### ISSUE TITLE
Crashing with log

### ISSUE THREAD

**Issue by magonzale192** [BearishSun/BansheeEngine#10]
```
Fatal error occurred and the program has to terminate!
RenderingAPIException - Cannot create DepthStencilView: 
in struct ID3D11DepthStencilView *__cdecl BansheeEngine::D3D11TextureView::createDSV(class BansheeEngine::D3D11TextureCore *,unsigned int,unsigned int,unsigned int,bool) [Source\BsD3D11TextureView.cpp:248]

Stack trace: 
BansheeEngine::D3D11TextureView::createDSV() - 0x8791387193498 File[bsd3d11textureview.cpp:248 (289)] Module[BansheeD3D11RenderAPI.dll]
BansheeEngine::D3D11TextureView::D3D11TextureView() - 0x8791387187772 File[bsd3d11textureview.cpp:25 (35)] Module[BansheeD3D11RenderAPI.dll]
BansheeEngine::D3D11TextureCore::createView() - 0x8791387275788 File[bsd3d11texture.cpp:794 (36)] Module[BansheeD3D11RenderAPI.dll]
BansheeEngine::TextureCore::requestView() - 0x8791272879238 File[bstexture.cpp:251 (0)] Module[BansheeCore.dll]
BansheeEngine::D3D11RenderWindowCore::createSizeDependedD3DResources() - 0x8791387244737 File[bsd3d11renderwindow.cpp:651 (50)] Module[BansheeD3D11RenderAPI.dll]
BansheeEngine::D3D11RenderWindowCore::initialize() - 0x8791387237170 File[bsd3d11renderwindow.cpp:152 (0)] Module[BansheeD3D11RenderAPI.dll]
BansheeEngine::CoreObject::executeGpuCommand() - 0x8791271833523 File[bscoreobject.cpp:148 (0)] Module[BansheeCore.dll]
std::_Func_impl const & __ptr64,std::function),std::shared_ptr const & __ptr64,std::function & __ptr64>,std::allocator,void>::_Do_call() - 0x8791271834455 File[functional:209 (0)] Module[BansheeCore.dll]
BansheeEngine::CommandQueueBase::playbackWithNotify() - 0x8791271828913 File[bscommandqueue.cpp:127 (0)] Module[BansheeCore.dll]
BansheeEngine::CoreThread::runCoreThread() - 0x8791271329435 File[bscorethread.cpp:124 (0)] Module[BansheeCore.dll]
BansheeEngine::PooledThread::run() - 0x8791390506316 File[bsthreadpool.cpp:125 (0)] Module[BansheeUtility.dll]
std::_LaunchPad >,std::default_delete > > > >::_Run() - 0x8791390512021 File[xthread:248 (0)] Module[BansheeUtility.dll]
std::_Pad::_Call_func() - 0x8791390504249 File[xthread:208 (0)] Module[BansheeUtility.dll]
0x8791286579933 Module[ucrtbase.DLL]
0x1994676717 Module[kernel32.dll]
0x1996993393 Module[ntdll.dll]
```

I'm using Windows 7 x64.
I have all dependencies installed.

**Comment by BearishSun** [comment]
Thanks for your report. Off the top of my head I have no idea what might be causing it.

Can you provide some more information? More specifically:
 - Is this crash happening with the editor, the example project, built game or are you running custom code?
 - At what point in the application does the error happen? (e.g. during startup, after you click/add something)
 - What GPU are you running?

**Comment by MikyGonzalez** [comment]
Sure.

The crash happend when I try open the editor (while startup). Executable is downloaded from description.

I'm executing on GT 540M (laptop).

**Comment by BearishSun** [comment]
It is probably something specific to your hardware. I'll see what I can do if I come across similar hardware. Or if you want to try manually compiling the editor debugging the problem yourself I can guide you.

**Comment by MikyGonzalez** [comment]
Ok, thanks for supporting.

I'll compile when I get time.

**Comment by MikyGonzalez** [comment]
You can close now. It's working! (I'm on a developer computer, I will test on my personal computer but this look nice), still with the hard work! Congratz.

**Comment by BearishSun** [comment]
Awesome!

**Comment by MikyGonzalez** [comment]
Sorry for say this, but this still not working, so I think this commit should be re-open.  It's happend once logo is showed. 

Log's contain a lot of warnings:

`Warning	Cannot find parameter with the name 'matWorldViewProj'
Warning	Cannot find parameter with the name 'colorIndex'
Warning	Cannot find parameter with the name 'matWorldViewProj'
Warning	Cannot find parameter with the name 'colorIndex'
Warning	Cannot find texture parameter with the name 'mainTexture'
Warning	Cannot find parameter with the name 'alphaCutoff'
Warning	Cannot find parameter with the name 'matWorldViewProj'`

But error produced is:

`Fatal error occurred and the program has to terminate!
Unhandled exception at 0x8791523138479. Access violation reading 0x40.

Stack trace: 
BansheeEngine::D3D11InputLayoutManager::addNewInputLayout() - 0x8791523138479 File[bsd3d11inputlayoutmanager.cpp:120 (0)] Module[BansheeD3D11RenderAPI.dll]
BansheeEngine::D3D11InputLayoutManager::retrieveInputLayout() - 0x8791523138001 File[bsd3d11inputlayoutmanager.cpp:72 (0)] Module[BansheeD3D11RenderAPI.dll]
BansheeEngine::D3D11RenderAPI::applyInputLayout() - 0x8791523195864 File[bsd3d11renderapi.cpp:1145 (47)] Module[BansheeD3D11RenderAPI.dll]
BansheeEngine::D3D11RenderAPI::drawIndexed() - 0x8791523189508 File[bsd3d11renderapi.cpp:639 (0)] Module[BansheeD3D11RenderAPI.dll]
BansheeEngine::RendererUtility::draw() - 0x8791336857419 File[bsrendererutility.cpp:314 (0)] Module[BansheeEngine.dll]
BansheeEngine::GUIManagerCore::render() - 0x8791337189869 File[bsguimanager.cpp:1814 (72)] Module[BansheeEngine.dll]
BansheeEngine::RenderBeast::renderOverlay() - 0x8791540418219 File[bsrenderbeast.cpp:804 (0)] Module[RenderBeast.dll]
BansheeEngine::RenderBeast::renderAllCore() - 0x8791540412151 File[bsrenderbeast.cpp:516 (0)] Module[RenderBeast.dll]
BansheeEngine::CommandQueueBase::playbackWithNotify() - 0x8791340735729 File[bscommandqueue.cpp:127 (0)] Module[BansheeCore.dll]
BansheeEngine::CommandQueueBase::playback() - 0x8791340735943 File[bscommandqueue.cpp:141 (0)] Module[BansheeCore.dll]
BansheeEngine::CommandQueueBase::playbackWithNotify() - 0x8791340735729 File[bscommandqueue.cpp:127 (0)] Module[BansheeCore.dll]
BansheeEngine::CoreThread::runCoreThread() - 0x8791340235099 File[bscorethread.cpp:124 (0)] Module[BansheeCore.dll]
BansheeEngine::PooledThread::run() - 0x8791537417132 File[bsthreadpool.cpp:124 (0)] Module[BansheeUtility.dll]
std::_LaunchPad >,std::default_delete > > > >::_Run() - 0x8791537422693 File[xthread:250 (0)] Module[BansheeUtility.dll]
std::_Pad::_Call_func() - 0x8791537415065 File[xthread:210 (0)] Module[BansheeUtility.dll]
0x8791299636765 Module[ucrtbase.DLL]
0x1999657405 Module[kernel32.dll]
0x2000921313 Module[ntdll.dll]`

**Comment by BearishSun** [comment]
Okay. So it works on the developer computer, but not on your personal computer? Or does it not work on the developer computer either?

**Comment by MikyGonzalez** [comment]
It don't work now, on a developer computer it worked, but I will do more tests. Do you need some information?

I'm using x64 Windows 7, .NET Framework full, Nvidia last drivers (Geforce GT 540M). 4 GB RAM.

Cause error access violation, I think it could be cause a leak or accessing a not reserved memory (has you checked code with Valgrind?); If I get time I will do myself.

For example, if you access some value out of program memory on your computer it could be zero, but on others it could be different (not managed). It's the only thing I think it could be.

**Comment by BearishSun** [comment]
It could be that. But those warnings you're getting shouldn't be there, it's as if shader failed to compile properly, which makes me think it has to do something with your GPU (which would be consistent with your previous error, which also seemed GPU related). Although I checked your GPU specs and it should be fully supported, so I don't know. I need to think about this some more.

**Comment by BearishSun** [comment]
I can't think of anything to try on my end. There are a few things you could try:
 - Try installing DirectX SDK: https://www.microsoft.com/en-us/download/details.aspx?id=6812.
 - If it still doesn't work try installing Windows SDK: https://www.microsoft.com/en-us/download/details.aspx?id=8279.

If it still doesn't work see if you can compile the code on your own end using Visual Studio 2015 (it's a free download, in case you never used it). Follow the compile instructions on the GitHub page, and download dependencies/data folder along with the source code. Then open up the BansheeEngine.sln in Build/VS2015 folder, right click on the BansheeEditorExec and hit Debug->Start new instance. See if it runs then, and if not, does it report any additional information.

And if that still produces the same result try compiling just the example project and see if you run into issues there. Right click on the ExampleProject in Visual Studio and hit Debug->Start new instance.

**Comment by MikyGonzalez** [comment]
I got some free time, I have DXSDK and WSDK already. I will try compiling myself (I will post when succed).

**Comment by gszauer** [comment]
I'm getting the ```Unhandled exception at 0x8791523138479. Access violation reading 0x40.``` error as well. Both DXSDK and WSDK are installed, running on Windows 7. If having the .dmp file would help i can provide it.

Getting the same error when compiling from source.

Error happens when first launching editor. splash screen shows up, black window shows up, error dialog appears.

**Comment by BearishSun** [comment]
Please do, I'd love to take a closer look.

If you have a chance, try compiling ExampleProject. It skips all the editor functionality, and at least we can find out if the error is in something editor specific or not.

**Comment by gszauer** [comment]
Happens on both x86 and 64. The Example Project crashes too, but in a much later spot. Something about binding a shader. This is my .dmp file:

https://www.dropbox.com/s/sb74f6e7ww0qzho/release_20160510_1608.zip?dl=0

**Comment by BearishSun** [comment]
I think some of the shaders fail to compile and then tries to access a shader vertex declaration that doesn't exist, and crashes. It's hard to tell for sure from the minidump though.

If you wouldn't mind taking a closer look, you could try placing a breakpoint in BsD3D11GpuProgram.cpp, populateParametersAndConstants(), at line 133. And then monitor all shaders as they're created and check if "mInputDeclaration" is null for any. If it's null then you could dig deeper into it's creation method to find out why.

Another thing you can check, in that same file, under compileMicrocode(), line 103 and see if the compilation fails for any of the shaders. If so let me know which and the error message.

**Comment by raizam** [comment]
Hey @BearishSun, how about using the bgfx library? https://github.com/bkaradzic/bgfx

**Comment by magonzale192** [comment]
@BearishSun Hello, I checked with last RELEASE 4, this issue not has beed fixed yet. I paste trace:

`
Fatal error occurred and the program has to terminate!
Unhandled exception at 0x8791522636513. Access violation reading 0x40.

Stack trace:
BansheeEngine::D3D11InputLayoutManager::addNewInputLayout() - 0x8791522636513 File[bsd3d11inputlayoutmanager.cpp:120 (0)] Module[BansheeD3D11RenderAPI.dll]
BansheeEngine::D3D11InputLayoutManager::retrieveInputLayout() - 0x8791522635985 File[bsd3d11inputlayoutmanager.cpp:72 (0)] Module[BansheeD3D11RenderAPI.dll]
BansheeEngine::D3D11RenderAPI::applyInputLayout() - 0x8791522754542 File[bsd3d11renderapi.cpp:1210 (49)] Module[BansheeD3D11RenderAPI.dll]
BansheeEngine::D3D11RenderAPI::drawIndexed() - 0x8791522746068 File[bsd3d11renderapi.cpp:704 (0)] Module[BansheeD3D11RenderAPI.dll]
BansheeEngine::RendererUtility::draw() - 0x8791409961168 File[bsrendererutility.cpp:296 (0)] Module[BansheeEngine.dll]
BansheeEngine::SpriteMaterial::render() - 0x8791409705950 File[bsspritematerial.cpp:90 (0)] Module[BansheeEngine.dll]
BansheeEngine::GUIManagerCore::render() - 0x8791409292440 File[bsguimanager.cpp:1826 (152)] Module[BansheeEngine.dll]
BansheeEngine::RenderBeast::renderOverlay() - 0x8791571362073 File[bsrenderbeast.cpp:805 (0)] Module[RenderBeast.dll]
BansheeEngine::RenderBeast::renderAllCore() - 0x8791571358345 File[bsrenderbeast.cpp:596 (0)] Module[RenderBeast.dll]
BansheeEngine::CommandQueueBase::playbackWithNotify() - 0x8791365111915 File[bscommandqueue.cpp:127 (0)] Module[BansheeCore.dll]
BansheeEngine::CommandQueueBase::playback() - 0x8791365112135 File[bscommandqueue.cpp:141 (0)] Module[BansheeCore.dll]
BansheeEngine::CommandQueueBase::playbackWithNotify() - 0x8791365111915 File[bscommandqueue.cpp:127 (0)] Module[BansheeCore.dll]
BansheeEngine::CoreThread::runCoreThread() - 0x8791365167409 File[bscorethread.cpp:124 (0)] Module[BansheeCore.dll]
BansheeEngine::PooledThread::run() - 0x8791510518556 File[bsthreadpool.cpp:125 (0)] Module[BansheeUtility.dll]
std::_LaunchPad >,std::default_delete > > > >::_Run() - 0x8791510524485 File[xthread:250 (0)] Module[BansheeUtility.dll]
std::_Pad::_Call_func() - 0x8791510516489 File[xthread:210 (0)] Module[BansheeUtility.dll]
0x8791514448605 Module[ucrtbase.DLL]
0x1997167085 Module[kernel32.dll]
0x1998439745 Module[ntdll.dll]
`

**Comment by BearishSun** [comment]
Hi, release 0.4 is VERY old and not representative of the current code. If you can reproduce the issue on the latest version compiled from source it would be beneficial (and it would also allow me to better see what is causing that issue, since I cannot reproduce it).
