### ISSUE TITLE
BsString reading access violation

### ISSUE THREAD

**Issue by htmlboss** [BearishSun/BansheeEngine#100]
I just updated my fork and successfully rebuilt the engine with the Vulkan and DX11 APIs, but now I'm getting a new null access violation when running the `BansheeEditorExec` project in VS 2017. The other example projects run fine. Any ideas?

![image](https://user-images.githubusercontent.com/5572045/32122655-adf8103c-bb3b-11e7-8744-8b853540856c.png)

**Comment by BearishSun** [comment]
Binary format for resources has very recently changed, and your screenshot suggests it is trying to read an old-format file. I can't tell which one without a full call stack, but quite possibly it's the Data/Settings.asset. Try deleting that file, and it should be re-created using the new format.

**Comment by htmlboss** [comment]
That worked. I deleted the Settings.asset, re-ran cmake, and did a full rebuild. Back to working like a charm! 

On another note, should I post a new issue about another null access violation when clicking the "cancel" button in the project manager window?

**Comment by BearishSun** [comment]
Great. I'm aware of the crash on shutdown, so no need to open an issue for it.
