### ISSUE TITLE
Question about planet-scale rendering

### ISSUE THREAD

**Issue by htmlboss** [BearishSun/BansheeEngine#101]
Hi again! I'm very interested in implementing a procedural planet rendering system. In your opinion, do you think Banshee would be capable of driving such a technique? From poking around in the example code, would I be correct in focussing on the low-level rendering project? I know there are a ton of features that I'll have to implement myself (frustum culling, quadtrees, etc), but I'm just looking for a well-structured and modern codebase to start this research 😺

**Comment by BearishSun** [comment]
It is definitely capable and was designed to support similar endeavors. You should take a look at the documentation for the low-level rendering API (basically a thin wrapper around Vulkan/DirectX/OpenGL) which gives you full control over rendering. You can write a renderer extension that allows you do draw your own graphics without having to dig into renderer internals. Or if you wish you can just modify the renderer straight up (RenderBeast project) - take a look at the RenderBeast class, all rendering originates from there. There are also manuals on mentioned topics in the online documentation. You are correct that low-level rendering example should be your starting point.
