### ISSUE TITLE
Can't build on Linux (Mint 18.2 / Ubuntu 16.04)

### ISSUE THREAD

**Issue by jonbitzen** [BearishSun/BansheeEngine#105]
I'm trying to build in Linux Mint 18.2, which is an Ubuntu 16.04 derivative (so I have more or less the same packages)

I run into two errors:

1.  Broken Makefile generated by CMake 3.9

BansheeUtility/CMakeFiles/BansheeUtility.dir/flags.make:6: *** recipe commences before first target.  Stop.
CMakeFiles/Makefile2:156: recipe for target 'BansheeUtility/CMakeFiles/BansheeUtility.dir/all' failed
make[1]: *** [BansheeUtility/CMakeFiles/BansheeUtility.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

This first one is caused by a line break in the makefile.  If you remove the linebreak the compile can proceed.

2.  A Compile / Link Error

[  9%] Linking CXX shared library /home/jrailsback/Documents/BansheeEngine/bin/x64/Release/libBansheeUtility.so
clang: error: no input files
BansheeUtility/CMakeFiles/BansheeUtility.dir/build.make:1922: recipe for target '/home/jrailsback/Documents/BansheeEngine/bin/x64/Release/libBansheeUtility.so' failed
make[2]: *** [/home/jrailsback/Documents/BansheeEngine/bin/x64/Release/libBansheeUtility.so] Error 1
CMakeFiles/Makefile2:156: recipe for target 'BansheeUtility/CMakeFiles/BansheeUtility.dir/all' failed
make[1]: *** [BansheeUtility/CMakeFiles/BansheeUtility.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

Before attempting to compile, I followed all the directions regarding setting up dependencies, as well as ensuring that "cc" and "c++" were linked to clang 4.0.

Thanks,

jonbitzen

**Comment by BearishSun** [comment]
The second error also sounds like a broken makefile. Can you please post the log output during CMake step?

**Comment by jonbitzen** [comment]
OK, so I double-checked my CMake version first.  Typing cmake --version I get the following:

cmake version 3.9.6

CMake suite maintained and supported by Kitware (kitware.com/cmake).

I've attached a text file with my CMake output, as well as the two make files referenced above.  Let me know if I can gather anything else.

Please note I added ".txt" extension to the makefiles to get past the attachment filter, but I have not otherwise altered the files.

Thanks,

jonbitzen

[cmake-output.txt](https://github.com/BearishSun/BansheeEngine/files/1485705/cmake-output.txt)

[flags.make.txt](https://github.com/BearishSun/BansheeEngine/files/1485706/flags.make.txt)
[build.make.txt](https://github.com/BearishSun/BansheeEngine/files/1485707/build.make.txt)

**Comment by BearishSun** [comment]
Thanks. I've tracked down and removed the line break causing the first error. I still don't know what's causing the second one. 

Can you try replacing `Source/CMakeLists.txt` with
[CMakeLists.txt](https://github.com/BearishSun/BansheeEngine/files/1485917/CMakeLists.txt) and see if that resolves the first issue - and perhaps even the second issue?

If the second issue isn't resolve, let me know and I'll dig deeper.

**Comment by jonbitzen** [comment]
Progress!

That resolved both issues.  Now there is a new one.  Here is the error:

[  9%] Linking CXX shared library /home/jrailsback/Documents/BansheeEngine/bin/x64/Release/libBansheeUtility.so
[  9%] Built target BansheeUtility
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

It did everything correctly up to and including building that shared object - I checked and it definitely built.  Previously the second error prevented that library from being built.
 
Now it looks like it's stuck at the next target.  I've attached the Makefile for reference.

Thanks,

jonbitzen

[Makefile.txt](https://github.com/BearishSun/BansheeEngine/files/1485978/Makefile.txt)

**Comment by BearishSun** [comment]
Good to hear that fixes the initial issue. Can you try running `make VERBOSE=1` and then paste the output.

**Comment by jonbitzen** [comment]
Here's the verbose output, attached.

[makefile-output.txt](https://github.com/BearishSun/BansheeEngine/files/1488104/makefile-output.txt)

**Comment by BearishSun** [comment]
It seems like the `-no-pie` flag isn't supported on the Clang version you are using. This flag is used on lines 175 through 177 of `Source/CMakeLists.txt` (the one I sent you):
```
	set(CMAKE_EXE_LINKER_FLAGS_DEBUG "-s -no-pie")
	set(CMAKE_EXE_LINKER_FLAGS_OPTIMIZEDDEBUG "-s -no-pie")
	set(CMAKE_EXE_LINKER_FLAGS_RELEASE "-s -no-pie")
```

What you could try is replacing the flag with `-fno-pie`. If that doesn't work, then you can try omitting the flag entirely, although then you might end up with other linker errors.

Alternatively you could compile using GCC until I have more time on my hands to test the Clang build chain more thoroughly.

**Comment by jonbitzen** [comment]
Hey so those changes got me a bit further, but I gave up on Clang and went GCC 7.  I'd really just been using Clang 4 since it was already on my machine.

Anyway it works and starts.  I'm having some other runtime things going on now, but I'll open another issue for that if I dont see it addressed elsewhere in your open issues list.

Might want to consider editing the build instructions maybe recommend Clang 5 as a minimum.  I haven't tried it yet, but I'm certain Clang 4 wont work.

Thanks for your help!

**Comment by BearishSun** [comment]
No problem. I'll take a closer look at Clang on Linux and update the instructions accordingly.

Regarding runtime, editor is pretty unstable at the moment while the C++ framework should be in a considerably better state. Just something to be wary about.
