### ISSUE TITLE
Linux Cmake Compile Error: can't generate script bindings

### ISSUE THREAD

**Issue by pengyz** [BearishSun/BansheeEngine#106]
I try compile the engine on linux. My OS is ArchLinux x64.
And cmake failed, error message like this below:
````bash
cmake -DCMAKE_CXX_COMPILER_ID=Clang -DBUILD_SCOPE=Framework -DCMAKE_BUILD_TYPE=debug ../Source/
-- Looking for BansheeSBGen installation...
-- ...BansheeSBGen OK.
-- Generating script bindings, please wait...
CMake Error at CMake/GenerateScriptBindings.cmake:88 (message):
  Failed to generate script bindings.
Call Stack (most recent call first):
  CMakeLists.txt:259 (include)
````

How can I fix it? I have no idea about it.
I try to use -DBUILD_SCOPE=Framework to avoid generate script binding, but it doesn't work.

Is there anyone who can help me? thanks a lot.

**Comment by BearishSun** [comment]
I've recently started building the SBGen executable using an automated build system on Travis, but it appears to trigger a segmentation fault when executed on certain Linux systems, including yours.

I've rebuilt the executable myself and updated the dependencies package. You should delete your `Dependencies` folder and then re-run CMake, after which it will fetch the updated dependencies and script binding generation should go through.

Also note that Clang build is not very well tested and you are advised to use GCC 7, or you might experience other issues during the build process.

**Comment by pengyz** [comment]
Thanks for your answer.

I'll try it later. Hops it works.

**Comment by pengyz** [comment]
I try it again with the new prebuild deps, now SBGen works correctly.
But There have some other compile errors:
````bash
[ 66%] Building CXX object SBansheeEngine/CMakeFiles/SBansheeEngine.dir/__/Generated/Engine/Source/BsScriptAsyncOpEx.generated.cpp.o
[ 66%] Building CXX object SBansheeEngine/CMakeFiles/SBansheeEngine.dir/__/Generated/Engine/Source/BsScriptAudio.generated.cpp.o
[ 66%] Building CXX object SBansheeEngine/CMakeFiles/SBansheeEngine.dir/__/Generated/Engine/Source/BsScriptAudioClip.generated.cpp.o
Generated/AsyncOpEx.generated.cs(23,10): error CS0246: The type or namespace name 'ScriptObjectBase' could not be found (are you missing a using directive or an assembly reference?)
Generated/AsyncOpEx.generated.cs(37,25): error CS0246: The type or namespace name 'ScriptObjectBase' could not be found (are you missing a using directive or an assembly reference?)

````
Also, ScriptObjectBase don't have a default constructor:
````bash
/home/peng/workspace/BansheeEngine/Build/Generated/Engine/Source/BsScriptAsyncOpEx.generated.cpp: 在静态成员函数‘static bs::ScriptObjectBase bs::ScriptAsyncOpEx::Internal_getReturnValue(bs::ScriptAsyncOpEx*)’中:
/home/peng/workspace/BansheeEngine/Build/Generated/Engine/Source/BsScriptAsyncOpEx.generated.cpp:46:20: 错误：no matching function for call to ‘bs::ScriptObjectBase::ScriptObjectBase()’
   ScriptObjectBase tmp__output;
                    ^~~~~~~~~~~
````

I try add one just like this:
````C++
ScriptObjectBase::ScriptObjectBase() : mManagedInstance(nullptr) {
  ScriptObjectManager::instance().registerScriptObject(this);
}
````
I don't know if it works. And there always an C# error.

**Comment by BearishSun** [comment]
It appears the SBGen version you are running is not the latest one, since it generates invalid .cpp and .cs files. I'm not sure how could this happen - did you perhaps attempt to install dependencies manually or have moved Banshee back to an earlier commit?

In order to resolve it I suggest doing a fresh checkout and trying it again, if that doesn't fix it let me know and we can debug it further.

**Comment by pengyz** [comment]
Ok, Thanks for your answer.

Yup, I download it manually. Unfortunately, I can't download it via cmake beacuse the network reason. Cmake would always failed.  Seems that I need a better VPN and give cmake another chance.

My friend, thank you very much for your helping. You a really a nice guy. :-)

**Comment by pengyz** [comment]
````bash
cmake -G"CodeBlocks - Unix Makefiles" ../Source/
-- Looking for BansheeSBGen installation...
-- ...BansheeSBGen OK.
-- Generating script bindings, please wait...
Unable to map type "ScriptObjectBase". Assuming same name as source.
Unable to map type "ScriptObjectBase". Assuming same name as source.
Unable to map type "ScriptObjectBase". Assuming same name as source.
Unable to map type "ScriptObjectBase". Assuming same name as source.
Unable to map type "ScriptObjectBase". Assuming same name as source.
Unable to map type "ScriptObjectBase". Assuming same name as source.
Unable to map type "ScriptObjectBase". Assuming same name as source.
Unable to map type "ScriptObjectBase". Assuming same name as source.
Unable to map type "ScriptObjectBase". Assuming same name as source.
Warning: Cannot find identifier referenced by the @copydoc command: " Skybox::getBrightness ".
-- ...scripting binding generation OK.
-- Looking for snappy installation...
-- ...snappy OK.
-- Looking for LibUUID...
-- ...LibUUID OK.
-- Looking for nvtt installation...
-- ...nvtt OK.
-- Looking for OpenAL installation...
-- ...OpenAL OK.
-- Looking for ogg installation...
-- ...ogg OK.
-- Looking for vorbis installation...
-- ...vorbis OK.
-- Looking for FLAC installation...
-- ...FLAC OK.
-- Looking for PhysX installation...
-- ...PhysX OK.
-- Looking for FBXSDK installation...
-- ...FBXSDK OK.
-- Looking for freetype installation...
-- ...freetype OK.
-- Looking for freeimg installation...
-- ...freeimg OK.
-- Looking for mono installation...
-- ...mono OK.
-- Looking for bison installation...
-- ...bison OK.
-- Looking for flex installation...
-- ...flex OK.
-- Building BSL lexer/parser...
-- Looking for XShaderCompiler installation...
-- ...XShaderCompiler OK.
-- Looking for Mono compiler (mcs) and xbuild installation...
-- ...mcs and xbuild OK.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/peng/workspace/BansheeEngine/Build
````

Seems there is also something error when generate scripting files :-（

**Comment by BearishSun** [comment]
This happens with default SBGen provided in the automatically downloaded dependencies (i.e. no manual install/download)?

Also, can you confirm this happens with a fresh checkout?

**Comment by BearishSun** [comment]
SBGen is no longer a required dependency by default. If needed Linux users need to compile it from the ground up. Closing the issue as it is no longer relevant.
