### ISSUE TITLE
EDITOR: Adding a directional light crash the application

### ISSUE THREAD

**Issue by christianclavet** [BearishSun/BansheeEngine#111]
Hi, Tested creating lights in the editor:

Creation of 1 point light - Work (Was also to tweak values including colors in the inspector window)
Creation of 1 spot light - Work (Was also to tweak values including colors in the inspector window)
Creation of 1 directionnal light -Crash.

How to reproduce:
Simply press the SUN icon in the menu toolbar:
![directionallight](https://user-images.githubusercontent.com/13395943/33528398-bde9a168-d82d-11e7-8140-68bd80db828f.JPG)

Here is the log output from my optimized debug build (3 dec. 2017)

Banshee Engine Log

System information

Banshee version: 0.4

OS version: Windows 10 64-bit

CPU vendor: GenuineIntel

CPU name: Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz

CPU clock speed: 3511Mhz

CPU core count: 8

GPU: NVIDIA Corporation GeForce GTX 1080/PCIe/SSE2

Log entries

Type | Description
-- | --
Error | A fatal error occurred and the program has to terminate!Unhandled exception at 0x140708552278171. Access violation reading 0x4.Stack trace: bs::ct::ShadowRendering::renderShadowOcclusion() - 0x140708552278171 File[bsshadowrendering.cpp:901 (0)] Module[RenderBeast.dll]bs::ct::RCNodeStandardDeferredLighting::render() - 0x140708552394257 File[bsrendercompositor.cpp:659 (0)] Module[RenderBeast.dll]bs::ct::RenderCompositor::execute() - 0x140708552383500 File[bsrendercompositor.cpp:146 (0)] Module[RenderBeast.dll]bs::ct::RenderBeast::renderView() - 0x140708552053976 File[bsrenderbeast.cpp:406 (0)] Module[RenderBeast.dll]bs::ct::RenderBeast::renderViews() - 0x140708552053410 File[bsrenderbeast.cpp:349 (0)] Module[RenderBeast.dll]bs::ct::RenderBeast::renderAllCore() - 0x140708552052807 File[bsrenderbeast.cpp:317 (0)] Module[RenderBeast.dll]std::_Func_impl,std::allocator,void>::_Do_call() - 0x140708552116780 File[functional:214 (0)] Module[RenderBeast.dll]bs::CommandQueueBase::playbackWithNotify() - 0x140708275018086 File[bscommandqueue.cpp:127 (0)] Module[BansheeCore.dll]bs::CommandQueueBase::playback() - 0x140708275018311 File[bscommandqueue.cpp:141 (0)] Module[BansheeCore.dll]bs::CommandQueueBase::playbackWithNotify() - 0x140708275018086 File[bscommandqueue.cpp:127 (0)] Module[BansheeCore.dll]bs::CoreThread::runCoreThread() - 0x140708275078654 File[bscorethread.cpp:119 (0)] Module[BansheeCore.dll]bs::PooledThread::run() - 0x140708394098684 File[bsthreadpool.cpp:125 (0)] Module[BansheeUtility.dll]std::_LaunchPad >,std::default_delete > > > >::_Run() - 0x140708394104437 File[xthread:250 (0)] Module[BansheeUtility.dll]std::_Pad::_Call_func() - 0x140708394096585 File[xthread:210 (0)] Module[BansheeUtility.dll]0x140709009741957 Module[ucrtbase.dll]0x140709018279908 Module[KERNEL32.DLL]0x140709056409489 Module[ntdll.dll]

**Comment by BearishSun** [comment]
Resolved with 5ec5c201cb448e9a4e1a7288fd26dfd6457dcaff

**Comment by christianclavet** [comment]
Hi, Updated and rebuilded as of today (12/04/17). The issue is resolved. Creating a new directional light doesnt crash the application anymore, and I can enable shadows. So the fix is confirmed.
