### ISSUE TITLE
Visual: Flickering when using the SSR Post shader (Default)

### ISSUE THREAD

**Issue by christianclavet** [BearishSun/BansheeEngine#112]
Hi, Checked more and found the item activation that cause the little visual flickering

From [this previous report](https://github.com/BearishSun/BansheeEngine/issues/107)  

Here is the visual problem in a screenshot.
![](https://user-images.githubusercontent.com/13395943/33510683-f6b028c0-d6dc-11e7-9fd9-bb3486eded56.JPG)

This has only been observed inside the editor (0.4 - 12/04/17) and the PBR demo.

How to disable/enable the flickering:
1. You need a DEBUG or OPTIMIZED DEBUG BUILD. (Mine is 12/4/2017)
2. You need at least a scene (Take the pistol with the PBR textures applied to it to test)
3. You need at least a skybox with an image
4. Look at the pistol from an angle and not perpendicular to it.
5. You need to click on the hierachy item named: "Scene Camera". (red items only on theses builds) Then look at the properties windows
6. Expand the "Render Settings" section under the Camera section.
7. Expand the Screen Space Reflection section
8. Check|Uncheck the ENABLED item and look if the flickering is enabled | disabled.

As a result, when SSR was disabled, the flickering was gone. 

As currently there is not any Light Probe at all in the scene and active perhaps explain the issue. How to have the reflection using the light probes instead|or with of the skybox?

**Comment by BearishSun** [comment]
With 1517308b3ba9b6059740eec60c0b103b791c81cf flickering should now be significantly reduced, to the point it shouldn't really be noticeable unless you look for it. It's not possible to completely eliminate it due to the nature of SSR, but it can be further reduced by increasing SSR quality and/or tweaking the lighting environment.
