### ISSUE TITLE
EDITOR: Can't apply any picture to the skybox|Reflection probes except the provided .asset example.

### ISSUE THREAD

**Issue by christianclavet** [BearishSun/BansheeEngine#115]
Build date: (16 december 2017)
Problem description:

Banshee **Skybox** can be assigned a picture to use. The only file that can be applied to it that work is:
**PaperMill_E_3k.hdr.asset**

Applying any other picture will make the background being black. Event the provided **PaperMill_E_3k.hdr** will not work and give also a black bacground. Only the one with the .asset extension will work.

Note: Tested also the "**Reflection Probe**" and it experience the same issue. If using an image, will see it's preview but the reflection is pure black. using a .asset file, will have the preview black, but the reflections will be there.

**Comment by BearishSun** [comment]
By default any texture is imported as a standard 2D texture, but skyboxes require cubemaps. Make sure texture is imported as a cubemap and cubemap source is set to a valid enum (Cylindrical for PaperMill texture). These properties can be changed in the Inspector after the texture is initially added to the project.

**Comment by christianclavet** [comment]
Confirmed. Set the texture as a cubemap. This issue can be closed. Thanks!

**Comment by christianclavet** [comment]
Sorry, Is there something I'm not doing correctly?

There is a representation of the HDR in Photoshop (32bit channel). Should be the same specs as your example:
![05-05_night_aa](https://user-images.githubusercontent.com/13395943/34082409-ecb68cc8-e32b-11e7-91f8-946e27e20619.jpg)

It should be spherical cubemap. So I defined it like that in the editor and pressed the **reimport** button.

Once applied to the skybox, the image is reversed and stretched.
![capture](https://user-images.githubusercontent.com/13395943/34082417-2a42b6a2-e32c-11e7-919f-9b3dc01901ff.JPG)

**Comment by BearishSun** [comment]
That looks like a Cylindical map, try using that option. Spherical maps look round with black corners.

**Comment by christianclavet** [comment]
Almost the same, here is a screen. I have changed it and pressed the REIMPORT button.
![capture](https://user-images.githubusercontent.com/13395943/34082471-15c30780-e32d-11e7-85e5-a171dae34389.JPG)

**Comment by BearishSun** [comment]
Tried with your texture and it looks okay on my end. Haven't had a chance to check but it might be due to OpenGL (I'm testing on DirectX), or it could some some bug in the editor that fails to refresh the texture properly after re-import.
