### ISSUE TITLE
Possibly a missing break statement?

### ISSUE THREAD

**Issue by darthdeus** [BearishSun/BansheeEngine#12]
I was just looking through the codebase and found what looks like a bug - missing break statement here https://github.com/BearishSun/BansheeEngine/blob/preview/Source/BansheeGLRenderAPI/Source/GLSL/src/BsGLSLGpuProgram.cpp#L123, which will cause `GL_TESS_EVALUATION_SHADER` to get overwritten.

**Comment by BearishSun** [comment]
Nice catch! Fixed on master.
