### ISSUE TITLE
EDITOR: Coordinates from a duplicated node that are parented take the local coordinates as position for the new node.

### ISSUE THREAD

**Issue by christianclavet** [BearishSun/BansheeEngine#121]
Hi,

I've been able to test more items, and when I duplicate an item that is parented to another, the copy will be at the coordinates of the local position to the world position.

How to replicate:
- Create an object an parent it to another.
- Duplicate the object (CTRL+D)
- Look at the position of the newly created object

**Comment by BearishSun** [comment]
Resolved with 1fefa8e76337d4800b58f524bef721538775637e.

**Comment by christianclavet** [comment]
Confirmed. I can duplicate items that are parented to others and their coordinates are ok.
Tested with a model, I downloaded on CADNAV and tested PBR materials, and duplicating of lights
![ironman](https://user-images.githubusercontent.com/13395943/34463957-5bddf39c-ee3b-11e7-9d33-fe6d3d77365c.JPG)

**Comment by BearishSun** [comment]
Awesome.

Prefab doesn't store meshes or materials directly (nor any other resource/asset), it just references them. If you delete them they will fail to load and not render. The components would remain and you would be able to assign different meshes/materials to those objects.

**Comment by christianclavet** [comment]
Thanks, I was not sure the prefab would get them all or just reference them. It would be nice to have a special type of prefab that would package the prefab for exchange. For now I will remember this and package using zip file and tell other to use the prefab to instantiate in the scene.
