### ISSUE TITLE
build pipeline

### ISSUE THREAD

**Issue by RevoluPowered** [BearishSun/BansheeEngine#123]
I'm playing around with a CI server at the moment, do you think you would benefit from having it configured for your project?

I'm setting it up for myself (because I'm testing your engine out) but if you want others to have access to it, give me a shout and I can give you and everyone else access.

**Comment by BearishSun** [comment]
I do plan on configuring Travis & Appveyor CI soon. If you do set up your own publicly feel free to share.

**Comment by RevoluPowered** [comment]
Cool, I will do!

I'm using https://www.gocd.org at home but may venture onto travis and
appveyor if I can
