### ISSUE TITLE
[BansheeSBGen] cmake failing on centos 7

### ISSUE THREAD

**Issue by RevoluPowered** [BearishSun/BansheeEngine#124]
cmake can't seem to find libstdc++ on a clean install of linux.

> 
> cmake ./Source 
> -- The C compiler identification is GNU 4.8.5
> -- The CXX compiler identification is GNU 4.8.5
> -- Check for working C compiler: /bin/cc
> -- Check for working C compiler: /bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /bin/c++
> -- Check for working CXX compiler: /bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> Defaulting to release build.
> -- Looking for BansheeSBGen installation...
> -- ...BansheeSBGen OK.
> -- Generating script bindings, please wait...
> /var/lib/go-agent/pipelines/banshee-engine/Dependencies/tools/BansheeSBGen/bin/BansheeSBGen: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /var/lib/go-agent/pipelines/banshee-engine/Dependencies/tools/BansheeSBGen/bin/BansheeSBGen)
> /var/lib/go-agent/pipelines/banshee-engine/Dependencies/tools/BansheeSBGen/bin/BansheeSBGen: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /var/lib/go-agent/pipelines/banshee-engine/Dependencies/tools/BansheeSBGen/bin/BansheeSBGen)
> /var/lib/go-agent/pipelines/banshee-engine/Dependencies/tools/BansheeSBGen/bin/BansheeSBGen: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /var/lib/go-agent/pipelines/banshee-engine/Dependencies/tools/BansheeSBGen/bin/BansheeSBGen)
> CMake Error at CMake/GenerateScriptBindings.cmake:98 (message):
>   Failed to generate script bindings.
> Call Stack (most recent call first):
>   CMakeLists.txt:274 (include)

Can you please look into this?

I've got **libstdc++-4.8.5-16** installed currently.

**Comment by BearishSun** [comment]
Compiling BansheeSBGen yourself will likely solve the problem. Source is available at https://github.com/BearishSun/BansheeSBGen.

The binary distribution has been causing problems on different distros so it will probably be removed eventually.

**Comment by RevoluPowered** [comment]
Thank you for the advice!

I'll fix that when I get home.

If you need help with anything you can give me a message on here, I've got
a bit of time spare

**Comment by BearishSun** [comment]
SBGen is no longer a required dependency by default. If needed Linux users need to compile it from the ground up. Closing the issue as it is no longer relevant.
