### ISSUE TITLE
[EDITOR - ANIMATON SPLITS] After splitting an animation in multiple parts, there are some issues with them.

### ISSUE THREAD

**Issue by christianclavet** [BearishSun/BansheeEngine#127]
Hi, Tried to split model animations in separate animation names with the editor tool.
Work correctly, by selecting the proper frames of animation, but there is a problem in the playback, as the mesh is distorded in some animation.

If this case, the first animations play ok, until it reach a frame and all other animation playback corrupt the mesh.

How to replicate:
- Use the provided scene of the "merc" and create an animation split for 7 animations
- Enter the 7 animation as in the screenshot or type those values:
death - 0 - 67
fire - 75 - 90
hit - 98 - 114
idle - 121 - 242
attack 1 - 250 - 280
run 292 - 316
walk 326 - 358
- Press the reimport button
- Look at the model when playing back idle, attack, run and walk animations
P.S. Tried the additive button, but the mesh seem to have "exploded". Not sure it's an issue, since I did not had additive animations.

![animationsplit](https://user-images.githubusercontent.com/13395943/34464159-3b1b1390-ee42-11e7-8aea-c87895f0e894.JPG)

**Comment by BearishSun** [comment]
This resolved with b6fa5e36c2ca3d36ffe8d9c7bef96a830c7a8add.
