### ISSUE TITLE
[CMAKE] Warning in generating script binding from source. (Jan 2, 2018)

### ISSUE THREAD

**Issue by christianclavet** [BearishSun/BansheeEngine#128]
Hi, Got this error while creating a new build today. I don't this will stop from creating them, since it's only a warning: (CMAKE)

Generating script bindings, please wait...
Warning: Cannot find identifier referenced by the @copydoc command: " Skybox::getBrightness ".

...scripting binding generation OK.

**Comment by BearishSun** [comment]
That has always been there, it won't cause any issues, it's only relevant for documentation and doesn't affect the code.
