### ISSUE TITLE
Depth Testing / Draw order / Clipping issue for near plane (OpenGL)

### ISSUE THREAD

**Issue by The5-1** [BearishSun/BansheeEngine#129]
BansheeGLRenderAPI

EDIT:
The near plane not updating was due to the CameraFlyer Component provided in ExampleGettingStarted  forcing the near plane to 5.0f! In the ExamplePhysicallyBasedShading it did not.

Setting the near plane to some notable value (5.0f or higher, depending on scene) reveals some drawing issues:
- Geometry in-front of the near plane seems to still draw.
- Geometry draws without depth testing, seemingly when geometry in-front of it would be clipped by the near plane. See Fig.1
- The clipping plane that might be the near plane does not correctly move with the frustum. See Fig.2.

Screenshots:

[Fig.1] Geometry being drawn independent of depth. Note the flower-pot drawing over the pillar. Near plane is 5.0f.
![Geometry drawing trough itself](https://user-images.githubusercontent.com/22944373/34536662-2d0d0fac-f0c6-11e7-9651-d58a93b10263.JPG)

[Fig.2] Note the strange clipping on the left curtain. Near plane is 5.0f.
![Strange clipping at courtain](https://user-images.githubusercontent.com/22944373/34537563-30fe50c8-f0c9-11e7-8182-3e1e8950d0f7.JPG)

[Fig.3] ExamplePhysicallyBasedShading with far plane set to 50.0f, near to 8.0f reveals issues.
![near close to far](https://user-images.githubusercontent.com/22944373/34538314-3be059fc-f0cc-11e7-8fba-4ebe3d667a43.JPG)

**Comment by BearishSun** [comment]
This is resolved with 631d3a29c2ad444c2fc03b7a2a4ac16d60529016.
