### ISSUE TITLE
Replace windows.h with std::chrono for time utils

### ISSUE THREAD

**Issue by npezolano** [BearishSun/BansheeEngine#13]
https://github.com/BearishSun/BansheeEngine/blob/preview/Source/BansheeUtility/Source/BsTime.cpp
https://github.com/BearishSun/BansheeEngine/blob/preview/Source/BansheeUtility/Source/Win32/BsWin32Timer.cpp

**Comment by BearishSun** [comment]
I'll fix that soon. Win32 version was used because earlier versions of chrono::high_resolution_clock in Microsoft's standard library weren't actually using high resolution timer. Looking at it now it appears fixed in VS2015.

**Comment by BearishSun** [comment]
Implemented on master. 

c168935089c50f781d59de3ce01f33b439cef8af
