### ISSUE TITLE
EDITOR Feature request: Scale UV in the material editor 

### ISSUE THREAD

**Issue by christianclavet** [BearishSun/BansheeEngine#132]
A scale UV GUI would be needed in the material editor or model to allow the user to scale the size of the texture on the model. Useful for seamless textures.

Why:
This feature is useless on a small model and would only work on a UV that **is for large models** (wall, floors, terrain) and would define the UV size for a texture to wrap over the model.

Started to make walls and the texture resolution would need to be 64k (65535pxx65535px) to have a good details. This is too big and the texture need to be seamless and tiled over the surface by scaling down the UV size.

Will be useful for the primitives too. as it could be used for create a "cheap" way to create interiors, until there more definitive tool. (CSG and|or vertex tool for example)

**Comment by BearishSun** [comment]
I agree this is a useful feature. For now you should be able to define the UV of the mesh itself (in the modeling tool, not in Banshee) to be tiled (larger than [0, 1] range) which should avoid the need for large textures.

**Comment by christianclavet** [comment]
This was added recently. So the issue can be closed.
