### ISSUE TITLE
EDITOR | ENGINE feature request: DECALS

### ISSUE THREAD

**Issue by christianclavet** [BearishSun/BansheeEngine#133]
Why in engine: (dynamic decals)
This can be used to project decals with a particle engine|ray casts and physic to have blood splats on impact, bullet holes, fire damage on explosions, etc. Could be generated by the engine and could create specific materials for them and use them in Banshee collision system.

Why in editor: (static decals)
Would be really useful for exterior|interior environment, to break the pattern of seamless textures that would be used for create big models (houses, big wall). User would select the brush and then click where to place it. Then a ray cast would do a collision on the environment and place the decal.

**Comment by BearishSun** [comment]
Decals are most certainly planned and are considered an important feature. They will be added likely very soon after the 1.0 release.

**Comment by christianclavet** [comment]
Thanks, Just saw them in the list now.
