### ISSUE TITLE
Shadows from point light source.

### ISSUE THREAD

**Issue by christianclavet** [BearishSun/BansheeEngine#139]
Hi,

I might have found an issue with the point light source shadows. Made a new build with your changes of today (9 jan 2018).

1 single point light source selected (in a scene of 2 point light sources):
![wrongshadow1](https://user-images.githubusercontent.com/13395943/34751396-5e2885cc-f57a-11e7-8203-16b828382fa1.JPG)
Here the shadow is present, but the shadow is not complete.

Here is the second point light source when it's selected. Of if I select the lights. Any shadow seem to vanish.
![shadows](https://user-images.githubusercontent.com/13395943/34751436-99dcbcfa-f57a-11e7-9f41-1f710ea7489a.JPG)
Perhaps there is something to do first.

The scene doesnt have any skybox, nor reflections probes. Just testing with the "basics" to see if the mesh would cast a shadow on the ground.

Edit: Done another test by putting everything as static. It improved a little the shadow, but still look strange: (2 points lights)
![static](https://user-images.githubusercontent.com/13395943/34752587-337cd308-f581-11e7-8a85-4d6689199a5c.JPG)

**Comment by BearishSun** [comment]
I've fixed a variety of shadow related issues during the last few days, which hopefully resolves this issue as well. Directional shadow issues mentioned in #155 should be resolved as well.

A few new properties regarding shadows has been exposed under Light and Camera. The most important one is Shadow Bias under Light. If you experience shadows that appear to "float" then reducing this value is a good idea, and if you experience "shadow acne" (ugly self-shadowing) then increasing the value is a good idea. Generally shadow acne should not be a problem as long as the shadow casting geometry has thickness (i.e. isn't just a single plane), so keeping the bias at 0 or negative is a good idea to reduce floating/light leaking (note, this is not the default as is results in serious acne for thin geometry).

**Comment by christianclavet** [comment]
Hi, I always model only the side of an object that will be seen, but not the other side. For shadows, should I enclose everything to make them "solid"?

**Comment by BearishSun** [comment]
Indeed. Combined with negative bias it looks the best (no floating shadows, or shadow acne) - at least in my experiments. If the geometry is thin (or has no back side at all) it results in extreme shadow acne with bias <= 0.

**Comment by christianclavet** [comment]
Ok. Then I'll will have to modify all the room assets I have made. I want them to look the best in Banshee. Thanks for the information!

**Comment by BearishSun** [comment]
Closing this as I believe all reported issues have been resolved.
