### ISSUE TITLE
Compilation issues

### ISSUE THREAD

**Issue by bensku** [BearishSun/BansheeEngine#140]
I have some issues compiling BansheeEngine. As seen [here](https://hastebin.com/bozuwanegi.pas), it seems to not recognize C++ types WString and String.

Previously I had encountered problem with CMake and BansheeSBGen, but that was solved by manually compiling BansheeSBGen from source. I made sure that all other required dependencies are present - not 100% sure if compiler finds them, though.

System information:
* Linux Mint 17.3 (based on Ubuntu 14.04.3) 64bit
* CMake 3.10.1 (from their PPA)
* Clang and LLVM 5.0 from their APT repositories
* Mono 5.4.1.6, XBuild 14.0
* libstdc++ 6 and 7 dev packages installed (from PPA), should have C++14 support

I hope I didn't miss anything obvious; I have little C++ experience, so the error message doesn't tell me much.

**Comment by BearishSun** [comment]
I have never properly tested Clang, so perhaps try using GCC.

**Comment by bensku** [comment]
Oh, that makes sense! I'll try that ASAP.

I generally use GCC too, but thought that whole project needs Clang; apparently only SBGen needs it, not as compiler but C++ parser.

**Comment by AndrzejOran** [comment]
I am still using commit https://github.com/BearishSun/BansheeEngine/commit/af46409c10d2ba94b978e7b756d90d75b3d3e97e as the latest commits are also giving me the same compilation errors.

I was curious if its related to this issue. https://github.com/BearishSun/BansheeEngine/issues/51

- Arch Linux 4.14.13-1
- Clion-EAP 173.4127.32-1 tried with GCC and G++
- CMake 3.9.6 (Clion EAP Bundled)

**Comment by bensku** [comment]
I have verified that the same thing happens with GCC/G++ 7 too.

**Comment by BearishSun** [comment]
The Linux build was broken in a few places, I just did a run-through and solved anything I found, see 66abaee367ebd4a76eabe4248867a0a5a4af89c2. Tested on Ubuntu 17.04 and GCC 7.2. The String/WString issue in particular was caused by incorrectly set up includes.

**Comment by bensku** [comment]
Seems that these bugs are gone now. Now only the fact that my distro ships older ld so I can't link with the binary dependencies. But it is not issue with BansheeEngine.
