### ISSUE TITLE
FreeImage undefined symbol

### ISSUE THREAD

**Issue by bensku** [BearishSun/BansheeEngine#143]
Trying to launch the editor leads to an interesting problem:
`./BansheeEditorExec: symbol lookup error: /home/benjami/Data/Koodaukset/BansheeEngine/bin/x64/Release/libBansheeFreeImgImporter.so: undefined symbol: FreeImage_Initialise`

I used ldd to check both libBansheeFreeImgImporter.so and BansheeEditorExec. Neither has FreeImage linked dynamically; is it supposed to be statically linked? Right now, it certainly is not.

I tried this with system-provided FreeImage, then compiled latest version myself (no difference). I also tested both G++ 7.2 and Clang 5 (which both compiled the whole project successfully!), without any difference. I'm using LLVM's ld, if that matters - however, it *should* be fully compatible with GNU one.

This might be an issue with my system though. I'll see if I can compile BansheeEngine on newer Ubuntu and test these binaries.

**Comment by BearishSun** [comment]
It's supposed to be statically linked. Can you try deleting the build folder, and re-running CMake? Up until today CMake was looking for the globally installed freeimg by default, which might be a shared library. Even after the update today CMake might cache the old location and still trying to link with the .so.

I haven't actually tried running the editor on Ubuntu today, as I compiled on a VM, so it's possible it's an actual problem with the build as well.

**Comment by bensku** [comment]
I did remove Build folder while switching from G++ to Clang for testing.

**Comment by BearishSun** [comment]
If you open up CMake GUI, generate the build files and tick the Advanced box it should show paths to all the dependencies it found. You can double-check if freeimg path points to a static library or if something is maybe getting messed up.

**Comment by bensku** [comment]
Both seem to point to Banshee's Dependencies folder.

**Comment by bensku** [comment]
I compiled FreeImage from source and put it there - that seems to work. However, I encounter another, puzzling error:
`Description: Could not load dynamic library libBansheeSL.so.  System Error: /home/benjami/Data/Koodaukset/BansheeEngine/bin/x64/Release/libBansheeSL.so: undefined symbol: _ZTTNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEE
`

I think something is seriously wrong with my build environment. Will post when I have found what it is.

**Comment by BearishSun** [comment]
I recompiled FreeImg and updated the dependencies package. I'm not sure what the actual issue was but it appears to load fine now. 

Your issue could be related to dependencies. BansheeSL in particular depends on the XShaderCompiler dependency. You could try compiling it manually (the particular version used by Banshee is available here: https://github.com/BearishSun/XShaderCompiler)

**Comment by bensku** [comment]
Managed to fix this by upgrading to Linux Mint 18. Mint 17 and Ubuntu 14.04 are just too old, trying to get them compile this is probably waste of time.
