### ISSUE TITLE
[EDITOR C# SCRIPT] Cannot assign script to item, How to test scripting?

### ISSUE THREAD

**Issue by christianclavet** [BearishSun/BansheeEngine#146]
I tried to assign a script to a item in the scene but it's not appearing as a new component for the item. So I don't know how to check and test scripting as for the moment (Jan 14 2018)

I was able to create a "generic" script and it work, have the script item in the ressources, but cannot do anything else.

**Comment by BearishSun** [comment]
This is resolved with 92c558bd6cccae70666d21f27446001f30e5d0f0. Note you will have to delete the existing script and create a new one for it to work.
