### ISSUE TITLE
[EDITOR - SCRIPT] Default scene is destroyed, because of a script that is present when saved.

### ISSUE THREAD

**Issue by christianclavet** [BearishSun/BansheeEngine#150]
Hi,

I added back the script of the walker you provided on the forum and applied it to the camera. It compiled and ran. But when closing the scene (I always save), it crashed.

When I tried to load it back, the scene file was gone.

I started it again in the debugger to see:
Output:
Exeption raised: read access violation, link_addr_volatile is 0xFFFFFFFFFFFFF

Stack calls:
BansheeMono.dll -> bs::MonoUtil:getObjectFromGCHandle() line 144
SBansheeEngine.dll -> bs::ManagedComponent::getManagedInstance() line 37
SBansheeEngine.dll -> bs:ManagedComponentRTTI:onSerializationStarted() line 76
BansheeCore.dll -> bs::Utility:findResourceDependenciesInternal() line 46,124,132
BansheeCore.dll -> bs::Utility:findResouceDependencies() line 14
BansheeCore.dll -> bs::Resources::save() line 575

Looking at this there was a problem when it was serializing the script to the scene file (probably)

**Comment by BearishSun** [comment]
I've submitted a fix for the script related crash, 87a5f4baaa6ad0ac857c404c0046dde97c211dbb.

Sadly I don't think there is a way to recover a scene destroyed by this issue, I thought it might still exist in the Internal folder but it appears to be gone from there as well. Sadly the crash happened while the scene was being saved, destroying it. I've updated the resource saving code so it handles crashes more gracefully in the future, but even with that there really are no guarantees what kind of damage some bug might do.

**Comment by christianclavet** [comment]
Cool! Thanks! I'll update my builds! :)
Perhaps you could rename the file as .old extension, create the updated file and delete the .old file once completed. If the file is not found, then try to locate the .old and rename it as it was (recovery)?

Don't worry about it, we're on alpha software, and this was to be expected. Just happy that it's fixed now!
