### ISSUE TITLE
Editor window blue on Linux

### ISSUE THREAD

**Issue by bensku** [BearishSun/BansheeEngine#153]
Editor seems to be a bit broken at the moment. Some [errors](https://hastebin.com/ukenadoqep.vbs) are produced to console, while the editor window opens; it is fully blue, without any readable text. Running Linux Mint 18 (Ubuntu 16.04), Nvidia GTX 750Ti (proprietary drivers) and two screens. Editor opens on my second screen, overlaps it and cannot be moved.

**Comment by BearishSun** [comment]
The first few messages regarding Jack should be normal I believe. It's just a way for OpenAL to query the audio system to use.

Regarding the errors about missing files. Are the files reported in the error log present? If they are, maybe it has something to do with their permissions.

**Comment by bensku** [comment]
Missing assets are not present. It is weird, since I stashed and pulled git repo, then compiled according to instructions.

**Comment by BearishSun** [comment]
Those assets are part of the Data archive downloaded during the build process. It's possible something went wrong during the download or extraction. If you delete `Data/.version` file and re-run CMake, it should attempt to re-download all such assets.

It's also possible something is going wrong during engine start-up and is possibly deleting the assets, although this is less likely.

**Comment by bensku** [comment]
Ok, I'll try re-running CMake and see if they are there, then run editor again and check if situation has changed.

**Comment by bensku** [comment]
Actually, the unlikely seems to be true in [this case](https://hastebin.com/tolehuyaja.cpp). Invalid cross-device link... I'm not 100% sure what that means, but I have a guess.

My system drive, /, is different than my drive mounted at /home. Actually, since I ran out of space with home directory, the folder where BansheeEngine resides is in yet another partition. FileSystem::moveFile does not actually *move* a file; it just renames it.

I'll create a pull request to fix this.

**Comment by BearishSun** [comment]
Sounds good. I think the right way to solve this is to attempt rename by default (which should work as long as the source and destination are on the same drive/partition). If that fails due to the cross device link error, then fallback on performing a copy followed by a delete.

**Comment by bensku** [comment]
Doing exactly that. It is apparently exactly what GNU mv does.

**Comment by bensku** [comment]
Works now with the change I pull requested.
