### ISSUE TITLE
Compiling for x86-64 - CMake generates with /machine:x86

### ISSUE THREAD

**Issue by DW01** [BearishSun/BansheeEngine#156]
There's likely a good reason for this behavior, but CMake generates a VS2017 solution explicitly incompatible with 64-bit compilation (/machine:x86). This seems odd to me as the project folder structure hints that compiling for 64-bit CPUs should be possible, but it throws a fit every time I remove the machine flag.

I've been out of the loop for a while with programming in general, so this is less a bug and more a general question; is building explicitly for x64 currently not possible?

**Comment by BearishSun** [comment]
64-bit is certainly possible, and it's the primary way to build the engine. Note that CMake has separate Visual Studio generators for 32-bit and 64-bit builds, so make sure you have selected the right one when creating the solution.

**Comment by DW01** [comment]
The GUI seems to only generate for 32-bit. Using the command line in the past has generate 32-bit for me regardless of whether I select the Win64 generator or not; it doesn't seem to generate the proper solution targets for Win64.

In the past when I've done full source builds of Unreal Engine, Epic's project generator has not only generated a solution for 64-bit, but had the 64-bit target default to selected we the solution is opened in VS. I dunno what's going on here but it doesn't generate a solution with 64-bit targets configured.

**Comment by BearishSun** [comment]
Which CMake and Windows version are you using? When you start CMake GUI (with a clean build folder), does it give you the option between `Visual Studio 15 2017 Win64` and `Visual Studio 15 2017`?

I can confirm proper 64-bit solution generation for VS2017 using CMake 3.9.0 on Windows 10 (in fact I don't recall the last time I generated a 32-bit one).

**Comment by DW01** [comment]
CMake 3.10.1 on Windows 10 64-bit.

It doesn't seem to give me any option but the default 32-bit generator through the GUI, as in there's no generator dropdown. This is certainly a strange one.

I've cleared out the Build folder, let's see if it changes anything.

**Comment by DW01** [comment]
Yep, that seems to have done it.

Weird that command-line generation spat out 32-bit build files, though...
