### ISSUE TITLE
[GLRenderAPI] ARB_geometry_shader4 check probably incorrect

### ISSUE THREAD

**Issue by w-flo** [BearishSun/BansheeEngine#157]
My hardware doesn't support the extension on Mesa, so ExampleGettingStarted throws an uncaught exception, but it does support geometry shaders. The ShadowDepthCube compilation apparently works fine after commenting out the extension check (I'm unsure if it's actually used anywhere). While the Khronos Wiki page https://www.khronos.org/opengl/wiki/Geometry_Shader indicates that this extension offers GS support, the same page says: 
> Note: While geometry shaders have had previous extensions like GL_EXT_geometry_shader4
> and GL_ARB_geometry_shader4, these extensions expose the API and GLSL functionality in
> very different ways from the core feature. This page describes only the core feature.

I've looked at the *_shader4 extension spec https://www.khronos.org/registry/OpenGL/extensions/ARB/ARB_geometry_shader4.txt and the GLSL generated by XSC for the GS that is used by ExampleGettingStarted (I think it's ShadowDepthCube.bsl), and it seems like XSC uses the OpenGL 3.2 core GS support:
>    In this extension, the input and output primitive types and maximum output
>    vertex count are specified prior to linking, using the
>    ProgramParameteriARB command.  However, OpenGL 3.2 requires that these
>    properties be specified using the "layout" modifier in geometry shader
>    source and provides no program paramter state.

If my observation is correct, I think it would be better to check for OpenGL version >= 3.2 instead of querying ARB_geometry_shader4 support.

GL instancing and multiple GS output streams are not in OpenGL Core 3.2, so if they are occasionally used by XSC, another check for ARB_gpu_shader5 and/or ARB_transform_feedback3 is needed.

**Comment by BearishSun** [comment]
That makes sense, I'll remove the checks as Banshee doesn't support anything earlier than OpenGL 4.1 anyway.

**Comment by BearishSun** [comment]
I've removed the check for ARB_geometry_shader4, 572ae23b942e8c1f298c230e7ed94c3613e56be8.

**Comment by w-flo** [comment]
Yes, this works now.
