### ISSUE TITLE
[FBX import] from Blender. Model is Ok, but animations are wrong

### ISSUE THREAD

**Issue by christianclavet** [BearishSun/BansheeEngine#163]
Hi, Found a FPS view model on the internet and tried to use it.

It was made in Blender, and I exported the animated model in FBX to import back in Banshee.

I see the model but there are issues in the animation. The FBX was exported as ASCII. For some reasons, the binary import did not have any animations at all. The ascii version seemed to import well as it found all the animations inside the file. But the deformations are wrong. Perhaps because I applied a scale to the model? It was too small.

Here is a screen showing how the hands deforms:
![capture](https://user-images.githubusercontent.com/13395943/35204233-c4b11db6-fefa-11e7-9b1a-9c41d431b81d.JPG)
Here is a zip file with the FBX and the source .blend:
[FPS Hands.zip](https://github.com/BearishSun/BansheeEngine/files/1650646/FPS.Hands.zip)

**Comment by BearishSun** [comment]
This is resolved with 04db697dce9d84897a9443e2a730acca7c58bd7d. Note that you will need to re-import any existing animations (even those that weren't affected by this issue), as there was an internal change to how the system works.
