### ISSUE TITLE
I cannot open the banshee in Windows 10

### ISSUE THREAD

**Issue by kodicak** [BearishSun/BansheeEngine#164]
I cannot open the banshee in Windows 10
https://imgur.com/lhR1QUZ

Fatal error occurred and the program has to terminate!Unhandled exception at 0x140724437195695. Access violation reading 0x40.Stack trace: BansheeEngine::D3D11InputLayoutManager::addNewInputLayout() - 0x140724437195695 File[bsd3d11inputlayoutmanager.cpp:120 (0)] Module[BansheeD3D11RenderAPI.dll]BansheeEngine::D3D11InputLayoutManager::retrieveInputLayout() - 0x140724437195217 File[bsd3d11inputlayoutmanager.cpp:72 (0)] Module[BansheeD3D11RenderAPI.dll]BansheeEngine::D3D11RenderAPI::applyInputLayout() - 0x140724437253080 File[bsd3d11renderapi.cpp:1145 (47)] Module[BansheeD3D11RenderAPI.dll]BansheeEngine::D3D11RenderAPI::drawIndexed() - 0x140724437246724 File[bsd3d11renderapi.cpp:639 (0)] Module[BansheeD3D11RenderAPI.dll]BansheeEngine::RendererUtility::draw() - 0x140724267102027 File[bsrendererutility.cpp:314 (0)] Module[BansheeEngine.dll]BansheeEngine::GUIManagerCore::render() - 0x140724267434477 File[bsguimanager.cpp:1814 (72)] Module[BansheeEngine.dll]BansheeEngine::RenderBeast::renderOverlay() - 0x140724418496171 File[bsrenderbeast.cpp:804 (0)] Module[RenderBeast.dll]BansheeEngine::RenderBeast::renderAllCore() - 0x140724418490103 File[bsrenderbeast.cpp:516 (0)] Module[RenderBeast.dll]BansheeEngine::CommandQueueBase::playbackWithNotify() - 0x140724269145329 File[bscommandqueue.cpp:127 (0)] Module[BansheeCore.dll]BansheeEngine::CommandQueueBase::playback() - 0x140724269145543 File[bscommandqueue.cpp:141 (0)] Module[BansheeCore.dll]BansheeEngine::CommandQueueBase::playbackWithNotify() - 0x140724269145329 File[bscommandqueue.cpp:127 (0)] Module[BansheeCore.dll]BansheeEngine::CoreThread::runCoreThread() - 0x140724268644699 File[bscorethread.cpp:124 (0)] Module[BansheeCore.dll]BansheeEngine::PooledThread::run() - 0x140724418902956 File[bsthreadpool.cpp:124 (0)] Module[BansheeUtility.dll]std::_LaunchPad >,std::default_delete > > > >::_Run() - 0x140724418908517 File[xthread:250 (0)] Module[BansheeUtility.dll]std::_Pad::_Call_func() - 0x140724418900889 File[xthread:210 (0)] Module[BansheeUtility.dll]0x140724869191813 Module[ucrtbase.dll]0x140724882120676 Module[KERNEL32.DLL]0x140724926672785 Module[ntdll.dll]
--

**Comment by BearishSun** [comment]
Hi, this appears to be a stack trace from an older version of Banshee. It's possible the issue has been resolved since. Please try compiling the latest from the master branch, and report the new log if the issue still happens.

**Comment by BearishSun** [comment]
Closing for now, feel free to re-open if you still experience the issue with a recent version.
