### ISSUE TITLE
Banshee executable search DATA folder in the source folder.

### ISSUE THREAD

**Issue by christianclavet** [BearishSun/BansheeEngine#165]
Hi, 

Having a problem with the last Windows version that refuse to launch when I updated the source folder.
Apparently Banshee seem to compile shaders and retrieving stuff from the DATA folder. But it get it where are the source of the repository.

Everytime I copy the copy the executables and the DATA in another folder. 

I you want to check:

Once you got a build, rename the DATA folder in the repo to OLDATA and try to launch the application.
Is there a way to have the splash screen appear before this?

**Comment by BearishSun** [comment]
Hi, I'm not entirely sure what you mean. Could you elaborate?

I think you are saying that Banshee attempts to load data files from the source directory even when you moved the executable & data files to another folder? And if you rename the data folder in the source directory, it will fail to launch?

If that's the case, I cannot reproduce the problem. I've built the editor and renamed the original data folder, everything still appears to work.

Also, I'm not sure what do you mean about the splash screen?

**Comment by christianclavet** [comment]
Hi! 

I remarked that the assets in the DATA folder (the one in the local Github repo), are modified when I use the editor. Each time I want to update the source, I have to cancel the modifications before updating. So logically I assume that the executable is doing something there when it should use a local path (like "../../data") when it use something like this "C:\users\clavetc\github\bansheeengine\data". Cmake could perhaps create this full path, when it need the relative path(from the executable location).

I've renamed the folder data in my github local repo and when I start the application it crash immediately. It doesnt crash if I don't change the name.

When I create a build, I copy the "bin" and "data" in another folder like "c:\project\banshee" and I put my stuff there (projects). So if I want to install banshee on my friend computer, I would be not be able to do it because the application will seek the data folder in MY profile that is not on this machine. 

Do you run the executable directly where they've been build? To reproduce this issue, create a folder somewhere else (like C:/test") and copy your executables folders (bin) and the data folder there. Once it's done, rename the folder in you github local repo, and try to launch the executable you copied. Here each time, it seek the local github repo and crash if I renamed the folder. (immediate crash, no wait)

For the splash screen, the problem is that Banshee is EXTREMELY slow to show something when we start it. I think it compile all the shaders at launch. If we had the splash screen before it start to compile, we would not think the application froze or crashed at startup. It take around 20-30 second to display something once I start the release application here. And 50-60 second in debug. When the splash screen appear, it close almost instantly to ask for the project to open. (0.5 sec approx). If you can, then later would be nice to have status on the this splascreen like "loading ressources, compiling shaders, etc).

Here is the graphic of the splashscreen:
![splashscreen](https://user-images.githubusercontent.com/13395943/35545963-b4d31160-053f-11e8-8ccb-0f9ab91b76c0.png)

**Comment by BearishSun** [comment]
Thanks, I understand now. When you copy the files to another folder you must ensure that the `Data` folder is in the same place as `BansheeEditorExec.exe`. If you do that, the editor will load the data files locally. In your case the editor cannot find the local data files, so it falls back on loading them from a location it knows they exist (the source folder). (For an example, you can download one of the older editor releases, and see the folder layout there)

Even when the editor is loading the assets from the source folder, it shouldn't be changing them, nor should it take that long to start up. I'll investigate those problems further.

I'm aware of the splash screen problem (I think you mentioned it earlier) and it will be resolved as well.

**Comment by christianclavet** [comment]
Thanks Marko! I'll move the data folder directly in the executable folder instead of having this:
(This was my "production" folder setup). I'll change it so the data folder is used correctly.
```
banshee -->
  bin 
  data
  project
  executable shortcuts
```
