### ISSUE TITLE
issues with ExampleLowLevelRendering using Vulkan

### ISSUE THREAD

**Issue by RallyTronics** [BearishSun/BansheeEngine#170]
While _ExampleGettingStared_ appears to work correctly, all I see is a blue window when I run _ExampleLowLevelRendering_.  In addition, the scaling seems off in the _ExamplePhysicallyBasedShading_ example compared to DirectX.

**Comment by BearishSun** [comment]
Vulkan issue in ExampleLowLevelRendering should now be resolved with 53975fac109f925c96a79f8b1c65b1bb0647eb8f.

I didn't manage to see a scaling difference between DirectX and Vulkan. Can you send a screenshot of what you mean? Although the camera positioning was off in both examples, which I adjusted a bit.

**Comment by RallyTronics** [comment]
Sounds like your probably got it, it was probably camera positioning.  I will confirm when I get home from work.

**Comment by RallyTronics** [comment]
Looking good!
