### ISSUE TITLE
[QUESTION] Data oriented? 

### ISSUE THREAD

**Issue by ShalokShalom** [BearishSun/BansheeEngine#173]
Is Banshee [data oriented?](https://www.danielsefton.com/2016/05/developing-a-data-oriented-game-engine-part-1/)

**Comment by BearishSun** [comment]
The frontend and high level systems are all very much object oriented. Internals of certain systems where performance matters (like the renderer) have their data organized in a data oriented, cache friendly manner. The approach yields the best of both worlds, with nice modular and encapsulated designed that's easy to follow, modify and maintain and fast, optimized internals in areas where a lot of processing takes place.

**Comment by ShalokShalom** [comment]
Very nice. 

Would you say functional programming does also combine these both worlds?

P.S: I would suggest to somehow name this evidence somewhere on the features list.

**Comment by BearishSun** [comment]
Aside from GPU code, I'm not really sure where would functional programming be a good fit in engine design.

**Comment by ShalokShalom** [comment]
Why?

**Comment by BearishSun** [comment]
I don't have a reason, I just can't think of any place I'd use it in any of the current engine systems that would result in design or performance benefit - doesn't necessarily mean its not a good fit somewhere.
