### ISSUE TITLE
[Build With Make] - error when compiling BsFrameAlloc.h

### ISSUE THREAD

**Issue by kamranrad1993** [BearishSun/BansheeEngine#175]
hi 
i`m using ubuntu 16.04 with cmake 3.11 and make 4.1and g++5.4.0
when i want to compile banshee3D with make fialed with this error : 

`
                  [  8%] Building CXX object BansheeCore/CMakeFiles/BansheeCore.dir/Profiling/BsProfilerCPU.cpp.o

                 In file included from /home/hello/Desktop/BansheeEngine-master/Source/BansheeCore/../BansheeUtility/Allocators/BsMemoryAllocator.h:442:0,

                 from /home/hello/Desktop/BansheeEngine-master/Source/BansheeCore/../BansheeUtility/Prerequisites/BsPrerequisitesUtil.h:262,

                 from /home/hello/Desktop/BansheeEngine-master/Source/BansheeCore/./BsCorePrerequisites.h:5,

                 from /home/hello/Desktop/BansheeEngine-master/Source/BansheeCore/./Profiling/BsProfilerCPU.h:5,

                 from /home/hello/Desktop/BansheeEngine-master/Source/BansheeCore/Profiling/BsProfilerCPU.cpp:3:

/home/hello/Desktop/BansheeEngine-master/Source/BansheeCore/../BansheeUtility/Allocators/BsFrameAlloc.h: In instantiation of ‘T* bs::FrameAlloc::construct(Args&& ...) [with T =
std::stack<bs::ProfilerCPU::ActiveBlock, std::deque<bs::ProfilerCPU::ActiveBlock,

 bs::StdFrameAlloc<bs::ProfilerCPU::ActiveBlock> > >; Args = 
{bs::StdFrameAlloc<bs::ProfilerCPU::ActiveBlock>}]’:
/home/hello/Desktop/BansheeEngine-master/Source/BansheeCore/Profiling/BsProfilerCPU.cpp:183:46:   required from here

/home/hello/Desktop/BansheeEngine-master/Source/BansheeCore/../BansheeUtility/Allocators/BsFrameAlloc.h:83:67: error: no matching function for call to ‘std::stack<bs::ProfilerCPU::ActiveBlock, std::deque<bs::ProfilerCPU::ActiveBlock, bs::StdFrameAlloc<bs::ProfilerCPU::ActiveBlock> > >::stack(bs::StdFrameAlloc<bs::ProfilerCPU::ActiveBlock>)’
    return new ((T*)alloc(sizeof(T))) T(std::forward<Args>(args)...);
                                                                   ^
In file included from /usr/include/c++/5/stack:61:0,
                 from /home/hello/Desktop/BansheeEngine-master/Source/BansheeCore/../BansheeUtility

/Allocators/BsStackAlloc.h:5,
                 from /home/hello/Desktop/BansheeEngine-master/Source/BansheeCore/../BansheeUtility

/Allocators/BsMemoryAllocator.h:440,
                 from /home/hello/Desktop/BansheeEngine-master/Source/BansheeCore/../BansheeUtility/Prerequisites/BsPrerequisitesUtil.h:262,
                 from /home/hello/Desktop/BansheeEngine-master/Source/BansheeCore/./BsCorePrerequisites.h:5,
                 from /home/hello/Desktop/BansheeEngine-master/Source/BansheeCore/./Profiling/BsProfilerCPU.h:5,
                 from /home/hello/Desktop/BansheeEngine-master/Source/BansheeCore/Profiling/BsProfilerCPU.cpp:3:
/usr/include/c++/5/bits/stl_stack.h:141:7: note: candidate: std::stack<_Tp, _Sequence>::stack(_Sequence&&) [with _Tp = bs::ProfilerCPU::ActiveBlock; _Sequence = std::deque<bs::ProfilerCPU::ActiveBlock, bs::StdFrameAlloc<bs::ProfilerCPU::ActiveBlock> >]
       stack(_Sequence&& __c = _Sequence())
       ^
/usr/include/c++/5/bits/stl_stack.h:141:7: note:   no known conversion for argument 1 from ‘bs::StdFrameAlloc<bs::ProfilerCPU::ActiveBlock>’ to ‘std::deque<bs::ProfilerCPU::ActiveBlock, bs::StdFrameAlloc<bs::ProfilerCPU::ActiveBlock> >&&’
/usr/include/c++/5/bits/stl_stack.h:137:7: note: candidate: std::stack<_Tp, _Sequence>::stack(const _Sequence&) [with _Tp = bs::ProfilerCPU::ActiveBlock; _Sequence = std::deque<bs::ProfilerCPU::ActiveBlock, bs::StdFrameAlloc<bs::ProfilerCPU::ActiveBlock> >]
       stack(const _Sequence& __c)
       ^
/usr/include/c++/5/bits/stl_stack.h:137:7: note:   no known conversion for argument 1 from ‘bs::StdFrameAlloc<bs::ProfilerCPU::ActiveBlock>’ to ‘const std::deque<bs::ProfilerCPU::ActiveBlock, bs::StdFrameAlloc<bs::ProfilerCPU::ActiveBlock> >&’
/usr/include/c++/5/bits/stl_stack.h:99:11: note: candidate: std::stack<bs::ProfilerCPU::ActiveBlock, std::deque<bs::ProfilerCPU::ActiveBlock, bs::StdFrameAlloc<bs::ProfilerCPU::ActiveBlock> > >::stack(const std::stack<bs::ProfilerCPU::ActiveBlock, std::deque<bs::ProfilerCPU::ActiveBlock, bs::StdFrameAlloc<bs::ProfilerCPU::ActiveBlock> > >&)
     class stack
           ^
/usr/include/c++/5/bits/stl_stack.h:99:11: note:   no known conversion for argument 1 from ‘bs::StdFrameAlloc<bs::ProfilerCPU::ActiveBlock>’ to ‘const std::stack<bs::ProfilerCPU::ActiveBlock, std::deque<bs::ProfilerCPU::ActiveBlock, bs::StdFrameAlloc<bs::ProfilerCPU::ActiveBlock> > >&’
/usr/include/c++/5/bits/stl_stack.h:99:11: note: candidate: std::stack<bs::ProfilerCPU::ActiveBlock, std::deque<bs::ProfilerCPU::ActiveBlock, bs::StdFrameAlloc<bs::ProfilerCPU::ActiveBlock> > >::stack(std::stack<bs::ProfilerCPU::ActiveBlock, std::deque<bs::ProfilerCPU::ActiveBlock, bs::StdFrameAlloc<bs::ProfilerCPU::ActiveBlock> > >&&)
/usr/include/c++/5/bits/stl_stack.h:99:11: note:   no known conversion for argument 1 from ‘bs::StdFrameAlloc<bs::ProfilerCPU::ActiveBlock>’ to ‘std::stack<bs::ProfilerCPU::ActiveBlock, std::deque<bs::ProfilerCPU::ActiveBlock, bs::StdFrameAlloc<bs::ProfilerCPU::ActiveBlock> > >&&’
BansheeCore/CMakeFiles/BansheeCore.dir/build.make:231: recipe for target 'BansheeCore/CMakeFiles/BansheeCore.dir/Profiling/BsProfilerCPU.cpp.o' failed
make[2]: *** [BansheeCore/CMakeFiles/BansheeCore.dir/Profiling/BsProfilerCPU.cpp.o] Error 1
CMakeFiles/Makefile2:172: recipe for target 'BansheeCore/CMakeFiles/BansheeCore.dir/all' failed
make[1]: *** [BansheeCore/CMakeFiles/BansheeCore.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
`

thanks ;)

**Comment by BearishSun** [comment]
Hi. This is due to an older standard library. You need to update your GCC/G++ to 7.0 or later.

**Comment by kamranrad1993** [comment]
thank so mush
its work :)

**Comment by kamranrad1993** [comment]
i update gcc and g++ 
but again give this error:

`[ 98%] Linking CXX executable /home/hello/Desktop/BansheeEngine-master/bin/x64/Release/ExampleGettingStarted
/home/hello/Desktop/BansheeEngine-master/bin/x64/Release/libBansheeEngine.so: undefined reference to `bs::HString::operator std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, bs::StdAlloc<wchar_t, bs::GenAlloc> > const&() const'
collect2: error: ld returned 1 exit status
Examples/ExampleGettingStarted/CMakeFiles/ExampleGettingStarted.dir/build.make:108: recipe for target '/home/hello/Desktop/BansheeEngine-master/bin/x64/Release/ExampleGettingStarted' failed
make[2]: *** [/home/hello/Desktop/BansheeEngine-master/bin/x64/Release/ExampleGettingStarted] Error 1
CMakeFiles/Makefile2:1018: recipe for target 'Examples/ExampleGettingStarted/CMakeFiles/ExampleGettingStarted.dir/all' failed
make[1]: *** [Examples/ExampleGettingStarted/CMakeFiles/ExampleGettingStarted.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by BearishSun** [comment]
Unsure what that's about. I'm using GCC 7.0.1 and Ubuntu 17.04 and it compiles fine. It could be some difference between GCC versions in case you are using a newer one.

**Comment by chaosink** [comment]
Same problem on Linux Mint 18.3 (base on Ubuntu 16.04) for GCC and Clang.
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9) 
clang version 5.0.0-3~16.04.1 (tags/RELEASE_500/final)

```
 error: no matching function for call to ‘std::stack<bs::ProfilerCPU::ActiveBlock, std::deque<bs::ProfilerCPU::ActiveBlock, bs::StdFrameAlloc<bs::ProfilerCPU::ActiveBlock> > >::stack(bs::StdFrameAlloc<bs::ProfilerCPU::ActiveBlock>)’
    return new ((T*)alloc(sizeof(T))) T(std::forward<Args>(args)...);
```

**Comment by BearishSun** [comment]
GCC 7 is required to compile Banshee.
