### ISSUE TITLE
Mouse wheel in editor very confusing to use

### ISSUE THREAD

**Issue by jonesmz** [BearishSun/BansheeEngine#188]
Pristine new project:

![image](https://user-images.githubusercontent.com/755783/37437506-9e7fb1d6-27bb-11e8-9af4-6fa4d3347f2d.png)

Rotate mouse wheel 1 "click"

![image](https://user-images.githubusercontent.com/755783/37437529-b4a49efe-27bb-11e8-89e7-5127b2677d23.png)

Where'd the grid go...?

Zoom back in, add a sphere

![image](https://user-images.githubusercontent.com/755783/37437573-e201834e-27bb-11e8-9ca7-359125dcf328.png)

Rotate mouse wheel 1 "click" towards myself:

![image](https://user-images.githubusercontent.com/755783/37437586-f8c9ff20-27bb-11e8-8fb5-29958e92a00e.png)

That seems rather... far away?

Is the scale for brand new editor projects set very very small?

Btw, slightly related, i noticed when making the pictures for this bug that if I click and hold the translation arrow for the sphere, and move my mouse forward, when it hits the top of the screen and teleports to the bottom of the screen and keeps going.

Of course, that's awesome that you have infinite mouse behavior, but having it jump to the bottom of the screen is a bit jarring. Is there a way to make it stay put, or go invisible when doing the object move operation, so that it doesn't jump around the screen?

**Comment by BearishSun** [comment]
The scroll wheel behavior probably needs tweaking.

The mouse behavior thing seems more of a personal preference, I like to see in which direction I'm moving the mouse. I'll consider changing it if others find it jarring as well.

**Comment by christianclavet** [comment]
Hi, Seen this. The zoom value is really high. Perhaps adding a way to change the value in the preference. For the "default" scene, it could be tweaked.

**Comment by jayrulez** [comment]
I also find this a bit jarring. I'd be happy if it was changed.

**Comment by XMatrixXiang** [comment]
I'd be happy too if it was changed.

**Comment by christianclavet** [comment]
Hi, Can this issue be closed now? I set the scroll speed to 0.1 with the new camera panel and work fine for me.
![image](https://user-images.githubusercontent.com/13395943/59968355-9f82c280-9506-11e9-8ecc-0507993d3b9b.png)

**Comment by BearishSun** [comment]
Sounds good, closing.
