### ISSUE TITLE
DX11 debug layer on windows 10

### ISSUE THREAD

**Issue by Mr1Penguin** [BearishSun/BansheeEngine#19]
Creating dx11 device with debug layer on windows 10 failed.

Found solution on [stackoverflow](http://stackoverflow.com/questions/32809169/use-d3d11-debug-layer-with-vs2013-on-windows-10), so maybe add this info here [here](https://github.com/BearishSun/BansheeEngine/blob/preview/Documentation/GitHub/compiling.md)?

**Comment by BearishSun** [comment]
Hi, this is noted in CompilingDependenciesManually.txt. I'll create a better doc for it a bit later.

**Comment by BearishSun** [comment]
Updated docs on master, https://github.com/BearishSun/BansheeEngine/blob/master/Documentation/GitHub/compiling.md.
