### ISSUE TITLE
Confusing language in codestyle document

### ISSUE THREAD

**Issue by jonesmz** [BearishSun/BansheeEngine#193]
https://github.com/BearishSun/BansheeEngine/blob/master/Documentation/Manuals/Native/codeStyle.md

> - If a class needs to communicate with another class within a sub-system, but the functionality isn't something a normal user is meant to use, provide "internal" methods. Those may be (depending on what is more convenient):
> - Private methods that are exposed to the other class using the friend syntax
> - Public methods that are prefixed with "_" (e.g. void _internalMethod();).

It would be clearer if the above two items had their itemization indented, or turned into a numeric enumeration.

**Comment by BearishSun** [comment]
These markdown docs are meant to be used by Doxygen, which generates the indentation properly, see here: http://docs.banshee3d.com/Native/code_style.html. GitHub doesn't interpret these documents properly (its much worse with other manuals).

Note the link above contains older documentation. You can generate latest by running Doxygen with `Documentation/Doxygen/Native.doxyconfig`

**Comment by jonesmz** [comment]
Ahh. Thanks for the explanation.
