### ISSUE TITLE
Documentation typo

### ISSUE THREAD

**Issue by jonesmz** [BearishSun/BansheeEngine#194]
http://docs.banshee3d.com/Native/animation_clip.html

> Skeletal - Each vertex on the mesh is assigned to a bone using and index and a weight - this is called a skin. Each bone is part of a hierarchy which is called a skeleton. The bones are then animated using animation clips, and as the bones move, so do the vertices (skin) attached to them.

assigned to a bone using **and** index and a weight

**Comment by BearishSun** [comment]
Thanks. Fixed. Note that I've just pushed a major refactor, and the whole engine core has been moved to https://github.com/GameFoundry/bsf (including the C++ documentation), while this repository is now only for the editor and its runtime.
