### ISSUE TITLE
Exposing Emissive materials in editor

### ISSUE THREAD

**Issue by iontom** [BearishSun/BansheeEngine#195]
I'm sure you have plans for this, as well as PBR interfaces and visual material scripting, but a simple emission map would help with early prototyping.

**Comment by BearishSun** [comment]
I'll see if I can fit in it for v1.0 release. It's hardly a complex feature but I've added too many features for v1.0 as is, so I'm trying to refrain from adding more. But it should come soon regardless. Visual material scripting is a more long-term goal however.

**Comment by iontom** [comment]
Awesome! Thanks!

**Comment by BearishSun** [comment]
Emissive materials were added a while back, closing.
