### ISSUE TITLE
Application icon..

### ISSUE THREAD

**Issue by christianclavet** [BearishSun/BansheeEngine#205]
Just decided the take the splashscreen PNG and create a windows icon for it (.ico).
[splashscreen_Sti_icon.zip](https://github.com/BearishSun/BansheeEngine/files/1976005/splashscreen_Sti_icon.zip)

Is there an icon picture on the executable on the Mac and Linux version?

**Comment by BearishSun** [comment]
Thanks. I do already have a version of that logo without the text (my profile pic here on GitHub), which I was going to use as an icon.

**Comment by christianclavet** [comment]
Ok. Used it and created another icon:
[main_icon.zip](https://github.com/BearishSun/BansheeEngine/files/2019847/main_icon.zip)
I was able to create an icon for the Windows application by creating the .rc file in MSVC. But this would need to work from a CMAKE config... Searched and not found anything yet.
