### ISSUE TITLE
Lost  “this” in the SpringGUI Constructor (LimitInspectors.cs)

### ISSUE THREAD

**Issue by XMatrixXiang** [BearishSun/BansheeEngine#206]
public SpringGUI(Spring spring, GUILayout layout)
        {
            this.spring = spring;
         
            // should be this.spring.stiffness = x
            stiffnessField.OnChanged += x => { spring.stiffness = x; MarkAsModified(); };
            stiffnessField.OnFocusLost += ConfirmModify;
            stiffnessField.OnConfirmed += ConfirmModify;

            // should be this.spring.damping = x
            dampingField.OnChanged += x => { spring.damping = x; MarkAsModified(); };
            dampingField.OnFocusLost += ConfirmModify;
            dampingField.OnConfirmed += ConfirmModify;

            layout.AddElement(stiffnessField);
            layout.AddElement(dampingField);
        }

**Comment by BearishSun** [comment]
Thanks for the report. Resolved with 11780e30cc3a6d0d68270a7db5894108b91b85f6.
