### ISSUE TITLE
Question using GITHUB DESKTOP with Banshee 3D

### ISSUE THREAD

**Issue by christianclavet** [BearishSun/BansheeEngine#207]
Hi!

Since the beginning, when updating Banshee , Github desktop cannot do it because of the changes (Since I'm building it after that).

I try to revert all the changes, before the separation of BSF, it was ok and I was able  to revert everything before doing a new update. And then create new builds.

Now, each time, it fail to revert the BSF source within Banshee 3D, and I have to delete the whole repo and restart as new each time I update.

Is there a better way to update the source using Github desktop?

**Comment by BearishSun** [comment]
I haven't used Github Desktop, but bsf acts as a separate repository within Banshee. So perhaps try opening `Source/bsf` in Github Desktop and doing revert on it directly?

If that doesn't work I suggest trying Tortoise Git instead Github Desktop. The step above should definitely work using that.

**Comment by christianclavet** [comment]
Thanks. I've installed it and tried to update. They have an overwrite option, so I will use this one instead.
