### ISSUE TITLE
Banshee Editor (OPENGL): BC texture compression output is black

### ISSUE THREAD

**Issue by christianclavet** [BearishSun/BansheeEngine#208]
Hi, I'm trying to compress the textures using the block compression schemes (BC1-BC7)
I have a done a Banshee build on openGL. 

Are theses compressor only work for the DX version? What to use for GL and Vulkan?

**Comment by BearishSun** [comment]
They should work across all render backends equally. I'll investigate and get back to you.

**Comment by BearishSun** [comment]
The issue should now be resolved.

**Comment by christianclavet** [comment]
Hi! Thanks Marko! With the latest changes, it work now!
