### ISSUE TITLE
Banshee use absolute path instead of relative path...

### ISSUE THREAD

**Issue by christianclavet** [BearishSun/BansheeEngine#210]
Hi, Banshee is using absolute paths when retrieving the files asssets.

I copied the build folder and given it a new name, and the application crashed as it was searching for assets that where not there:

Here is the path before I renamed:
C:\Users\Public\Projets\BS\BansheeEngine

After I copied it to another location and given it a new name:
C:\Users\Public\Projets\BS\Banshee3D

Yet, the application try to load the asset from the absolute path not relative to the executable...

Here is the output of the crash:

Type | Description
-- | --
Warning | Attempting to open a file that doesn't exist: C:\Users\Public\Projets\BS\BansheeEngine\Data\SplashScreen.png.assetin class std::shared_ptr __cdecl bs::FileSystem::openFile(const class bs::Path &,bool) [c:\users\public\projets\bs\bansheeengine\source\bsf\source\foundation\bsfutility\private\win32\bswin32filesystem.cpp:280]
Error | A fatal error occurred and the program has to terminate!Unhandled exception at 0x140720723703774. Access violation reading 0x0.Stack trace: 0x140720723703774 Module[bsf.dll]0x140720883122575 Module[EditorCore.dll]0x140720882721191 Module[EditorCore.dll]0x140720724039272 Module[bsf.dll]0x140720724086650 Module[bsf.dll]0x140720723564313 Module[bsf.dll]0x140720723562135 Module[bsf.dll]0x140721581841413 Module[ucrtbase.dll]0x140721603420132 Module[KERNEL32.DLL]0x140721635127393 Module[ntdll.dll]

**Comment by christianclavet** [comment]
Humm... Ok. Found the issue:
Need to remove the configuration that have the absolute path! Once removed, Banshee will redo a configuration file and not crash. 
The file is located there and have a full path for the files:
_BansheeEngine/Data/Settings.asset_

**Comment by christianclavet** [comment]
Humm.. You mean, it cannot be copied, and need to be rebuild each time? How will you make an installer? 

From what I know, it's possible to make it relative to the executable, so it this executable seek stuff, it should start from his own path, and seek in his path and seach assets in it subfolders. I was able to do this for IRB with Irrlicht as Irrlicht had functions to convert an absolute path to a relative path based on the location of the executable. 

In CMAKE it's working almost the same way:
[https://stackoverflow.com/questions/26787628/how-do-i-specify-relative-paths-in-cmake](https://stackoverflow.com/questions/26787628/how-do-i-specify-relative-paths-in-cmake)
As:
> You do this by specifying the path relative to ${CMAKE_CURRENT_SOURCE_DIR}, which is the directory containing the current CMakeLists.txt file.

**Comment by BearishSun** [comment]
When packaged for release Banshee uses relative paths to find the data files.
If you just compiled it manually it will use the hardcoded path to the data assets in the source folder.

**Comment by christianclavet** [comment]
Ok. It worked for Banshee, and now it seeking buildin assets files for BSF. So it's defined, only that you had 2 methods to load the assets. Thanks, this can be closed.

**Comment by BearishSun** [comment]
I have, it appears to be working correctly to the few people I'm distributing it to. You are correct in copying the 2 data folders, but you also need to copy `bin/Mono` and `bin/Assemblies` to be relative to the executable.

You can also run `Scripts/package_editor,py` and it will output the files in Builds/Banshee3D. The script expects you to have compiled everything using `OptimizedDebug` configuration.
