### ISSUE TITLE
Hovering over menu item with submenu causes parent menu to close.

### ISSUE THREAD

**Issue by jayrulez** [BearishSun/BansheeEngine#211]
On the latest revision of BS3D, click the components menu on the then hover over physics or audio menu items causes the component menu to close.

**Comment by jayrulez** [comment]
It seems hovering over the submenu causes focus lost event to be triggered.

**Comment by jayrulez** [comment]
Context menus have the same problem.

**Comment by BearishSun** [comment]
Thanks for the report. I believe the issue should be resolved with e849ad6815804409f4a31f55c11c48c06a88dddd.

**Comment by jayrulez** [comment]
Yes it does.
