### ISSUE TITLE
SPIR-V module not valid: MemoryBarrier.

### ISSUE THREAD

**Issue by kushinn** [BearishSun/BansheeEngine#219]
# Banshee Engine Log
Banshee version: 1.0
OS version: Windows 10 64-bit
CPU vendor: GenuineIntel
CPU name: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
CPU clock speed: 4200Mhz
CPU core count: 8
GPU: GeForce GTX 1080

void VulkanGpuProgram::initialize()
{
    VkResult result = vkCreateShaderModule(vkDevice, &moduleCI, gVulkanAllocator, &shaderModule); // **crash !!!!!!!!!**
}
	
# Log entries
Type | Description
-- | --
Error | A fatal error occurred and the program has to terminate!- Error: RenderingAPIException- Description: ERROR: [SC] Code 5: Object: 0x0 \| SPIR-V module not valid: MemoryBarrier: Vulkan specification requires Memory Semantics to have one of the following bits set: Acquire, Release, AcquireRelease or SequentiallyConsistent- In function: unsigned int __cdecl bs::ct::debugMsgCallback(unsigned int,enum VkDebugReportObjectTypeEXT,unsigned __int64,unsigned __int64,int,const char *,const char *,void *)- In file: f:\projects\engines\bansheeengine\source\bsf\source\plugins\bsfvulkanrenderapi\bsvulkanrenderapi.cpp:75Stack trace: bs::CrashHandler::reportCrash() - 0x140731790989302 File[bswin32crashhandler.cpp:468 (0)] Module[bsf.dll]bs::ct::debugMsgCallback() - 0x140731999675813 File[bsvulkanrenderapi.cpp:75 (156)] Module[bsfVulkanRenderAPI.dll]debug_log_msg() - 0x140732242441669 File[vk_layer_logging.h:320 (85)] Module[VkLayer_core_validation.dll]log_msg() - 0x140732242452596 File[vk_layer_logging.h:831 (0)] Module[VkLayer_core_validation.dll]PreCallValidateCreateShaderModule() - 0x140732242422691 File[shader_validation.cpp:1579 (105)] Module[VkLayer_core_validation.dll]core_validation::CreateShaderModule() - 0x140732241618990 File[core_validation.cpp:8695 (16)] Module[VkLayer_core_validation.dll]object_tracker::CreateShaderModule() - 0x140732547430296 File[object_tracker.cpp:1058 (33)] Module[VkLayer_object_tracker.dll]parameter_validation::vkCreateShaderModule() - 0x140732540631572 File[parameter_validation.cpp:2746 (20)] Module[VkLayer_parameter_validation.dll]threading::CreateShaderModule() - 0x140732546239899 File[thread_check.h:1157 (20)] Module[VkLayer_threading.dll]bs::ct::VulkanGpuProgram::initialize() - 0x140731999610062 File[bsvulkangpuprogram.cpp:92 (33)] Module[bsfVulkanRenderAPI.dll]std::_Invoker_pmf_pointer::_Call() - 0x140731791853972 File[type_traits:16707566 (68)] Module[bsf.dll]std::invoke() - 0x140731791863232 File[type_traits:16707566 (96)] Module[bsf.dll]std::_Invoker_ret::_Call() - 0x140731791852992 File[type_traits:15732480 (0)] Module[bsf.dll]std::_Call_binder,std::tuple<> >() - 0x140731791854727 File[functional:1078 (0)] Module[bsf.dll]std::_Binder::operator()<>() - 0x140731791851768 File[functional:1133 (136)] Module[bsf.dll]std::_Invoker_functor::_Call & __ptr64>() - 0x140731791853774 File[type_traits:16707566 (62)] Module[bsf.dll]std::invoke & __ptr64>() - 0x140731791863678 File[type_traits:16707566 (62)] Module[bsf.dll]std::_Invoker_ret::_Call & __ptr64>() - 0x140731791853870 File[type_traits:15732480 (0)] Module[bsf.dll]std::_Func_impl_no_alloc,void>::_Do_call() - 0x140731791875069 File[functional:15732480 (0)] Module[bsf.dll]std::_Func_class::operator()() - 0x140731788639200 File[functional:15732480 (0)] Module[bsf.dll]bs::CoreObject::executeGpuCommand() - 0x140731791878203 File[bscoreobject.cpp:149 (0)] Module[bsf.dll]std::_Invoker_functor::_Call const & __ptr64,std::function),std::shared_ptr & __ptr64,std::function & __ptr64>() - 0x140731791852838 File[type_traits:16707566 (150)] Module[bsf.dll]std::invoke const & __ptr64,std::function),std::shared_ptr & __ptr64,std::function & __ptr64>() - 0x140731791863090 File[type_traits:16707566 (130)] Module[bsf.dll]std::_Invoker_ret::_Call const & __ptr64,std::function),std::shared_ptr & __ptr64,std::function & __ptr64>() - 0x140731791852642 File[type_traits:15732480 (0)] Module[bsf.dll]std::_Call_binder const & __ptr64,std::function),std::tuple,std::function >,std::tuple<> >() - 0x140731791854537 File[functional:1078 (0)] Module[bsf.dll]std::_Binder const & __ptr64,std::function),std::shared_ptr const & __ptr64,std::function & __ptr64>::operator()<>() - 0x140731791851576 File[functional:1133 (136)] Module[bsf.dll]std::_Invoker_functor::_Call const & __ptr64,std::function),std::shared_ptr const & __ptr64,std::function & __ptr64> & __ptr64>() - 0x140731791853582 File[type_traits:16707566 (62)] Module[bsf.dll]std::invoke const & __ptr64,std::function),std::shared_ptr const & __ptr64,std::function & __ptr64> & __ptr64>() - 0x140731791863582 File[type_traits:16707566 (62)] Module[bsf.dll]std::_Invoker_ret::_Call const & __ptr64,std::function),std::shared_ptr const & __ptr64,std::function & __ptr64> & __ptr64>() - 0x140731791853678 File[type_traits:15732480 (0)] Module[bsf.dll]std::_Func_impl_no_alloc const & __ptr64,std::function),std::shared_ptr const & __ptr64,std::function & __ptr64>,void>::_Do_call() - 0x140731791874973 File[functional:15732480 (0)] Module[bsf.dll]std::_Func_class::operator()() - 0x140731788639200 File[functional:15732480 (0)] Module[bsf.dll]bs::CommandQueueBase::playbackWithNotify() - 0x140731791838212 File[bscommandqueue.cpp:127 (0)] Module[bsf.dll]bs::CoreThread::runCoreThread() - 0x140731792248937 File[bscorethread.cpp:118 (0)] Module[bsf.dll]std::_Invoker_pmf_pointer::_Call() - 0x140731792141172 File[type_traits:16707566 (68)] Module[bsf.dll]std::invoke() - 0x140731792164896 File[type_traits:16707566 (96)] Module[bsf.dll]std::_Invoker_ret::_Call() - 0x140731792140432 File[type_traits:15732480 (0)] Module[bsf.dll]std::_Call_binder,std::tuple<> >() - 0x140731792141591 File[functional:1078 (0)] Module[bsf.dll]std::_Binder::operator()<>() - 0x140731792138696 File[functional:1133 (136)] Module[bsf.dll]std::_Invoker_functor::_Call & __ptr64>() - 0x140731792140830 File[type_traits:16707566 (62)] Module[bsf.dll]std::invoke & __ptr64>() - 0x140731792165150 File[type_traits:16707566 (62)] Module[bsf.dll]std::_Invoker_ret::_Call & __ptr64>() - 0x140731792140926 File[type_traits:15732480 (0)] Module[bsf.dll]std::_Func_impl_no_alloc,void>::_Do_call() - 0x140731792213757 File[functional:15732480 (0)] Module[bsf.dll]std::_Func_class::operator()() - 0x140731788639200 File[functional:15732480 (0)] Module[bsf.dll]bs::PooledThread::run() - 0x140731789081623 File[bsthreadpool.cpp:113 (0)] Module[bsf.dll]std::_Invoker_pmf_pointer::_Call() - 0x140731789047748 File[type_traits:16707566 (68)] Module[bsf.dll]std::invoke() - 0x140731789058992 File[type_traits:16707566 (96)] Module[bsf.dll]std::_Invoker_ret::_Call() - 0x140731789047632 File[type_traits:15732480 (0)] Module[bsf.dll]std::_Call_binder,std::tuple<> >() - 0x140731789048007 File[functional:1078 (0)] Module[bsf.dll]std::_Binder::operator()<>() - 0x140731789047480 File[functional:1133 (136)] Module[bsf.dll]std::_Invoker_functor::_Call >() - 0x140731789047854 File[type_traits:16707566 (62)] Module[bsf.dll]std::invoke >() - 0x140731789059102 File[type_traits:16707566 (62)] Module[bsf.dll]std::_LaunchPad >,std::default_delete > > > >::_Execute<0>() - 0x140731789050234 File[xthread:241 (0)] Module[bsf.dll]std::_LaunchPad >,std::default_delete > > > >::_Run() - 0x140731789071741 File[xthread:249 (0)] Module[bsf.dll]std::_LaunchPad >,std::default_delete > > > >::_Go() - 0x140731789069302 File[xthread:233 (0)] Module[bsf.dll]std::_Pad::_Call_func() - 0x140731789066941 File[xthread:211 (0)] Module[bsf.dll]0x140732553892328 Module[ucrtbased.dll]0x140732553891329 Module[ucrtbased.dll]0x140732937089076 Module[KERNEL32.DLL]0x140732979549521 Module[ntdll.dll]

**Comment by BearishSun** [comment]
Thanks for the report. Which version of the Vulkan SDK are you using?

**Comment by kushinn** [comment]
[ VulkanSDK-1.1.73.0](https://vulkan.lunarg.com/sdk/home)

**Comment by kushinn** [comment]
It seems to be related to "GroupMemoryBarrierWithGroupSync" in some bsl.

**Comment by BearishSun** [comment]
Should be resolved on latest master. glslang was generating invalid SPIR-V which was failing some checks on more recent Vulkan SDK.
