### ISSUE TITLE
Maybe the 'SBansheeEditor\CMakeSources.cmake' has not pushed yet?

### ISSUE THREAD

**Issue by kushinn** [BearishSun/BansheeEngine#222]
BansheeEngine\Source\Scripting\SBansheeEditor\CMakeSources.cmake

After add the code to BansheeEngine\Source\Scripting\SBansheeEditor\CMakeSources.cmake

set(BS_GENERATED_EDITOR_H_FILES
	"Generated/BsScriptProjectResourceIcons.generated.h"
)
set(BS_GENERATED_EDITOR_CPP_FILES
	"Generated/BsScriptProjectResourceIcons.generated.cpp"
)

**Comment by BearishSun** [comment]
Those files should have been automatically registered. The issue has be resolved on latest master, make sure to re-run cmake after you pull.
