### ISSUE TITLE
BS_ASSERT(gResources().getUUIDFromFilePath(entry, uuid));

### ISSUE THREAD

**Issue by XMatrixXiang** [BearishSun/BansheeEngine#223]
this line code in the BansheeEngine/Source/Scripting/SBansheeEditor/Wrappers/BsScriptBuildManager.cpp(307 line) will not be executed in release model

**Comment by BearishSun** [comment]
Indeed, thanks for the report. Fixed with a16247f1b05603dce56897af1201a19cd2028455.
