### ISSUE TITLE
Physics Material missing

### ISSUE THREAD

**Issue by XMatrixXiang** [BearishSun/BansheeEngine#224]
My English is poor, but I will try to describe the problem。

1.  crate  a physics material 
2. drage this physics material to a collider compoent
3. save the scene 
4. close the editor 
5. open the editor 
6. click che scene object(with the collider compoent) in the  hierarchy panel 
but  the  material of the collider compoent displays  'None' in the inspector pannel
7. when i click the physics material in the library pannel , the material of the collider compoent  displayed correctly in the inspector pannel。

**Comment by BearishSun** [comment]
Thanks for the report, I'm able to reproduce the issue.

**Comment by BearishSun** [comment]
This should be resolved on latest. You will need to re-save your scene to see the changes.
