### ISSUE TITLE
the editor crashed,when i try to save the scene.

### ISSUE THREAD

**Issue by XMatrixXiang** [BearishSun/BansheeEngine#227]
I have compiled the latest code and create a simple scene(a Box node),
when i try to save the scene the editor crashed.
heere is the crashReports:

Error |

 No sync data is available. Cannot block until AsyncOp is complete.in void __cdecl bs::AsyncOp::blockUntilComplete(void) const [e:\study\editor\trunk\source\bsf\source\foundation\bsfutility\threading\bsasyncop.cpp:34]

Error | 
A fatal error occurred and the program has to terminate!Unhandled exception at 0x140709916345936. Access violation reading 0x16.Stack trace: std::vector >::vector >() - 0x140709916345936 File[vector:772 (0)] Module[EditorCore.dll]bs::ProjectLibrary::_finishQueuedImports() - 0x140709916293282 File[bsprojectlibrary.cpp:516 (0)] Module[EditorCore.dll]bs::ScriptProjectLibrary::internal_Refresh() - 0x140709861963388 File[bsscriptprojectlibrary.cpp:79 (0)] Module[SBansheeEditor.dll]0x22697283359390x8860190573280x8860190559040x8860190557760x8860190573280x10x2269763791536

**Comment by BearishSun** [comment]
Thanks for the report. I believe I know what the issue is but I'm in the process of refactoring that system anyway, so the issue should be resolved when that's done (likely end of this week).

**Comment by BearishSun** [comment]
This should be resolved with 336a12cb2f0fdc6cdd6924f95a0210eb17184f83.

**Comment by XMatrixXiang** [comment]
Thanks， Checked and it's good ！
