### ISSUE TITLE
function Gizmos.DrawText not working in c# script

### ISSUE THREAD

**Issue by XMatrixXiang** [BearishSun/BansheeEngine#228]
function Gizmos.DrawText not working in C # script

**Comment by XMatrixXiang** [comment]
I did a simple test.
I added two lines of  at the end of the Collidergizmos.cs/drawboxcollider function 
like this:
 Vector3 offset = new Vector3(5.0f, 5.0f, 5.0f);
 Gizmos.DrawText(collider.Center * scale + offset, "BoxCollider");
No matter how I modify the value of offset ,the text always appeared at the center point of the Box node 
like this:
![5](https://user-images.githubusercontent.com/13548583/41508705-6fc4515c-727b-11e8-81aa-683dbbc207ab.png)

**Comment by christianclavet** [comment]
Could be a parenthesis issue. Have you tried this?:

> Gizmos.DrawText((collider.Center * scale) + offset, "BoxCollider);

**Comment by BearishSun** [comment]
This was an actual issue with the gizmo rendering code, local offset simply wasn't being applied and it was only accounting for the transform matrix. Should be resolved on latest.

**Comment by XMatrixXiang** [comment]
Thanks， Checked and it's good ！
![7](https://user-images.githubusercontent.com/13548583/41515697-21748ed2-72e3-11e8-9a2c-5f21ea07bfc4.png)

**Comment by BearishSun** [comment]
Thanks for the report. The issue didn't reproduce in the same way for me (but it was definitely also broken), and I've produced a fix with the latest version. I believe it should now be resolved but since the issue didn't manifest in the same way there's potentially a separate issue.

**Comment by XMatrixXiang** [comment]
perfect！ Thanks for the quick fix.
