### ISSUE TITLE
CMAKE errors, Missing variables.., Build missing a shader (gizmo)

### ISSUE THREAD

**Issue by christianclavet** [BearishSun/BansheeEngine#229]
Hi, I tried to make a new build this weekend (june 16, 2018)
Got this coming from CMAKE:

> CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
> Missing variable is:
> CMAKE_CXX_FLAGS_OPTIMIZEDDEBUG
> CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
> Missing variable is:
> CMAKE_SHARED_LINKER_FLAGS_OPTIMIZEDDEBUG

I was able to make a release build without errors, and run it.
Then see that it is missing a .bsl shader (but still running):
![missing](https://user-images.githubusercontent.com/13395943/41501637-4e028468-7176-11e8-8915-2899760add56.JPG)

**Comment by BearishSun** [comment]
Thanks for the report. I've just submitted a fix that should resolve the missing shader problem.

To fix CMake errors you'll need to delete your build folder and regenerate it through CMake. Some build properties changed and CMake doesn't seem to be able to handle the change gracefully on existing builds.

**Comment by BearishSun** [comment]
Good to hear!

Those new build options haven't been tested with Banshee yet and are intended primarily for the framework at the moment. I'll update the docs when they're properly tested.
