### ISSUE TITLE
BansheeEngine (Discussion)

### ISSUE THREAD

**Issue by ret80** [BearishSun/BansheeEngine#23]
After a cursory acquaintance with the engine the impression that somewhere in all this is seen :)
I would like to know what your engine will be favorable differ from the Unity 3D?
What are the goals you are pursuing? Maybe you simply want to increase their skills in the development of engines? Or do you have a look at how the engine should look like?

**Comment by BearishSun** [comment]
The main benefits of Banshee are that it is open source and free, and its potential to grow. It allows you to fix bugs and add features with no limitations. It offers a more modern, clean and better designed code base that make it easier for the community to extend with new functionality. It can also be used both as a low level library and a high level runtime allowing it to be more easily used for new technologies. 

Once finished Banshee aims to provide a more stable engine, with better performance, larger focus on high fidelity PC/Console graphics and hopefully a lot of community enhancements that make its systems and tools better.

However it is not something that should be compared to Unity in its current state.

**Comment by ret80** [comment]
All this sounds great! :)
I got acquainted with a list of improvements. I do not quite agree with your priorities. Any visual things you are going to receive greater priority than the tools. You may want to reconsider that. Since the engine without the Vulkan and DX12 but with good opportunities for the rapid creation of games will attract more people to the community than the "Framework" from Vulkan and DX12. Not so much anymore which does not motivate the developer to use your product as a ready-made designs on it issued by the store. Way possible support for what may be a mobile platform is also to increase the priority of development.
I hope that you will succeed.
