### ISSUE TITLE
when i created a bsl file ,log window showed this error message!

### ISSUE THREAD

**Issue by XMatrixXiang** [BearishSun/BansheeEngine#230]
when i created a bsl file ,log window showed this error message!
![6](https://user-images.githubusercontent.com/13548583/41508853-ca12f364-727d-11e8-89aa-f0297c80806a.png)

**Comment by christianclavet** [comment]
Hi, have you enabled the option to create BSL shader when you've done your build? This is not enabled by default.

**Comment by BearishSun** [comment]
Thanks for the report. The default shader resource simply had obsolete BSL syntax. I've updated it and the issue should be resolved with 72471e8f1a426ae68580a6c6fb9435cb38748e99.

As a sidenote, `BUILD_BSL` CMake property is only required if you plan on changing the BSL syntax. Pretty much all users can leave that off.

**Comment by XMatrixXiang** [comment]
Thanks， Checked and it's good ！
