### ISSUE TITLE
the issue about the Shader resource

### ISSUE THREAD

**Issue by XMatrixXiang** [BearishSun/BansheeEngine#231]
1. create a bsl shader file
2. create a meterial  file
3. Apply the shader file to the Materia
4. Apply the Materia file to the Renderable compoent
5. The shder works fine.
6. Close the editor
7. Open the editor
Shader failure
Modify the BSL file again(For example: Add a few spaces), and then save it. Shader's working again.

**Comment by BearishSun** [comment]
Thanks for the report. This should now be resolved on the latest master.
