### ISSUE TITLE
[EDITOR] Error - Assertation failed

### ISSUE THREAD

**Issue by 690fps** [BearishSun/BansheeEngine#234]
I downloaded Editor binaries v0.4.0 (Windows x64)
I often get an error "Assertation failed" on any kind of actions
- moving window "project manager" after program start
- opening recent project
- moving in 3d area
- sometimes even if i do nothing after launching program

Tested on 3 systems:
- Win 7 sp1 - i3 3240
- Win 7 sp1 - i3 3240 + 1050 ti
- Win 7 sp1 - i3 3240 + AMD HD6570

VS2015 is installed
[Crash reports and system info.zip](https://github.com/BearishSun/BansheeEngine/files/2194681/Crash.reports.and.system.info.zip)

![13-07-2018 173724](https://user-images.githubusercontent.com/38181025/42721289-9a6d76e4-8762-11e8-90ee-1c097b81070f.png)
![13-07-2018 195233](https://user-images.githubusercontent.com/38181025/42721338-509ed30e-8763-11e8-9633-c39247958e08.png)
![13-07-2018 174603](https://user-images.githubusercontent.com/38181025/42721340-59f0c0e8-8763-11e8-9ce8-964592cba47b.png)

**Comment by BearishSun** [comment]
Hi. This is a known issue and it was resolved on newer versions. v0.4.0 release is very old and it is suggested your either build a new version from source and if unable, wait for the next binary release.
