### ISSUE TITLE
[EDITOR] Memory leakage on rotating perspective

### ISSUE THREAD

**Issue by 690fps** [BearishSun/BansheeEngine#236]
I downloaded Editor binaries v0.4.0 (Windows x64)
Editor uses too much memory on rotating perspective. Program crashes when system run out memory.
To reproduce open new project and rotate perspective many times.
Crash reports and system info:
[Memory leakage on rotating perspective.zip](https://github.com/BearishSun/BansheeEngine/files/2194709/Memory.leakage.on.rotating.perspective.zip)

![14-07-2018 130557](https://user-images.githubusercontent.com/38181025/42721587-7eda023a-8767-11e8-871a-56a93eeefa37.png)
![13-07-2018 225618](https://user-images.githubusercontent.com/38181025/42721602-c2b21cea-8767-11e8-9a90-ed932767177f.png)

**Comment by BearishSun** [comment]
Hi. This is a known issue and it was resolved on newer versions. v0.4.0 release is very old and it is suggested your either build a new version from source and if unable, wait for the next binary release.
