### ISSUE TITLE
Feature Request: BSP Meshes

### ISSUE THREAD

**Issue by t-boom** [BearishSun/BansheeEngine#24]
It would be awesome if there was support for some sort of BSP mesh for rapid prototyping level design. I find them much nicer to work with than primitives.

**Comment by BearishSun** [comment]
I agree this is a useful feature. I'll add it to the roadmap but have no timeframe when will it be implemented.

**Comment by t-boom** [comment]
Understandable. Many other features are much higher priority.

**Comment by BearishSun** [comment]
I'll close this since it might be a bit before we get around to it, but the feature has been added to the roadmap.
