### ISSUE TITLE
Editor hangs where scene is played/paused/frame stepped.

### ISSUE THREAD

**Issue by jayrulez** [BearishSun/BansheeEngine#242]
1. If the scene is not running and I hit pause then the editor hangs.

2. If I hit the play button twice then the editor hangs.

3. If the scene is not running and I hit the framestep button then the editor hangs.

[BsTest2.zip](https://github.com/BearishSun/BansheeEngine/files/2463120/BsTest2.zip)
 
This attached project causes the editor to crash on opening the project.

**Comment by BearishSun** [comment]
Thanks. I won't be able to check this out immediately, but I'll hopefully get to it by the end of the week.

**Comment by BearishSun** [comment]
This should be resolved on latest.
