### ISSUE TITLE
Undo operation reverts too many actions.

### ISSUE THREAD

**Issue by jayrulez** [BearishSun/BansheeEngine#246]
I added a quad to the scene.

I scaled the quad to 4x1x4.

I then moved the quad on the Y axis by accident.

I attempted to revert the move by using crtl+z.

I expected just the move to be reverted.

However, the scaling was also reverted making the quad the default size.

**Comment by jayrulez** [comment]
Additionally, when I try to revert the revert by using "redo", nothing happens.

**Comment by christianclavet** [comment]
Hi. I tried it again. The undo system seem to be broken at the moment. I've done a scale and a move on a node and got wrong results.

**Comment by christianclavet** [comment]
Hi, tried again today (june 24), and got the move reverted and the quad size was still maintained correctly. I think the issue is fixed now.

**Comment by jayrulez** [comment]
Sure. The undo-redo system was overhauled and works great now.
