### ISSUE TITLE
On the use of wide strings as paths

### ISSUE THREAD

**Issue by almightykiwi** [BearishSun/BansheeEngine#25]
In a couple of places, a wstring is passed as an argument to std::fstream, like so:
```
void f(const Path& path)
{
      std::fstream stream;
      stream.open(path.toWString().c_str());
      [...]
}
```
This doesn't work on Linux, where paths are strings of `char`, not `wchar_t`. Hence my question: is it possible / a good idea to use non-wide strings for paths on Windows ? Or should we rather use `#ifdef` to discriminate between Windows and others?

**Comment by BearishSun** [comment]
I think the right solution is to use Path::toString instead of using wide strings. However Path::toString itself should be modified so it properly converts wchar_t into UTF-8 char, perhaps by using codecvt<wchar_t, char, mbstate_t> and std::wstring_convert. This way hopefully even Windows will be able to handle unicode paths.

**Comment by almightykiwi** [comment]
That makes sense.

Off topic, but for the record, I have libstdc++ 4.8 (fairly recent) installed on my system, and there is no `codecvt` header yet, so `BsDataStream.cpp` can't compile. (But it seems that libc++ has complete support for C++11, so I'll try to use it instead.)

**Comment by BearishSun** [comment]
Actually thinking about this some more, my suggestion is wrong. Windows will not recognize the narrow string as UTF-8 and assume it's ASCII resulting in trying to open a junk file path if there are any unicode characters.

Your second suggestion is then probably better, use #ifdef to separate the two calls to fstream. fstreams shouldn't be constructed outside of FileDataStream (if they are, they should probably use FileDataStream instead to avoid having these #ifdefs in multiple places in the code).

**Comment by BearishSun** [comment]
Whoops, accidental close.
