### ISSUE TITLE
GUIToggle label not displayed if the style is set to EditorStyles.Toggle

### ISSUE THREAD

**Issue by jayrulez** [BearishSun/BansheeEngine#252]

**Comment by jayrulez** [comment]
The behavior is still the same if I do not specify a style. If I do not specify a style should the label still not be displayed?

**Comment by BearishSun** [comment]
The default style is just to display a checkbox, no text. That's because GUIToggle is essentially just a variant of a button, so text would be centered over the checkbox graphic, and would also be interactable.

**Comment by jayrulez** [comment]
Okay. I got you. It seems I was using the wrong control anyway. I will take the ideas from the camera inspector.
