### ISSUE TITLE
Editor crashes when adding a camera to an empty scene.

### ISSUE THREAD

**Issue by jayrulez** [BearishSun/BansheeEngine#254]
[20181125_2231.zip](https://github.com/BearishSun/BansheeEngine/files/2613976/20181125_2231.zip)

This was running in debug mode.

**Comment by christianclavet** [comment]
Hi, Some fixes have been done recently to the editor. Can you try with a new build? I'm able to create a camera in an empty scene with no crash now. There still more work to do to make the editor work stable, but this problem seem to be fixed now.

**Comment by christianclavet** [comment]
This can be closed. I tested again with a new build (june 22) and it doesn't crash anymore.
