### ISSUE TITLE
Building BANSHEE VULKAN on Win64, fail.

### ISSUE THREAD

**Issue by christianclavet** [BearishSun/BansheeEngine#257]
Hi, I've updated to the lastest source and tried to create a new build today using VULKAN.
Got error building VULKAN API dll with errors in compilation. Compiled using Visual Studio Community 2017 on windows 10, using a NVidia GTX 1080.

Is my vulkan API is not the proper version?:

Here is the result of vulkan info:
 Device Properties and Extensions :
==================================
GPU0
VkPhysicalDeviceProperties:
===========================
        apiVersion     = 0x401054  (1.1.84)
        driverVersion  = 1749598208 (0x6848c000)
        vendorID       = 0x10de
        deviceID       = 0x1b80
        deviceType     = DISCRETE_GPU
        deviceName     = GeForce GTX 1080
        VkPhysicalDeviceLimits:
        -----------------------
                maxImageDimension1D                     = 32768
                maxImageDimension2D                     = 32768
                maxImageDimension3D                     = 16384
                maxImageDimensionCube                   = 32768
                maxImageArrayLayers                     = 2048
                maxTexelBufferElements                  = 0x8000000
                maxUniformBufferRange                   = 0x10000
                maxStorageBufferRange                   = 0xffffffff
                maxPushConstantsSize                    = 256
                maxMemoryAllocationCount                = 4096
                maxSamplerAllocationCount               = 4000
                bufferImageGranularity                  = 0x400
                sparseAddressSpaceSize                  = 0xffffffffffffffff
                maxBoundDescriptorSets                  = 32
                maxPerStageDescriptorSamplers           = 1048576
                maxPerStageDescriptorUniformBuffers     = 15
                maxPerStageDescriptorStorageBuffers     = 1048576
                maxPerStageDescriptorSampledImages      = 1048576
                maxPerStageDescriptorStorageImages      = 1048576
                maxPerStageDescriptorInputAttachments   = 1048576
                maxPerStageResources                    = 4294967295
                maxDescriptorSetSamplers                = 1048576
                maxDescriptorSetUniformBuffers          = 90
                maxDescriptorSetUniformBuffersDynamic   = 15
                maxDescriptorSetStorageBuffers          = 1048576
                maxDescriptorSetStorageBuffersDynamic   = 16
                maxDescriptorSetSampledImages           = 1048576
                maxDescriptorSetStorageImages           = 1048576
                maxDescriptorSetInputAttachments        = 1048576
                maxVertexInputAttributes                = 32
                maxVertexInputBindings                  = 32
                maxVertexInputAttributeOffset           = 0x7ff
                maxVertexInputBindingStride             = 0x800
                maxVertexOutputComponents               = 128
                maxTessellationGenerationLevel          = 64
                maxTessellationPatchSize                        = 32
                maxTessellationControlPerVertexInputComponents  = 128
                maxTessellationControlPerVertexOutputComponents = 128
                maxTessellationControlPerPatchOutputComponents  = 120
                maxTessellationControlTotalOutputComponents     = 4216
                maxTessellationEvaluationInputComponents        = 128
                maxTessellationEvaluationOutputComponents       = 128
                maxGeometryShaderInvocations            = 32
                maxGeometryInputComponents              = 128
                maxGeometryOutputComponents             = 128
                maxGeometryOutputVertices               = 1024
                maxGeometryTotalOutputComponents        = 1024
                maxFragmentInputComponents              = 128
                maxFragmentOutputAttachments            = 8
                maxFragmentDualSrcAttachments           = 1
                maxFragmentCombinedOutputResources      = 16
                maxComputeSharedMemorySize              = 0xc000
                maxComputeWorkGroupCount[0]             = 2147483647
                maxComputeWorkGroupCount[1]             = 65535
                maxComputeWorkGroupCount[2]             = 65535
                maxComputeWorkGroupInvocations          = 1536
                maxComputeWorkGroupSize[0]              = 1536
                maxComputeWorkGroupSize[1]              = 1024
                maxComputeWorkGroupSize[2]              = 64
                subPixelPrecisionBits                   = 8
                subTexelPrecisionBits                   = 8
                mipmapPrecisionBits                     = 8
                maxDrawIndexedIndexValue                = 4294967295
                maxDrawIndirectCount                    = 4294967295
                maxSamplerLodBias                       = 15.000000
                maxSamplerAnisotropy                    = 16.000000
                maxViewports                            = 16
                maxViewportDimensions[0]                = 32768
                maxViewportDimensions[1]                = 32768
                viewportBoundsRange[0]                  =-65536.000000
                viewportBoundsRange[1]                  = 65536.000000
                viewportSubPixelBits                    = 8
                minMemoryMapAlignment                   = 64
                minTexelBufferOffsetAlignment           = 0x10
                minUniformBufferOffsetAlignment         = 0x100
                minStorageBufferOffsetAlignment         = 0x20
                minTexelOffset                          = -8
                maxTexelOffset                          =  7
                minTexelGatherOffset                    =-32
                maxTexelGatherOffset                    = 31
                minInterpolationOffset                  =-0.500000
                maxInterpolationOffset                  = 0.437500
                subPixelInterpolationOffsetBits         = 4
                maxFramebufferWidth                     = 32768
                maxFramebufferHeight                    = 32768
                maxFramebufferLayers                    = 2048
                framebufferColorSampleCounts            = 15
                framebufferDepthSampleCounts            = 15
                framebufferStencilSampleCounts          = 31
                framebufferNoAttachmentsSampleCounts    = 31
                maxColorAttachments                     = 8
                sampledImageColorSampleCounts           = 15
                sampledImageDepthSampleCounts           = 15
                sampledImageStencilSampleCounts         = 31
                sampledImageIntegerSampleCounts         = 15
                storageImageSampleCounts                = 15
                maxSampleMaskWords                      = 1
                timestampComputeAndGraphics             = 1
                timestampPeriod                         = 1.000000
                maxClipDistances                        = 8
                maxCullDistances                        = 8
                maxCombinedClipAndCullDistances         = 8
                discreteQueuePriorities                 = 2
                pointSizeRange[0]                       = 1.000000
                pointSizeRange[1]                       = 189.875000
                lineWidthRange[0]                       = 0.500000
                lineWidthRange[1]                       = 10.000000
                pointSizeGranularity                    = 0.125000
                lineWidthGranularity                    = 0.125000
                strictLines                             = 1
                standardSampleLocations                 = 1
                optimalBufferCopyOffsetAlignment        = 0x1
                optimalBufferCopyRowPitchAlignment      = 0x1
                nonCoherentAtomSize                     = 0x40
        VkPhysicalDeviceSparseProperties:
        ---------------------------------
                residencyStandard2DBlockShape            = 1
                residencyStandard2DMultisampleBlockShape = 1
                residencyStandard3DBlockShape            = 1
                residencyAlignedMipSize                  = 0
                residencyNonResidentStrict               = 1

Device Extensions       count = 63
        VK_KHR_8bit_storage                 : extension revision  1
        VK_KHR_16bit_storage                : extension revision  1
        VK_KHR_bind_memory2                 : extension revision  1
        VK_KHR_create_renderpass2           : extension revision  1
        VK_KHR_dedicated_allocation         : extension revision  3
        VK_KHR_descriptor_update_template   : extension revision  1
        VK_KHR_device_group                 : extension revision  3
        VK_KHR_draw_indirect_count          : extension revision  1
        VK_KHR_driver_properties            : extension revision  1
        VK_KHR_external_fence               : extension revision  1
        VK_KHR_external_fence_win32         : extension revision  1
        VK_KHR_external_memory              : extension revision  1
        VK_KHR_external_memory_win32        : extension revision  1
        VK_KHR_external_semaphore           : extension revision  1
        VK_KHR_external_semaphore_win32     : extension revision  1
        VK_KHR_get_memory_requirements2     : extension revision  1
        VK_KHR_image_format_list            : extension revision  1
        VK_KHR_maintenance1                 : extension revision  2
        VK_KHR_maintenance2                 : extension revision  1
        VK_KHR_maintenance3                 : extension revision  1
        VK_KHR_multiview                    : extension revision  1
        VK_KHR_push_descriptor              : extension revision  2
        VK_KHR_relaxed_block_layout         : extension revision  1
        VK_KHR_sampler_mirror_clamp_to_edge : extension revision  1
        VK_KHR_sampler_ycbcr_conversion     : extension revision  1
        VK_KHR_shader_atomic_int64          : extension revision  1
        VK_KHR_shader_draw_parameters       : extension revision  1
        VK_KHR_storage_buffer_storage_class : extension revision  1
        VK_KHR_swapchain                    : extension revision 70
        VK_KHR_variable_pointers            : extension revision  1
        VK_KHR_vulkan_memory_model          : extension revision  2
        VK_KHR_win32_keyed_mutex            : extension revision  1
        VK_EXT_blend_operation_advanced     : extension revision  2
        VK_EXT_conditional_rendering        : extension revision  1
        VK_EXT_conservative_rasterization   : extension revision  1
        VK_EXT_depth_range_unrestricted     : extension revision  1
        VK_EXT_descriptor_indexing          : extension revision  2
        VK_EXT_discard_rectangles           : extension revision  1
        VK_EXT_hdr_metadata                 : extension revision  1
        VK_EXT_inline_uniform_block         : extension revision  1
        VK_EXT_post_depth_coverage          : extension revision  1
        VK_EXT_sample_locations             : extension revision  1
        VK_EXT_sampler_filter_minmax        : extension revision  1
        VK_EXT_shader_subgroup_ballot       : extension revision  1
        VK_EXT_shader_subgroup_vote         : extension revision  1
        VK_EXT_shader_viewport_index_layer  : extension revision  1
        VK_EXT_vertex_attribute_divisor     : extension revision  3
        VK_NV_clip_space_w_scaling          : extension revision  1
        VK_NV_dedicated_allocation          : extension revision  1
        VK_NV_device_diagnostic_checkpoints : extension revision  2
        VK_NV_external_memory               : extension revision  1
        VK_NV_external_memory_win32         : extension revision  1
        VK_NV_fill_rectangle                : extension revision  1
        VK_NV_fragment_coverage_to_color    : extension revision  1
        VK_NV_framebuffer_mixed_samples     : extension revision  1
        VK_NV_geometry_shader_passthrough   : extension revision  1
        VK_NV_sample_mask_override_coverage : extension revision  1
        VK_NV_shader_subgroup_partitioned   : extension revision  1
        VK_NV_viewport_array2               : extension revision  1
        VK_NV_viewport_swizzle              : extension revision  1
        VK_NV_win32_keyed_mutex             : extension revision  1
        VK_NVX_device_generated_commands    : extension revision  3
        VK_NVX_multiview_per_view_attributes: extension revision  1

**Comment by BearishSun** [comment]
Do you have the error it is reporting during compilation?

My guess is that you need to install Vulkan SDK: https://vulkan.lunarg.com/sdk/home . Get version 1.1.85. You also need to set up the `VULKAN_SDK` environment variable to point to your SDK install folder (e.g. `C:\VulkanSDK\1.1.85.0`) and then re-run CMake.

**Comment by christianclavet** [comment]
Hi, I checked the folders I have and the API is 1.1.92. I rebooted the system and it still does it.
But it will not give any compile error in compile the BSF library. So BSF is ok when compiling, not the editor...

vk_mem_alloc.h give lots of errors while compiling and is used inside the Banshee Editor plugin bsf_VulkanRenderApi. 

So I think it's ok for now, the new improvements you made in BSF for Vulkan broke vulkan support in the editor. It compile fine in DX and GL. Once you start working back in the editor again, this part will need to be adjusted to work with the new changes in BSF.

**Comment by christianclavet** [comment]
Hi, After seeing that you updated the editor, I decided to try to make a VULKAN build again. Used TortoiseGIT to create the 2 repos and it build and compile correctly this time. Was able to start the editor.

But can't import any meshes, or add anything to the scene. (Crash and immediate close each time) I'll wait for more updates but I can create a VULKAN Build this time and this issue can be closed.

**Comment by BearishSun** [comment]
Hey. Can you confirm you have `Vulkan 1.1.85` or lower? Newever SDK versions will not work at the moment.

**Comment by christianclavet** [comment]
Looking at the SDK folder, it's: 1.1.92.1
There seem to have another folder with another version: 1.0.37.0
Don't know which one it selected.

**Comment by BearishSun** [comment]
`VULKAN_SDK` environment variable controls which one is used. It most likely 1.1.92.1 since its the more recent version.

There are known issues with newer SDK versions and Banshee that cause crashes. It's unclear if that's the crash you are experiencing. Until things are more stable I do highly suggest using DirectX as it's the version I develop on, and only version I have tested on so far.

**Comment by christianclavet** [comment]
Ok. I created a build using DX and it give the same errors. The instant I want to add a mesh to the scene it crash. (DX & Vulkan). Vulkan still give me the editor interface and I was able to add a camera and move it without crashing. But will use DX and let you update the editor.
