### ISSUE TITLE
Editor crashes... 

### ISSUE THREAD

**Issue by christianclavet** [BearishSun/BansheeEngine#258]
Hi, Just built a DX11 version of Banshee 3D and got a crash the instant I try to instantiate the particle system.

Checking at the error it seem related to the "layout". I know that I'm running it at 4k resolution, but then changed my display resolution to 2k and still the same problem.

Anything that I try to instantiate from the menu make the application crash. Seem related to GUI problem with font and layouts...

Just wanted to have a peek of the progress made in BSF, and wanted to see if I could see something from the editor, but it seem the editor will need some tweaks...

Here is the report from the application:

Type | Description
-- | --
Error | A fatal error occurred and the program has to terminate!Unhandled exception at 0x140710068870181. Access violation reading 0x96.Stack trace: bs::Font::getClosestSize() - 0x140710068870181 File[bsfont.cpp:60 (0)] Module[bsf.dll]bs::TextDataBase::TextDataBase() - 0x140710068905435 File[bstextdata.cpp:364 (0)] Module[bsf.dll]bs::GUIHelper::calcOptimalContentsSize() - 0x140710070662171 File[bsguihelper.cpp:52 (44)] Module[bsf.dll]bs::GUIHelper::calcOptimalContentsSize() - 0x140710070661657 File[bsguihelper.cpp:26 (0)] Module[bsf.dll]bs::GUILabel::_getOptimalSize() - 0x140710070455083 File[bsguilabel.cpp:134 (23)] Module[bsf.dll]bs::GUIElementBase::_calculateLayoutSizeRange() - 0x140710070620571 File[bsguielementbase.cpp:424 (0)] Module[bsf.dll]bs::GUIElementBase::_getLayoutSizeRange() - 0x140710070620623 File[bsguielementbase.cpp:430 (9)] Module[bsf.dll]bs::GUILayoutX::_updateOptimalLayoutSizes() - 0x140710070560876 File[bsguilayoutx.cpp:65 (11)] Module[bsf.dll]bs::GUIElementBase::_updateOptimalLayoutSizes() - 0x140710070620394 File[bsguielementbase.cpp:410 (9)] Module[bsf.dll]bs::GUIElementBase::_updateOptimalLayoutSizes() - 0x140710070620394 File[bsguielementbase.cpp:410 (9)] Module[bsf.dll]bs::GUILayoutX::_updateOptimalLayoutSizes() - 0x140710070560679 File[bsguilayoutx.cpp:52 (0)] Module[bsf.dll]bs::GUIElementBase::_updateOptimalLayoutSizes() - 0x140710070620394 File[bsguielementbase.cpp:410 (9)] Module[bsf.dll]bs::GUIElementBase::_updateOptimalLayoutSizes() - 0x140710070620394 File[bsguielementbase.cpp:410 (9)] Module[bsf.dll]bs::GUILayoutY::_updateOptimalLayoutSizes() - 0x140710070565671 File[bsguilayouty.cpp:52 (0)] Module[bsf.dll]bs::GUIElementBase::_updateOptimalLayoutSizes() - 0x140710070620394 File[bsguielementbase.cpp:410 (9)] Module[bsf.dll]bs::GUIPanel::_updateOptimalLayoutSizes() - 0x140710070780557 File[bsguipanel.cpp:88 (0)] Module[bsf.dll]bs::GUIElementBase::_updateOptimalLayoutSizes() - 0x140710070620394 File[bsguielementbase.cpp:410 (9)] Module[bsf.dll]bs::GUILayoutY::_updateOptimalLayoutSizes() - 0x140710070565671 File[bsguilayouty.cpp:52 (0)] Module[bsf.dll]bs::GUIElementBase::_updateOptimalLayoutSizes() - 0x140710070620394 File[bsguielementbase.cpp:410 (9)] Module[bsf.dll]bs::GUIPanel::_updateOptimalLayoutSizes() - 0x140710070780557 File[bsguipanel.cpp:88 (0)] Module[bsf.dll]bs::GUIElementBase::_updateOptimalLayoutSizes() - 0x140710070620394 File[bsguielementbase.cpp:410 (9)] Module[bsf.dll]bs::GUILayoutY::_updateOptimalLayoutSizes() - 0x140710070565671 File[bsguilayouty.cpp:52 (0)] Module[bsf.dll]bs::GUIElementBase::_updateOptimalLayoutSizes() - 0x140710070620394 File[bsguielementbase.cpp:410 (9)] Module[bsf.dll]bs::GUIScrollArea::_updateOptimalLayoutSizes() - 0x140710070627861 File[bsguiscrollarea.cpp:83 (0)] Module[bsf.dll]bs::GUIWidget::_updateLayout() - 0x140710070802711 File[bsguiwidget.cpp:215 (0)] Module[bsf.dll]bs::GUIElementBase::getBounds() - 0x140710070618291 File[bsguielementbase.cpp:140 (29)] Module[bsf.dll]bs::ScriptGUIElement::internal_getBounds() - 0x140709926116523 File[bsscriptguielement.cpp:289 (18)] Module[SBansheeEngine.dll]0x23392457868670x1065353215

**Comment by BearishSun** [comment]
I have a bunch of uncommited changes, plus I haven't check the state of various data dependencies in a long while (i.e. testing with a fresh project). Either of those could be the cause. I'll get around to it once I have some of the WIP features finalized.

**Comment by christianclavet** [comment]
Hi! I perfectly understand you will need to adapt these new changes to the editor. Just wanted to have a peek at the new features and realized that the editor is not ready yet... :)

I'll wait and check the updates on github and will give it another try when the editor will become more stable. You made remarkable work so far on both of them (framework and editor)! The most memorable change I've seen is the speed the editor is starting now, comparing it to 0.4. I'm eager to see the new stuff in the editor when it's ready! 👍

**Comment by christianclavet** [comment]
New crashes from today build (3 april 2019), can't put anything inside the scene without a crash and close and there is no report like it used to do (Got the folder created but no files are generated). I got a little excited to see the new items (particles, and decals) in the menu. :)

**Comment by christianclavet** [comment]
Ok. This is getting weird. Created a new build in DX (Release) and it still crash at the same place.
Decided to create a debug build (Dx) to see where it crash: It does'nt!

I just got this exception that is being catched:
![Capture](https://user-images.githubusercontent.com/13395943/55660416-37102900-57d4-11e9-9a57-390e80495de2.JPG)
"Managed exception: Object reference not set to an instance of an object"
Can you try a release version to see if you make it crash?

**Comment by BearishSun** [comment]
Yeah release crashes for me too, that seems to be it. I'll let you know when it's resolved. Thanks for the notes.

**Comment by BearishSun** [comment]
That managed exception issue should be resolved on latest. The release mode is still not fixed.

**Comment by christianclavet** [comment]
Thanks Marko. That could be a compiler directive, that is missing somewhere or misplaced. I have immediate exit of the application with no error (exit(0). Thanks for looking on it!

**Comment by christianclavet** [comment]
Hi, Instead of create a "release" build, I've done a release with "debug information". I had some libs missing from the build (copied over from the release build that I had) and tried to run in the local debugger and without the debugger.

It's now doing an immediate close now when I try to add a mesh in the scene. And this is almost as fast as the release build. 
![Capture](https://user-images.githubusercontent.com/13395943/55760753-05dd6600-5a2b-11e9-92a6-856b27d8395f.JPG)

**Comment by christianclavet** [comment]
Thanks Marko! Thanks also for the information about how to check release builds!

**Comment by christianclavet** [comment]
Created a new release build and tested. No crash now. Thanks.
