### ISSUE TITLE
Mysterious #defines

### ISSUE THREAD

**Issue by almightykiwi** [BearishSun/BansheeEngine#26]
In `Source/BansheeCore/Include/BsRenderAPICapabilities.h`, there's a couple of mysterious `#defines`:

```
#define CAPS_CATEGORY_SIZE 8i64
#define BS_CAPS_BITSHIFT (64i64 - CAPS_CATEGORY_SIZE)
#define CAPS_CATEGORY_MASK (((1i64 << CAPS_CATEGORY_SIZE) - 1i64) << BS_CAPS_BITSHIFT)
#define BS_CAPS_VALUE(cat, val) ((cat << BS_CAPS_BITSHIFT) | (1i64 << val))
```

What are `8i64`, `1i64` and `64i64`? I have never seen this syntax, and neither has gcc, apparently ;-).

**Comment by BearishSun** [comment]
They force the integer to by 64 bit instead of 32, otherwise the bit-shifts might shift into nothingness. I think the equivalent suffix that is also multiplatform is "LL".

**Comment by almightykiwi** [comment]
Oh, ok. Actually, there are macros in `cstdint` that append the correct suffix to create integer constants of a given size, like `INT64_C(8)`. I guess I'll use this, and I will submit it in a future pull request.
Thank you for your reply.
