### ISSUE TITLE
Saved scenes lose data when reloaded

### ISSUE THREAD

**Issue by jayrulez** [BearishSun/BansheeEngine#264]
Scene objects with meshes seem to lose their meshes when reopened after restarting the editor.

**Comment by BearishSun** [comment]
This was only happening to me with built-in meshes (box, sphere, etc.). It should now be resolved with 51d3353876ada1161dab971d0ce7854afa99a53c. If you feel you had problems with normal meshes, or the issue isn't resolved feel free to reopen.
