### ISSUE TITLE
Window stretching issue, and aspect ratio of the main window.

### ISSUE THREAD

**Issue by christianclavet** [BearishSun/BansheeEngine#268]
Build on:
Windows 10 Home
Release
DX11
Build date: 04/13/2019
Video card: NVIDIA GTX1080
**Issue Description:**

I have a dual screen setup. One screen is 4k oriented landscape (3840x2160), and the other is 2k oriented portrait (1200x1920).

I did not notice this at first on the landscape oriented screen, but when I moved the Banshee Editor windows over the portrait oriented screen.

**First issue:** The main window cannot be stretched from the right or bottom.
**Second issue:** When stretching in a non landscape way the content don't seem to be updated properly, we lose the right corner widget of the windows (minimize, maximize, close)
**Third issue:** If we are able to maximize the windows it will take a landscape orientation and be cropped by the screen.

Here is a screenshot (Issue 1 and 2):
![image](https://user-images.githubusercontent.com/13395943/56083561-8e298580-5df4-11e9-906c-161db70064ee.png)

Screenshot for issue 3:
![image](https://user-images.githubusercontent.com/13395943/56083584-ce890380-5df4-11e9-9b22-00789dbb8aea.png)

**EDIT:** The stretching limitation on the right and bottom seem to happen also with all windows.

**Comment by BearishSun** [comment]
Thanks for the report (and for all the other issues as well). I'm able to reproduce issue 1 and 2, haven't tried 3 yet. I'll let you know when I have a fix.

**Comment by christianclavet** [comment]
3 will be hard to reproduce if you cannot work in portrait mode with your screen. The last screen show what happened when I pressed the maximize button on the screen right corner. (I'm still able to scale the window by using the top and left side) If you scale the window in a landscape proportion, the buttons will appear again.

**Comment by BearishSun** [comment]
1 and 3 should be resolved. For 2 I still need to decide what's the best way to handle it.

**Comment by christianclavet** [comment]
Confirmed for the fix. They work now.
