### ISSUE TITLE
Library window not focused after triggered modal.

### ISSUE THREAD

**Issue by jayrulez** [BearishSun/BansheeEngine#272]
Trigger a modal from the library window by following these steps:

1. Create a folder.
2. Rename the folder to "test".
3. Create a second folder.
4. Try to rename it to "test".
After the modal is dismissed I expect the library window to have focus again and be active so when I hit f2 the rename text entry for the selected item pops up again.
However, while the item is still selected hitting f2 does nothing.

**Comment by christianclavet** [comment]
Hi, Tested this today (june 24 with today build), and got the same. Issue confirmed. To "recover" I have to use the rename item from the menu. After that, F2 is usable again on that item.

Checked the details of what is done:
1. After the operation, the icon is still selected (blue)
2. Pressing F2, will not do anything.
3. Clicking on the icon and pressing F2 will show the text being highlighted for editing but closed immediately. Each press of F2 will repeat this behavior
4. Right clicking on the icon, give the menu, and selecting RENAME will enable to change the name.
5. Once (4) is done, you can press the F2 key to rename the item without any issue.

**Comment by BearishSun** [comment]
Thanks for the report. This should be resolved on latest.
