### ISSUE TITLE
Project crashes and become unloadable after adding a script

### ISSUE THREAD

**Issue by jayrulez** [BearishSun/BansheeEngine#274]
I'm not sure if it is he added script or something else that is causing the crash but I've attached the project here for reproduction.
[Test7.zip](https://github.com/BearishSun/BansheeEngine/files/3078139/Test7.zip)

**Comment by BearishSun** [comment]
This should be resolved on the latest master. `GUIWidget` component was not properly handling the assembly refresh that was triggered when a new script was added.
