### ISSUE TITLE
Crashing when adding component Reflexion probe

### ISSUE THREAD

**Issue by barraganlazlo** [BearishSun/BansheeEngine#279]
When i first add Reflexion probe component to an object it puts an error :
![image](https://user-images.githubusercontent.com/24246051/56809097-56c6ca00-6833-11e9-812d-1ae0f5a07cc0.png)
if i delete the component and add it another time it crash
logs :
[20190426_1451.zip](https://github.com/BearishSun/BansheeEngine/files/3121355/20190426_1451.zip)

**Comment by BearishSun** [comment]
Hi, thanks for the report. The crash, as well as the errors should be resolved on the latest master. If the problem is still happening feel free to re-open the issue.
