### ISSUE TITLE
creating shader ressources cross compilation failed error

### ISSUE THREAD

**Issue by barraganlazlo** [BearishSun/BansheeEngine#280]
after creating a shader ressource by right clicking on the library panel
banshee logs an error
![image](https://user-images.githubusercontent.com/24246051/56852066-987c7100-6916-11e9-8176-7fa2957edd31.png)

**Comment by BearishSun** [comment]
Thanks for the report. Should be fixed on latest master. Note the fix will not work retroactively, you will need to delete the old shader file and create a new one.
