### ISSUE TITLE
Issue: Material not displaying with the standard material when first applied

### ISSUE THREAD

**Issue by christianclavet** [BearishSun/BansheeEngine#292]
Hi. 

I've done a new test with a new build (18 may) of Banshee.

Loaded a model, created a new material, put the textures in the slots and applied back the material to the model and added a lamp.

Here is the screenshot
![Banshee](https://user-images.githubusercontent.com/13395943/57975171-4a491380-7992-11e9-80ac-7ce51b4f8b97.JPG)

I don't see the material being applied to the model. It still all gray.

If I quit and reload the application and the scene. Now I can see the textures.
![Banshee2](https://user-images.githubusercontent.com/13395943/57975512-37d1d880-7998-11e9-9e24-af6c0c5515ac.JPG)

Here is a sample scene (removed some assets because of GITHUB file size limitation):
[cclavet_problems.zip](https://github.com/BearishSun/BansheeEngine/files/3194519/cclavet_problems.zip)

Note: The model show "material" slots that are being expanded (as first screenshot). It would be nice to have the material textures inside the material slot itself and be collapsed by default. So you could expand the material and change the textures without having all of them at once. (Or having a E "edit" button) to edit the texture and shader of the material slot.

Note2: When moving a model in the scene some axes are inverted. The model is moving the reverse the mouse is moving. Only the Z axis seem to move correctly (following the mouse movement)

**Comment by BearishSun** [comment]
Thanks. I'm aware of the material not updating issue. I've also added material grouping on the Renderable inspector just yesterday, so you should be seeing that in a more recent build.

**Comment by christianclavet** [comment]
Thanks. If you can, it would be nice to get the material names from the import (Most of time when I export, all material slots correspond to sub-objects that have names) Getting the names would simplify the task of assigning them their material definition.

**Comment by BearishSun** [comment]
Already on my radar, along with bunch of other editor enhancements. However those will all have to wait as my priority is to get existing functionality stable, followed by high level framework features that are still missing.

**Comment by BearishSun** [comment]
Textures assigned to materials should now show up properly. I haven't managed to reproduce the problem you mentioned with move axes being inverted.

**Comment by BearishSun** [comment]
Scene axis invert issue should now also be resolved (was only a problem on Vulkan).

**Comment by christianclavet** [comment]
Thanks. I'll do a build with Vulkan and try again.
