### ISSUE TITLE
Issue: VULKAN Backend -> Application crash (Leak) 

### ISSUE THREAD

**Issue by christianclavet** [BearishSun/BansheeEngine#293]
Operating system: Windows 10
Build date: 18 may 2019
Graphic API used: Vulkan

Description of the problem:
The application run correctly, then after time period of inactivity it crash (exception catch happened before closing and created a crash report)

Here is the Vulkan runtime installed:
![image](https://user-images.githubusercontent.com/13395943/57976842-2ac4e180-79b8-11e9-857c-a21a71c120a8.png)

Here is the report:

Type | Time | Description
-- | -- | --
Error | 19:04:18 | A fatal error occurred and the program has to terminate!Unhandled exception at 0x1977217277. Access violation reading 0x48.Stack trace: 0x1977217277 Module[nvoglv64.dll]0x1977218616 Module[nvoglv64.dll]0x1977275137 Module[nvoglv64.dll]0x1977317137 Module[nvoglv64.dll]0x1977281079 Module[nvoglv64.dll]0x1977382982 Module[nvoglv64.dll]bs::ct::VulkanGraphicsPipelineState::createPipeline() - 0x140722404833229 File[bsvulkangpupipelinestate.cpp:485 (0)] Module[bsfVulkanRenderAPI.dll]bs::ct::VulkanGraphicsPipelineState::getPipeline() - 0x140722404831971 File[bsvulkangpupipelinestate.cpp:338 (0)] Module[bsfVulkanRenderAPI.dll]bs::ct::VulkanCmdBuffer::bindGraphicsPipeline() - 0x140722404750481 File[bsvulkancommandbuffer.cpp:1279 (46)] Module[bsfVulkanRenderAPI.dll]bs::ct::VulkanRenderAPI::drawIndexed() - 0x140722404722583 File[bsvulkanrenderapi.cpp:456 (83)] Module[bsfVulkanRenderAPI.dll]bs::ct::RendererUtility::drawScreenQuad() - 0x140722272530069 File[bsrendererutility.cpp:368 (55)] Module[bsf.dll]bs::ct::BuildHiZMat::execute() - 0x140722365921367 File[bspostprocessing.cpp:1102 (0)] Module[bsfRenderBeast.dll]bs::ct::RCNodeHiZ::render() - 0x140722365622192 File[bsrendercompositor.cpp:2261 (40)] Module[bsfRenderBeast.dll]bs::ct::RenderCompositor::execute() - 0x140722365576602 File[bsrendercompositor.cpp:178 (0)] Module[bsfRenderBeast.dll]bs::ct::RenderBeast::renderView() - 0x140722365298960 File[bsrenderbeast.cpp:515 (49)] Module[bsfRenderBeast.dll]bs::ct::RenderBeast::renderViews() - 0x140722365298353 File[bsrenderbeast.cpp:457 (0)] Module[bsfRenderBeast.dll]bs::ct::RenderBeast::renderAllCore() - 0x140722365297857 File[bsrenderbeast.cpp:429 (0)] Module[bsfRenderBeast.dll]std::_Func_impl_no_alloc,void>::_Do_call() - 0x140722365367002 File[functional:15732480 (0)] Module[bsfRenderBeast.dll]bs::CommandQueueBase::playbackWithNotify() - 0x140722268688812 File[bscommandqueue.cpp:127 (0)] Module[bsf.dll]bs::CommandQueueBase::playback() - 0x140722268689047 File[bscommandqueue.cpp:141 (0)] Module[bsf.dll]bs::CommandQueueBase::playbackWithNotify() - 0x140722268688812 File[bscommandqueue.cpp:127 (0)] Module[bsf.dll]bs::CoreThread::runCoreThread() - 0x140722268736938 File[bscorethread.cpp:118 (0)] Module[bsf.dll]bs::PooledThread::run() - 0x140722268256377 File[bsthreadpool.cpp:115 (6)] Module[bsf.dll]std::_Pad::_Call_func() - 0x140722268254199 File[xthread:210 (33)] Module[bsf.dll]0x140723313451002 Module[ucrtbase.dll]0x140723345652084 Module[KERNEL32.DLL]0x140723368665713 Module[ntdll.dll]

**Comment by BearishSun** [comment]
Thanks for the report. Seems like a potential resource leak somewhere in the Vulkan backend.

**Comment by christianclavet** [comment]
I've checked it more and seem it get all available memory when it crash.
![image](https://user-images.githubusercontent.com/13395943/58058165-cdef3580-7b35-11e9-946b-b4ad50a0734f.png)

**Comment by christianclavet** [comment]
Just updating, with a new build using a DX11 renderer (25 may), the memory consumption seem stable.

**Comment by BearishSun** [comment]
Interesting, so the crash no longer happens when using Vulkan? Not really sure what I fixed that would have solved it.

**Comment by jayrulez** [comment]
I was having a similar issue like a week ago where the application would crash after running for a short period of time. I switched from Vulkan to OpenGL backend for now because that is the only one that seems to work well enough for me right now.

I could test Vulkan again and see if the issue is still there.

**Comment by christianclavet** [comment]
Sorry. Re-tested (Vulkan - Win10 x64 build from 22 june) and closed this one too early. There is still a memory leak going on. (Around 5mb per second here). The crash seem to occur because all ram is taken. So I'll re-open it.

**Comment by BearishSun** [comment]
This should be resolved on latest.

**Comment by christianclavet** [comment]
Hi, Just created a new Vulkan build and work fine now. Memory is stable now. Thanks for fixing it!😊
