### ISSUE TITLE
Issues with BC Compressors for images textures.

### ISSUE THREAD

**Issue by christianclavet** [BearishSun/BansheeEngine#294]
Hi, Just to leave some feedback on theses as I've tried them today. (may 19, 2019)

The compression is working, and I've seen improvement as there some feedback on the interface (still seem to freeze sometimes). Quite slow, but it work.

I've seen some little issues that might annoy some users:

- All icons representation assumes that the source image is based from RGBA8 images. But when converted to other formats like the BCx types the image is garbled.

- When selecting a cubemap image texture, the texture type gui is not displayed. There is a way to have it displayed by reloading the application and scene, or by saving the scene (force a refresh). By pressing the reimport button and not having selected the type of cubemap will still do it but generate an error. I was forced to press the reimport button 2 times for the skybox, because it was set to another type and I did not access to the type GUI.

- In my VULKAN build it work, but the application give me errors when I convert to the BC formats: (Still display ok)
_"unpackColor not implemented for "BC...", packColor not implemented for "BC..." in BsPixelUtil.cpp_

- When converting, Banshee will often stop syncing with the OS. On my Windows 10, the Banshee window got blank (white overlay) a lot of time and window telling me the application was not responding and asked if I want to close. It's nice to see the rotating wheel telling the application is processing...

Found information that is teaching how to use the block compressor that would be useful, is that information is in the user documentation somewhere? 
[understanding-bcn-texture-compression-formats](http://www.reedbeta.com/blog/understanding-bcn-texture-compression-formats/)

**Comment by christianclavet** [comment]
Just to give an update, changing the texture format can give other issues. I had a RGBA8 texture that I did not wanted to use the alpha channel. Decided to change it to RGB8 format; then got Banshee crash, and would not reload the project.

I had to delete the material and the .meta for the textures directly to be able to reload the project.

**Comment by BearishSun** [comment]
Thanks, this whole system very much needs an overhaul - I was hoping to get away with something quick a dirty for texture preview only, but might need to implement a proper preview system sooner than expected.

We don't have any information about block compression formats in the docs - `PixelFormat` enum gives you a basic explanation.

**Comment by christianclavet** [comment]
Hi, with the new build of today (25 may) the scene is not loading and crash when I try to load it. Seem that the BC compressor used make it fail. Found also that when I delete the resource folder from the internal folder, it try to rebuild from the info in the .meta file. For the moment, i'll remove all the compressors from my assets since its too unstable.

**Comment by christianclavet** [comment]
Hi, Just seen that. Perhaps , you could get a peek over it if it get better performance at compression. The current one take a long time to compress, use lots of CPU and RAM to do it's work.
[https://github.com/binomialLLC/basis_universal](https://github.com/binomialLLC/basis_universal)

**Comment by BearishSun** [comment]
Preview for block compressed formats should now work. RGB textures should also now work properly on Vulkan.

That's seems to be a good library. When I'm free I'll investigate integrating it and we can hopefully speed up texture compression.

**Comment by christianclavet** [comment]
Hi, Just to update of the preview, I tested it and it work fine now. I've got the preview showing correctly.
