### ISSUE TITLE
Issue with decals

### ISSUE THREAD

**Issue by christianclavet** [BearishSun/BansheeEngine#295]
Hi, I was able to use decals, and I think I figured it out except one thing. I have a transparency texture that serve as a cutout (Gray 8bit PNG)  and also the texture has a ALPHA (PNG).

Found theses on the internet and decided to use it as a decal and project a graffiti on the wall.
(I hate graffitis in real life, but this is only a test..  😄 )
![graffiti-1935630_960_720](https://user-images.githubusercontent.com/13395943/58140018-5ee41080-7c0b-11e9-9deb-84f277d01493.png)
![graffiti_mask](https://user-images.githubusercontent.com/13395943/58140019-5ee41080-7c0b-11e9-8af3-ac44e1651df7.png)

Here is the result:
![Decals](https://user-images.githubusercontent.com/13395943/58140062-8d61eb80-7c0b-11e9-8c69-f945ce8d7d71.JPG)

If you look the part that should be transparent is still showing a dark overlay. Also I had to put the gUVTILE Y to - 1 as the decal was reversed on that axis.

Is there something in my source files that make that it's not totally transparent? I only want to show the graffiti.

What is the gMaskTex? I tried it and it did not change anything.
BTW, Congrat for making it! Once I saw it projecting on the wall, I could move it and rotate it projection easily and it work really well.

**Comment by BearishSun** [comment]
I've yet to test decals in the editor at all. `gMaskTex` should not be visible to the user as its used for internal purposes.

Not sure about the transparency, it works in the framework example project. But decals support different blend modes, which are currently not selectable in the editor, so if it's using some weird blend mode that could be it.

**Comment by christianclavet** [comment]
Ok. Then it work, just the transparency that is not working 100%. But, I've not tested the normal maps and/other maps other than the albedo.

**Comment by christianclavet** [comment]
Hi! Just seen this on the patreon page!
[ProgressUpdate](https://www.patreon.com/posts/progress-update-23068477)
From the example, you were able to get the alpha blending correctly. Do you have an example scene I could check. Perhaps something I was not using properly in the editor.

**Comment by BearishSun** [comment]
There's a Decals example in the framework examples: https://github.com/GameFoundry/bsfExamples

That's where the image is from. I haven't properly hooked up or tested decals in the editor yet.

**Comment by christianclavet** [comment]
Hi! Thank! This give me a better idea of what could be occurring. 

Checked the code and the demo doesn't use any lighting except perhaps the skybox. So this could be related to lighting and decals materials interaction. The default blending was also enforced and you don't this parameter in the shader parameters of the editor.

**Comment by BearishSun** [comment]
It was indeed lighting related.

The incorrect transparency issue and the flipped rendering issues were resolved. Variation selection was also added so you can choose between blend modes within the editor. Ideally everything decal related should now be functional.

**Comment by christianclavet** [comment]
Hi, Marko.

**Decal transparency fixed and more!**
Transparency work 100%. It's taking the alpha transparency information from the image and the rendering is good. I see the projection direction now (don't remember seeing it before) by a bounding box. Also when not selecting the decal, it show a "can" icon that can be clicked on and will select the decal.  👍😊 

(Small note: For the icons, I see them changing shape as I move in the scene, I don't know why. Ex: Icon shape changes from "light" to "decal" to another as I move in the scene)

**Little issue with the image projection:**
Got a small issue with the image itself that is flipped (vertically). I've tried to play with the UV setting and size (negative) but nothing changed this time. When I used a negative size, the image disappeared. 

Here is a screenshot. Note that the image is flipped vertically (BTW My scene that was crashing at load seem to load fine now with this new build (16 june)
![image](https://user-images.githubusercontent.com/13395943/59566219-0ac22580-902b-11e9-916a-cf164c098f37.png)

**Comment by BearishSun** [comment]
Thanks for testing. Reopening the issue due to the flipping problem.

Let me know if you can get consistent reproduction steps for the transform change issue.

**Comment by christianclavet** [comment]
Hi!
I reloaded my scene to re-test, but strangely, **my texture was gone, and material.** I've reimported it and created a new material and _there is no flipping now_. I don't know why it had the flipping issue before.

When you delete an active asset in the library, does Banshee, remove the asset from the scene hierarchy? I might have accidentally deleted the asset from the library and values got flipped there. (Also this is the scene I had problems) Perhaps something got mixed in the scene data...

For the transform affecting the size:
![image](https://user-images.githubusercontent.com/13395943/59889929-c1f8cc80-939c-11e9-94b8-2e99b14b39eb.png)
Changing the value there will change the size value, in the inspector. So from the image, changing the Y transform to 2, will put 1.2 in the size. Since I re-imported the asset and redone the material, all seem ok there. But with the old data, it was really weird.

For reproducing the issue with the transform-size interaction:

1. Set the Y of the transform to 1, then try to set the value of the Size of the Decal to -1, the decal will disappear. Set it back to the old value (setting a value <0, will make it disappear and not flip) I would like to use it to flip the image and it's not working.)
2. Set the Y of the transform to -1, the value will also be inverted in the Size, and you will see it flipped (desired intend)
3. With option 2 done, save your scene and reload. The Decal will disappear again. (since the Size<0 is set) 

Specific to the transform input:
Seen that when you press "backspace" key when you input values in the transform will put a "0", then when you put another number it will be put after the "0". I have to select the "0" to remove it.

**Comment by BearishSun** [comment]
Thanks for the description. The size weirdness should be resolved on latest.

If you delete the asset in the library, it will be removed wherever it was linked from, including the scene.

**Comment by christianclavet** [comment]
Thanks. With a new scene and new project. Seem to work perfectly fine. I just remarked that when I delete an item from the library, any object that has been instanced in the scene will remain there (Probably need to be improved, but is not related to Decals). If quit and reload the scene the object will not be there (as intended), but is not removed from the "active-live" objects.
