### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by christianclavet** [BearishSun/BansheeEngine#296]
Just created a new build today (25 may) and the editor crash on startup. Editor no longer work.
Seem related to the changes to "PlayInEditor" recently done and the crash seem to be on the mono side (c#).  

This is a Win10 DX Build this time (Wanted to check if the resource leak was also affecting DX)

Here is the report:
Banshee Engine Log
System information
bs::framework version: 1.1.0

Started on: Saturday, May 25, 2019 13:38:23

OS version: Windows 10 64-bit

CPU information:
CPU vendor: GenuineIntel

CPU name: Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz

CPU clock speed: 3500Mhz

CPU core count: 8

GPU List:
GPU #0: NVIDIA GeForce GTX 1080

GPU #1: Microsoft Basic Render Driver
Type | Time | Description
-- | -- | --
Error | 13:38:25 | 
- A fatal error occurred and the program has to terminate!
- Error: InvalidParametersException
- Description: Unable to find class of type: "bs.Editor::PlayInEditor"
- In function: void __cdecl bs::MonoManager::initializeScriptTypes(class bs::MonoAssembly &)
- In file: C:\Users\Public\Projets\Banshee\Source\bsf\Source\Scripting\bsfMono\BsMonoManager.cpp:198

Stack trace: 
bs::CrashHandler::reportCrash() - 0x140725247074672 File[bswin32crashhandler.cpp:473 (0)] Module[bsf.dll]
bs::MonoManager::initializeScriptTypes() - 0x140697393226621 File[bsmonomanager.cpp:197 (172)] Module[Banshee3D.exe]
bs::MonoManager::loadAssembly() - 0x140697393225838 File[bsmonomanager.cpp:182 (0)] Module[Banshee3D.exe]bs::EditorScriptLibrary::initialize() - 0x140697391982953 File[bseditorscriptlibrary.cpp:27 (78)] Module[Banshee3D.exe]
bs::ScriptManager::ScriptManager() - 0x140725250423781 File[bsscriptmanager.cpp:13 (0)] Module[bsf.dll]
bs::EditorApplication::onStartUp() - 0x140725435715742 File[bseditorapplication.cpp:139 (234)] Module[EditorCore.dll]
WinMain() - 0x140697391664325 File[bseditorexec.cpp:29 (0)] Module[Banshee3D.exe]
__scrt_common_main_seh() - 0x140697393243446 File[exe_common.inl:283 (33)] Module[Banshee3D.exe]
0x140726386129268 Module[KERNEL32.DLL]
0x140726398657137 Module[ntdll.dll]

**Comment by christianclavet** [comment]
Hi, Done a another build of type: ReleaseWithDebugInfo and got another report. (Still crash on startup, after showing the Banshee logo):

The class is different this time...

[ERROR] A fatal error occurred and the program has to terminate!
  - Error: InvalidParametersException
  - Description: Unable to find class of type: "bs::AsyncOpBase"
  - In function: void __cdecl bs::MonoManager::initializeScriptTypes(class bs::MonoAssembly &)
  - In file: C:\Users\Public\Projets\Banshee\Source\bsf\Source\Scripting\bsfMono\BsMonoManager.cpp:198

Stack trace: 
bs::CrashHandler::reportCrash() - 0x140725004715274 File[bswin32crashhandler.cpp:473 (0)] Module[bsf.dll]
bs::MonoManager::initializeScriptTypes() - 0x140699334968482 File[bsmonomanager.cpp:197 (172)] Module[Banshee3D.exe]
bs::MonoManager::loadAssembly() - 0x140699334967730 File[bsmonomanager.cpp:182 (0)] Module[Banshee3D.exe]
bs::EngineScriptLibrary::initialize() - 0x140699334509772 File[bsenginescriptlibrary.cpp:36 (113)] Module[Banshee3D.exe]
bs::EditorScriptLibrary::initialize() - 0x140699333883559 File[bseditorscriptlibrary.cpp:23 (5)] Module[Banshee3D.exe]
bs::ScriptManager::ScriptManager() - 0x140725007725701 File[bsscriptmanager.cpp:13 (0)] Module[bsf.dll]
bs::bs_new<bs::ScriptManager>() - 0x140725369698647 File[bsmemoryallocator.h:354 (17)] Module[EditorCore.dll]
bs::EditorApplication::onStartUp() - 0x140725369685523 File[bseditorapplication.cpp:139 (217)] Module[EditorCore.dll]
WinMain() - 0x140699333621989 File[bseditorexec.cpp:29 (0)] Module[Banshee3D.exe]
__scrt_common_main_seh() - 0x140699334987862 File[exe_common.inl:283 (33)] Module[Banshee3D.exe]
0x140726386129268 Module[KERNEL32.DLL]
0x140726398657137 Module[ntdll.dll]

**Comment by BearishSun** [comment]
Try re-running CMake then recompiling. When new C# files get added CMake needs to be re-ran otherwise they aren't part of the project files and don't get compiled. `RelWithDebInfo` might be a separate issue, I don't suggest using that configuration at the moment.

**Comment by christianclavet** [comment]
Thanks. I've deleted everything in the build folder, and redone it again. This time, the build did not crash.
