### ISSUE TITLE
Issue with materials using transparent shader

### ISSUE THREAD

**Issue by christianclavet** [BearishSun/BansheeEngine#297]
When selecting the transparent shader in the editor the editor crash (and recuperate a little with this message)
![image](https://user-images.githubusercontent.com/13395943/58375792-73851900-7f29-11e9-939c-e97879ba54fb.png)
And the inspector look like this:
![image](https://user-images.githubusercontent.com/13395943/58375812-f0b08e00-7f29-11e9-9278-b50917183b80.png)

This happen for 2 shaders:
- transparent
- particlelit

Other shaders seem ok.

If the material was already defined (as in my spaceship cockpit in my scenes), loading back the project will result in an immediate crash.

Crash with build source from 25 may, Windows 10 - DX11

**Comment by BearishSun** [comment]
Can you provide the crash log (in case its a hard crash), or click the Show Details button in Log window and show the call-stack (if it's just an error message). Thanks.

**Comment by christianclavet** [comment]
Hi, Here is what I have:
[20190525_1958.zip](https://github.com/BearishSun/BansheeEngine/files/3220532/20190525_1958.zip)
[20190525_2001.zip](https://github.com/BearishSun/BansheeEngine/files/3220528/20190525_2001.zip)


Banshee Engine Log
System information
bs::framework version: 1.1.0

Started on: Saturday, May 25, 2019 20:01:45

OS version: Windows 10 64-bit

CPU information:
CPU vendor: GenuineIntel

CPU name: Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz

CPU clock speed: 3500Mhz

CPU core count: 8

GPU List:
GPU #0: NVIDIA GeForce GTX 1080

GPU #1: Microsoft Basic Render Driver

Log entries

**Comment by christianclavet** [comment]
This seem to work fine with the latest builds. Can't reproduce it anymore now.
