### ISSUE TITLE
Can't save a scene anymore on my existing project. (Work with new projects)

### ISSUE THREAD

**Issue by christianclavet** [BearishSun/BansheeEngine#298]
With this new build (25 may), I tried to save a scene and got this on an existing project that I was trying to recover:
![image](https://user-images.githubusercontent.com/13395943/58375988-f3ad7d80-7f2d-11e9-81c5-d1942c3c5047.png)

I only selected "save scene" from the menu:
![image](https://user-images.githubusercontent.com/13395943/58375993-25264900-7f2e-11e9-9d19-a7515b854822.png)

So the path must be good. But Banshee still thinks the path is not good.

If I'm doing it from a new project, it work. This only give me this on my current project.

**UPDATE (EDIT)**
Deleted the project folder, created a new project (same name) and copied files from a backup (only the resource folder not the internal folder) and let it rebuild the internal folder (removed the material for the cockpit because of another issue). It took a very long time to rebuild the assets because I used compression.

The application crashed when I tried to save back a new scene:
![image](https://user-images.githubusercontent.com/13395943/58376301-e09eab80-7f35-11e9-9cde-1a13f6832c6c.png)
Still the icon appeared and now got 2 scenes.  The new scene that crashed on save missed the .meta file when I tried to load it back, but Banshee seem to have created a new one. So I think this problem could be related to the assets in the internal folder.

I had to force close the application (using windows task manager) because It would repeat the error each time I would try to close the application. (closing the window or using the exit menu item)

**NOTE:** The billboard that represent lights and other assets seem to display correctly now. Before they were not visible when I was getting near the object with the scene camera.

**Comment by BearishSun** [comment]
Hi. Most of these issues reported recently are caused by a corrupt project. Sadly I don't think I can do much without the project itself, as I cannot reproduce the problem. If you can send me the project it would be helpful.

**Comment by christianclavet** [comment]
Hi, Marko. Sent you my project via WETRANSFER, I compressed it in a zip file and it's more than 415MB.

**Comment by BearishSun** [comment]
Great, thanks for sending that, it'll help a lot.

**Comment by christianclavet** [comment]
Thanks. I can load back the scene now and it does'nt crash.
