### ISSUE TITLE
Crash when creating a new material with OpenGL backend

### ISSUE THREAD

**Issue by jayrulez** [BearishSun/BansheeEngine#303]
```
[ERROR] A fatal error occurred and the program has to terminate!
  - Error: RenderingAPIException
  - Description: OpenGL error: Error has been generated. GL error GL_INVALID_VALUE in TexStorage2D: (ID: 3202140462) Generic error
  - In function: void __cdecl bs::ct::openGlErrorCallback(unsigned int,unsigned int,unsigned int,unsigned int,int,const char *,void *)
  - In file: d:\banshee\bansheeengine\source\bsf\source\plugins\bsfglrenderapi\bsglrenderapi.cpp:2738

Stack trace: 
bs::CrashHandler::reportCrash() - 0x140727883166294 File[bswin32crashhandler.cpp:473 (0)] Module[bsf.dll]
bs::ct::openGlErrorCallback() - 0x140728236793291 File[bsglrenderapi.cpp:2738 (181)] Module[bsfGLRenderAPI.dll]
```

Let me know if you need more info

**Comment by christianclavet** [comment]
Created a new build in GL from June 22: Issue confirmed
Got this:

A fatal error occurred and the program has to terminate!
- Error: RenderingAPIException
- Description: Zero sized texture surface on texture face 0 mipmap 0. Probably, the GL driver refused to create the texture.
- In function: void __cdecl bs::ct::GLTexture::createSurfaceList(void)
- In file: C:\Users\Public\Projets\Banshee\Source\bsf\Source\Plugins\bsfGLRenderAPI\BsGLTexture.cpp:516

This build is running on Windows 10, with a NVIDIA GTX 1080 GPU.

**To reproduce:**
1. Create a new project
2. In the empty scene, create a new material in the ressource windows
3. Result is the crash.
4. If you re-open the project, the material is there, but clicking on it to see it on the inspector side will result in another crash.

**Comment by BearishSun** [comment]
This one slipped my mind. I'll increase priority and hopefully get to it soon.

**Comment by BearishSun** [comment]
Should be resolved on latest.
