### ISSUE TITLE
Question: Reference size cubes needed.

### ISSUE THREAD

**Issue by christianclavet** [BearishSun/BansheeEngine#304]
Hi! Would you be able to provide us with a model of a reference cube for a 1 meter sized size? OBJ would be great since it does not have scale ratios. From there I could measure it in Blender and get the proper size for my models.

I'm still not used to the correct size in Banshee, and this would be critical for Physic (meter per second velocity, etc.) So old tests I've done with physic give unrealistic result and I'm almost 100% sure, it's because my models scale.

Having a model that is internally match a meter in Banshee would be great to have access to.
Thanks.

**Comment by BearishSun** [comment]
You can probably create one yourself. You can create one that you think its  right, import it and compare with built-in cube (which is 1x1x1). Alternatively just move the object in the scene and check the transform coordinates, 1 unit = 1 meter.

**Comment by christianclavet** [comment]
Cool! I didn't think about it! I'll try that!
