### ISSUE TITLE
Helper Icons issue. VULKAN with helper icons, not displaying at the proper position.

### ISSUE THREAD

**Issue by christianclavet** [BearishSun/BansheeEngine#305]
Hi, Done 2 build today (june 22). A DX and Vulkan build and remarked immediately that there helper icons were not displaying properly.

![image](https://user-images.githubusercontent.com/13395943/59968434-f1781800-9507-11e9-8879-e72dace03149.png)
Here I see the icon of a decal, it it positioned exactly at the position of the object. In  Vulkan, it's not there, but I still can see them appearing while I move but in improper position.

On DX, I can see the helper icons at the proper place but I see an issue:

1. The icons change shape (image) while I move in the scene (FPS controls of the scene camera)

Here is a screenshot:
![image](https://user-images.githubusercontent.com/13395943/59968489-ac081a80-9508-11e9-8bc1-952b7bf4f2d5.png)
Here there is a reflection probe at 0,0,0 (gray cube), and there a is radial light at the ship nose and it's displaying a decal icon. If I move the icon change:

![image](https://user-images.githubusercontent.com/13395943/59968511-e70a4e00-9508-11e9-9ca2-0a1612285003.png)
Note: The icon image seem to change depending of the angle and position, I am from the node position.

**Comment by BearishSun** [comment]
Thanks for the report. Both of the issues should be resolved on latest.

If you can try to make a separate issue for each specific problem (feel free to just link one issue from another and provide an extra set of details, while the main issue contains most of the information). 

It's easier to deal with if I fix one issue and don't fix another. As I'm unable to close the issue and then when I come back to it later I might not even remember which part is fixed or which isn't, causing disorganization.
