### ISSUE TITLE
Issue: Importing "locked" files assets will crash the editor

### ISSUE THREAD

**Issue by christianclavet** [BearishSun/BansheeEngine#307]
This is not 100% reproducible but happened to me when I was exporting assets to Banshee from Blender.

Steps:
1. Open a model in any modeling application (Used blender here)
2. Export the model from the application (used .obj)
3. Immediately drag&drop the file into Banshee 3D (ressource area), the modeling application still opened.
4. On some occasion go a crash while importing, Banshee was not able to recuperate from this. I suspect that my modeling application (Blender) did not removed the lock on the file immediately after writing and Banshee wanted to open the the file (perhaps in RW mode)

Expected behavior:
Warning, but can continue working and not crashing. Do not create the model icon in the resource folder if it fail to import.

Current behavior:
Warning, but loop crashing. Import progress, with error, and repeat non-stop. Have to force close the application to be able to work with the project.

**Comment by BearishSun** [comment]
Interesting, thanks for the report. I do suspect this one might be difficult to reproduce.

**Comment by christianclavet** [comment]
I was able to reproduce it:

Exported a mesh from Blender in .FBX format. There is no textures on it, but the UV are present.
![image](https://user-images.githubusercontent.com/13395943/60039197-29a46580-9684-11e9-9c00-f3e15bc24a72.png)
I see the asset icon there but it's stuck in importing. Looping non-stop.

This is what happen when I try to close the application
![image](https://user-images.githubusercontent.com/13395943/60039369-8b64cf80-9684-11e9-82b2-ebc1062b500b.png)

It produced an crash output:
![image](https://user-images.githubusercontent.com/13395943/60039499-d8e13c80-9684-11e9-9f6e-3c804756624e.png)

**Comment by christianclavet** [comment]
**Update:** With my last build (30 june). I was not able to make it crash this time. I'm not sure it's resolved, but it did not happen.

I have Blender opened at the same time of Banshee and updated some assets (uv maps), reimported everything without any issue.

**Comment by BearishSun** [comment]
I'll close this if its not reproducible. Previous versions would crash often on import and most of these issues are hopefully now fixed. If it happens again please reopen.
