### ISSUE TITLE
Issue: Importing assets will crash the editor when saving the scene/project.

### ISSUE THREAD

**Issue by christianclavet** [BearishSun/BansheeEngine#309]
Hi, 

Been practicing making modular assets (using the grid) with the new scale reference. My assets fit the grid nicely now and I expect that physic be improved since it's up to scale now.

Been importing some basic models to check, and placing them in a scene. Everything is working fine except when I'm saving the scene and/or the project. Got crashes.

[CrashReports.zip](https://github.com/BearishSun/BansheeEngine/files/3322836/CrashReports.zip)

Here are the steps I'm using:
1. Import the asset by drag&drop in the library
2. drag the model in the hierarchy so it appear in the scene
3. Position the model and assign a material
4. Save the scene/project
5. Crash

**Comment by BearishSun** [comment]
Is this happening in 100% of the cases? I cannot reproduce on my end.

**Comment by christianclavet** [comment]
Do you import meshes? This happen at least 75% of the times I import models I've made in blender. Is the Crashreport give some kind of hint about where it could crash? I could figure the result of the crashreport myself. Everytime this happen is when I save the scene and or project.

**Comment by BearishSun** [comment]
The crash reports aren't telling me much. The first two look like it crashed due to editor window layout, rather than anything mesh related. And the third one seems to be related to textures.

Having a crash log from a debug version of the editor would have more exact information if you can get a moment to try that.

**Comment by christianclavet** [comment]
I tried a debug build (29 june) and created a new project, reimported my assets (models and textures). Saved the scene and project. No crash.

Reloaded my scene, imported other models, saved the scene project, still no crash. This will take me some time.
