### ISSUE TITLE
Issue: Not seeing the textures maps beeing applied properly when first imported.

### ISSUE THREAD

**Issue by christianclavet** [BearishSun/BansheeEngine#310]
Hi, I worked on importing some model today, and still seeing issues with textures maps.

Steps:
1. Import some textures maps (albedo, metallic, normal and roughness)
2. Create a new material and assign them their proper slot
3. Assign the material into the material slot of a model
4. Notice **no texture details** on the model (UV scale?!) Some properties seem to be applied but no details of the texture.
5. Save the scene/project and quit Banshee.
6. Start Banshee again and load your scene, the texture details is now visible.

I've tested this and this seem to apply to all texture maps, perhaps the UVScale that is being at 0 when they are first imported, I'm really not sure. But I see something changing in the model material when it's first applied.

If your material was previously saved, it display correctly when applied to the model. This only happen when the textures are imported and the material created.
EDIT: Build on DX

**Comment by christianclavet** [comment]
Hi, Been able to reproduce it.
1. Loaded a test map I was doing.
2. Imported new textures (3 of them)
3. Created a new material, from the new textures
4. Applied the material to the meshes
5. Result: All black. I don't see the textures.
![image](https://user-images.githubusercontent.com/13395943/60451780-de95cf80-9bfa-11e9-8715-ace75a3b4a68.png)
6. Saved the scene and project. And closed Banshee
7. Started Banshee again, and opened the scene
8: Result:
![image](https://user-images.githubusercontent.com/13395943/60451860-10a73180-9bfb-11e9-8598-adfeff0a4b3a.png)
9. Here after adjusting the texture tile parameter of the texture on the material. (I've found a way to have the UV size the same from each model in Blender).:
![image](https://user-images.githubusercontent.com/13395943/60452066-bf4b7200-9bfb-11e9-8b52-9c868bbe983d.png)


Note: Perhaps something changed with this new build but I didn't see any crashes with all the importing I've done and scene saving so far.

**Comment by christianclavet** [comment]
EDIT:There seem to be an issue with normal maps and/or lighting. I have to save the scene and reload Banshee sometimes to see the lighting update the normal map correctly. So I'll keep it here.
 
Playing with save, reload, and inverting the normal map resolve the problem at some point:
Here is the desired effect with some tweaks. I used a sun light.
Here is the image with the normal map provided: (Notice the shadowing in the normal map, it's look inverted)
![image](https://user-images.githubusercontent.com/13395943/60455769-5bc64200-9c05-11e9-8122-3348f9516733.png)

Here I created an inverted normal map in a paint program from the original. Here what happen when I apply it first:
![image](https://user-images.githubusercontent.com/13395943/60455813-86b09600-9c05-11e9-96f6-fad73d341f1b.png)

If I save the scene, quit Banshee and reload the scene, I got the correct result (without touching anything), but I'm using an inverted normal map.
![image](https://user-images.githubusercontent.com/13395943/60455289-03db0b80-9c04-11e9-87b6-e89ff1f1339d.png)

I'm not sure about if it's the light, the normal map or other things. Can you check the scene and see if the normal map and/or lighting has issues?:
Here is a [LINK TO DROPBOX](https://www.dropbox.com/s/95hsqgm2djk9w14/test2.zip?dl=0)

**Comment by BearishSun** [comment]
Hi, thanks for investigating. I cannot reproduce the first issue. I followed the steps you described:
1. I import a new texture
2. I create a new material
3. I assign the material to an object
4. I set the texture on the material (tried both setting it on object, or on Material itself)

I've seen the texture show up properly. Let me know if there are perhaps steps I am missing. I'm using the built-in box mesh as a test - maybe it's something mesh related.

**Comment by christianclavet** [comment]
Strange, I was even able to reproduce with a Quad.

Try this:
1. Import a new set of PBR textures ([https://freepbr.com/](https://freepbr.com/))
2. Create a new material with most of the slot assigned
3. Create a lamp
4. Create a QUAD
5. Drag the new material in the material slot of the model in the inspector

Result is that is should be black
If you save the scene, project and close the editor, when reloading, it will display.

**Comment by BearishSun** [comment]
I'm afraid I still cannot reproduce, even with those exact steps. I've created a new project then followed those exact steps above and the material renders properly without reload. Perhaps something got broken in your project? Also, how old is the version of the editor this is happening on?

**Comment by christianclavet** [comment]
Redone the steps today, and I'm able to reproduce it 100% with my Vulkan build (was doing it with DX before). I'm doing a new build each saturday. So when the report was done, the build was barely new. For the report from today, the build was made this morning.

Theses build are done, using VS2017 on NVIDIA Hardware (GTX 1080), running on Win10 (1903), as release.

As for the project for testing this, a new one is made every time and using simply the QUAD primitive with a PBR texture from the internet.

At some point, I was thinking I was not doing my builds properly, I've downloaded the build appveyor and was also able to reproduce it:
[Build from APPVEYOR](https://ci.appveyor.com/project/BearishSun/bansheeengine/build/artifacts)

Then, I decided the create a DEBUG Build and run it on the local debugger. Was not able to reproduce it. 
Can you repeat the steps on a release build (you can take the one from APPVEYOR) and check it?

**Comment by BearishSun** [comment]
Thanks for narrowing it down, I was finally able to reproduce it in release mode. It should be fixed on latest.

I haven't had a chance to look at the normal map issue yet.

**Comment by christianclavet** [comment]
This seem to happen with the directional light currently. I retested it with the other light types and seem ok.

**Comment by christianclavet** [comment]
Hi, restested it today with a Vulkan Build (made on 13 july). Setup the same kind of scene with the texture applied (5 tiles) on a the cube with the directional light.

Result:
1. Texture appeared correctly once imported. No black image anymore.
2. Checked the normal map "shadowing" when using a normal map and using the directional light. Seem ok now.
Here is a screen:
![image](https://user-images.githubusercontent.com/13395943/61176434-e2c4d400-a58e-11e9-89af-cad280b1120d.png)
Note: Thanks for fixing the icons position on Vulkan! I really like the fade effect when we get near of them. That's really a nice touch! 😊
