### ISSUE TITLE
Animation Windows issues

### ISSUE THREAD

**Issue by christianclavet** [BearishSun/BansheeEngine#312]
Hi, Made a new build Vulkan today (6 july) and tested the animation window with a simple cube.

This windows show great improvement and work much better that the firsts iterations but there still more work to do. But I feel I could use it to create cutscenes and lots of animation with it (doors opening, elevators, etc.). This is really a great feature! 😀

1-Animation curves drawing
The animation curve drawing seem inverted. The DOT of the keyframe is presented at the proper position and can be selected and tweaked (we can even tweak the handle there). But the animation curve drawing seem to have issues:
![image](https://user-images.githubusercontent.com/13395943/60761278-0c23b400-a013-11e9-8717-a9608ec28f24.png)

2-Animation rendered issues from keyframe data.
I set a Y rotation of the object to turn 360 degrees at each seconds for 30 second. The translation movement seem fine, but the rotation seem wrong. Perhap an issue with the interpolation (Gimbal lock?)

I've put the project/scene here if you want to check since there almost nothing it's really small.
[TEST3.zip](https://github.com/BearishSun/BansheeEngine/files/3365051/TEST3.zip)

**Comment by BearishSun** [comment]
Thanks for the report. Both of the issues should be resolved on latest.
 - Animations over 180 degrees were incorrectly wrapping around
 - Line rendering on Vulkan was inverted on the Y axis

**Comment by christianclavet** [comment]
Fix confirmed. Line rendering follow the keyframes and the rotation property is animation correctly now.
