### ISSUE TITLE
Build error by syntax error in BsScriptUndoRedo.cpp

### ISSUE THREAD

**Issue by christianclavet** [BearishSun/BansheeEngine#314]
Hi, There is a syntax error (missing ";") at line 229 of that file in the source of the editor.
There is the code:

> 			BuiltinComponentInfo* info = sam.getBuiltinComponentInfo(paramType);
> 			if (info == nullptr)
> 			{
> 				BS_LOG(Warning, Editor, "Provided type is not a valid component")
> 				continue;
> 			}

Just missing a semicolon.

Once I added it, it was building correctly.

It occured since [this change](https://github.com/BearishSun/BansheeEngine/commit/a658d20dba2d5d4adda2145e690697bc357b9799#diff-7f0a4fa916a87597a5775d021b67e154) 14 day ago.

**Comment by BearishSun** [comment]
Should be fixed on latest. What compiler was this happening on? VS2017 wasn't complaining for me nor on the CI server.

**Comment by christianclavet** [comment]
Hi, Marko!
This happened to me on VS2017 on Windows 10. If all the bugs were that easy to fix, I could help you on the side of the code, but I'm not skilled enough. At least, I can help you with bug tracking...☺

**Comment by BearishSun** [comment]
Thanks. That's what I use though, and haven't had any compilation issues, nor should there have been any as that code was valid regardless. And on top of that, there were other cases where the semicolon was missing after `BS_LOG`.

We only added the requirement to use a semicolon in `BS_LOG` to `bsf` repository yesterday, but that wasn't integrated into Banshee until today, so it couldn't have been it (unless you manually pulled a newer `bsf` version).

**Comment by christianclavet** [comment]
Ha! ok. That explain all. I pull both repo manually when I create a new build. I've dropped github desktop and now using TortoiseGIT to update the repos (Banshee and BSF).

I probably pulled a newer version of BSF...
