### ISSUE TITLE
Animation Windows: Editor freeze if animation window is present at reload

### ISSUE THREAD

**Issue by christianclavet** [BearishSun/BansheeEngine#315]
Hi,

I've found an issue directly related to the animation window freezing the editor when loading a scene. This seem to happen because I docked the animation window in the editor. If the window is closed when the scene is loaded the issue will not happen.

To replicate:
1. Dock the animation windows in the editor and close it.
2. Open the editor and load the provided project with the scene
[TEST3.zip](https://github.com/BearishSun/BansheeEngine/files/3389208/TEST3.zip)
3. Click on the cube in the scene or try to select it in the hierarchy view.

If the editor window is not opened when the scene is loaded or closed once it's loaded, clicking on the cube will not make it freeze.

**Comment by BearishSun** [comment]
Thanks for the report, this should be fixed on latest.

**Comment by christianclavet** [comment]
Fix confirmed. There is no freeze when the scene is loaded and the animation window is opened.
