### ISSUE TITLE
Animation Window: FPS setting is not saved.

### ISSUE THREAD

**Issue by christianclavet** [BearishSun/BansheeEngine#316]
In the animation windows there is a button to set the FPS of the playback of the animation clip.
Each time, I have to set it manually to 30FPS and each time the scene is reloaded the value goes back to 1FPS.

![image](https://user-images.githubusercontent.com/13395943/61176333-17379080-a58d-11e9-8fd4-62b101b9867b.png)

**Comment by BearishSun** [comment]
Thanks for the report. This should be resolved on latest.

**Comment by christianclavet** [comment]
Fix confirmed. The data is saved now.
