### ISSUE TITLE
Animation Window: Only the first property keyframe data is saved properly.

### ISSUE THREAD

**Issue by christianclavet** [BearishSun/BansheeEngine#317]
Hi,

When using the animation window. I remarked that my rotation data is not saved. (second property). The first property is position and every data is restored and keyframes are good.

The keyframe themselves seem to be saved but the retrieved data is wrong. Each time, I set the Y axis to set the rotation at 1440 degrees, and when loaded back the data is corrupted.

Here the rotation was set at frame 20, and the value was set at 1440. Reloaded and here is the result:
![image](https://user-images.githubusercontent.com/13395943/61176368-a644a880-a58d-11e9-902f-f4759e58e870.png)

**Comment by BearishSun** [comment]
This should be resolved but I didn't have time to properly test this today. Will close when I get a chance to verify.

**Comment by christianclavet** [comment]
Fix confirmed. The data is saved properly and the channel rotation animate correctly too.
