### ISSUE TITLE
Issue: Animations created by animation windows have a little glitch while animating.

### ISSUE THREAD

**Issue by christianclavet** [BearishSun/BansheeEngine#325]
Hi, I checked the animation made by the animation window on a cube, and all issues related to movement and rotation seemed to be fixed. But when getting at the beginning of a the loop it glitches (jumpy movement) and it doesn't happen to every loop.

How to replicate:

1. Use the provided project: (dropbox) 67mb
[https://www.dropbox.com/s/u70yw1w43zqddjl/TEST3.zip?dl=0](https://www.dropbox.com/s/u70yw1w43zqddjl/TEST3.zip?dl=0)
2. Load the scene and press the play button.
3. Observe the cube rotating and moving.
4. At some point while animating, you should see the glitch happen. (Movement|rotation stutter) This "glitch" doesn't happen at the same place all the time while looping.

Here is a screenshot. But you need to see it animating to see the problem:
![image](https://user-images.githubusercontent.com/13395943/62416725-09b27b00-b60e-11e9-8a13-50da692cc70d.png)

Note: Tested also the mipmaps creation and I'm happy to report that it work really well as it improved the cube texture rendering of my scene.

**Comment by BearishSun** [comment]
Thanks for the report. This should be resolved on latest.
