### ISSUE TITLE
Problems compiling (still)

### ISSUE THREAD

**Issue by MXSteel** [BearishSun/BansheeEngine#33]
>  BsFBXImporter.cpp
2>  BsFMODPlugin.cpp
2>D:\BansheeEngine\Source\BansheeFMOD\Include\BsFMODAudio.h(7): fatal error C1083: Cannot open include file: 'fmod.hpp': No such file or directory
2>  BsFMODImporter.cpp
2>D:\BansheeEngine\Source\BansheeFMOD\Include\BsFMODAudio.h(7): fatal error C1083: Cannot open include file: 'fmod.hpp': No such file or directory
2>  BsFMODAudioSource.cpp
1>D:\BansheeEngine\Source\BansheeFBXImporter\Source\BsFBXImporter.cpp(536): error C2819: type 'std::vector<BansheeEngine::TNamedAnimationCurve<BansheeEngine::Vector3>,BansheeEngine::StdAlloc<T,BansheeEngine::GenAlloc>>' does not have an overloaded member 'operator ->'
1>          with
1>          [
1>              T=BansheeEngine::TNamedAnimationCurve<BansheeEngine::Vector3>
1>          ]
1>  D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\vector(679): note: see declaration of 'std::vector<BansheeEngine::TNamedAnimationCurve<BansheeEngine::Vector3>,BansheeEngine::StdAlloc<T,BansheeEngine::GenAlloc>>'
1>          with
1>          [
1>              T=BansheeEngine::TNamedAnimationCurve<BansheeEngine::Vector3>
1>          ]
1>  D:\BansheeEngine\Source\BansheeFBXImporter\Source\BsFBXImporter.cpp(536): note: did you intend to use '.' instead?
1>  D:\BansheeEngine\Source\BansheeFBXImporter\Source\BsFBXImporter.cpp(543): note: see reference to function template instantiation 'auto BansheeEngine::FBXImporter::convertAnimations::<lambda_5746e8d4b9b9b75e1369ef5db81cb619>::operator ()<std::vector<BansheeEngine::TNamedAnimationCurve<BansheeEngine::Vector3>,BansheeEngine::StdAlloc<T,BansheeEngine::GenAlloc>>,std::vector<BansheeEngine::TNamedAnimationCurve<BansheeEngine::Vector3>,BansheeEngine::StdAlloc<T,BansheeEngine::GenAlloc>>>(std::vector<BansheeEngine::TNamedAnimationCurve<BansheeEngine::Vector3>,BansheeEngine::StdAlloc<T,BansheeEngine::GenAlloc>> &,std::vector<BansheeEngine::TNamedAnimationCurve<BansheeEngine::Vector3>,BansheeEngine::StdAlloc<T,BansheeEngine::GenAlloc>> &) const' being compiled
1>          with
1>          [
1>              T=BansheeEngine::TNamedAnimationCurve<BansheeEngine::Vector3>
1>          ]
1>D:\BansheeEngine\Source\BansheeFBXImporter\Source\BsFBXImporter.cpp(536): error C2039: 'position': is not a member of 'std::vector<BansheeEngine::TNamedAnimationCurve<BansheeEngine::Vector3>,BansheeEngine::StdAlloc<T,BansheeEngine::GenAlloc>>'
1>          with
1>          [
1>              T=BansheeEngine::TNamedAnimationCurve<BansheeEngine::Vector3>
1>          ]
1>  D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\vector(679): note: see declaration of 'std::vector<BansheeEngine::TNamedAnimationCurve<BansheeEngine::Vector3>,BansheeEngine::StdAlloc<T,BansheeEngine::GenAlloc>>'
1>          with
1>          [
1>              T=BansheeEngine::TNamedAnimationCurve<BansheeEngine::Vector3>
1>          ]
1>D:\BansheeEngine\Source\BansheeFBXImporter\Source\BsFBXImporter.cpp(536): error C2039: '__this': is not a member of 'std::vector<BansheeEngine::TNamedAnimationCurve<BansheeEngine::Vector3>,BansheeEngine::StdAlloc<T,BansheeEngine::GenAlloc>>'
1>          with
1>          [
1>              T=BansheeEngine::TNamedAnimationCurve<BansheeEngine::Vector3>
1>          ]
1>  D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\vector(679): note: see declaration of 'std::vector<BansheeEngine::TNamedAnimationCurve<BansheeEngine::Vector3>,BansheeEngine::StdAlloc<T,BansheeEngine::GenAlloc>>'
1>          with
1>          [
1>              T=BansheeEngine::TNamedAnimationCurve<BansheeEngine::Vector3>
1>          ]
1>D:\BansheeEngine\Source\BansheeFBXImporter\Source\BsFBXImporter.cpp(536): error C2228: left of '.curve' must have class/struct/union
1>D:\BansheeEngine\Source\BansheeFBXImporter\Source\BsFBXImporter.cpp(536): error C2228: left of '.split' must have class/struct/union
1>D:\BansheeEngine\Source\BansheeFBXImporter\Source\BsFBXImporter.cpp(539): error C2819: type 'BansheeEngine::TAnimationCurve<BansheeEngine::Vector3>' does not have an overloaded member 'operator ->'
1>  D:\BansheeEngine\Source\BansheeCore\Include\BsAnimationClip.h(55): note: see declaration of 'BansheeEngine::TAnimationCurve<BansheeEngine::Vector3>'
1>  D:\BansheeEngine\Source\BansheeFBXImporter\Source\BsFBXImporter.cpp(539): note: did you intend to use '.' instead?
1>D:\BansheeEngine\Source\BansheeFBXImporter\Source\BsFBXImporter.cpp(539): error C2232: '->BansheeEngine::TAnimationCurve<BansheeEngine::Vector3>::makeAdditive': left operand has 'class' type, use '.'
1>D:\BansheeEngine\Source\BansheeFBXImporter\Source\BsFBXImporter.cpp(525): error C2440: 'initializing': cannot convert from 'BansheeEngine::TAnimationCurve<BansheeEngine::Quaternion>' to 'BansheeEngine::TAnimationCurve<BansheeEngine::Vector3> &'
1>  D:\BansheeEngine\Source\BansheeFBXImporter\Source\BsFBXImporter.cpp(544): note: see reference to function template instantiation 'auto BansheeEngine::FBXImporter::convertAnimations::<lambda_5746e8d4b9b9b75e1369ef5db81cb619>::operator ()<std::vector<BansheeEngine::TNamedAnimationCurve<BansheeEngine::Quaternion>,BansheeEngine::StdAlloc<T,BansheeEngine::GenAlloc>>,std::vector<BansheeEngine::TNamedAnimationCurve<BansheeEngine::Quaternion>,BansheeEngine::StdAlloc<T,BansheeEngine::GenAlloc>>>(std::vector<BansheeEngine::TNamedAnimationCurve<BansheeEngine::Quaternion>,BansheeEngine::StdAlloc<T,BansheeEngine::GenAlloc>> &,std::vector<BansheeEngine::TNamedAnimationCurve<BansheeEngine::Quaternion>,BansheeEngine::StdAlloc<T,BansheeEngine::GenAlloc>> &) const' being compiled
1>          with
1>          [
1>              T=BansheeEngine::TNamedAnimationCurve<BansheeEngine::Quaternion>
1>          ]
1>D:\BansheeEngine\Source\BansheeFBXImporter\Source\BsFBXImporter.cpp(536): error C2819: type 'std::vector<BansheeEngine::TNamedAnimationCurve<BansheeEngine::Quaternion>,BansheeEngine::StdAlloc<T,BansheeEngine::GenAlloc>>' does not have an overloaded member 'operator ->'
1>          with
1>          [
1>              T=BansheeEngine::TNamedAnimationCurve<BansheeEngine::Quaternion>
1>          ]
1>  D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\vector(679): note: see declaration of 'std::vector<BansheeEngine::TNamedAnimationCurve<BansheeEngine::Quaternion>,BansheeEngine::StdAlloc<T,BansheeEngine::GenAlloc>>'
1>          with
1>          [
1>              T=BansheeEngine::TNamedAnimationCurve<BansheeEngine::Quaternion>
1>          ]
1>  D:\BansheeEngine\Source\BansheeFBXImporter\Source\BsFBXImporter.cpp(536): note: did you intend to use '.' instead?
1>D:\BansheeEngine\Source\BansheeFBXImporter\Source\BsFBXImporter.cpp(536): error C2039: 'position': is not a member of 'std::vector<BansheeEngine::TNamedAnimationCurve<BansheeEngine::Quaternion>,BansheeEngine::StdAlloc<T,BansheeEngine::GenAlloc>>'
1>          with
1>          [
1>              T=BansheeEngine::TNamedAnimationCurve<BansheeEngine::Quaternion>
1>          ]
1>  D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\vector(679): note: see declaration of 'std::vector<BansheeEngine::TNamedAnimationCurve<BansheeEngine::Quaternion>,BansheeEngine::StdAlloc<T,BansheeEngine::GenAlloc>>'
1>          with
1>          [
1>              T=BansheeEngine::TNamedAnimationCurve<BansheeEngine::Quaternion>
1>          ]
1>D:\BansheeEngine\Source\BansheeFBXImporter\Source\BsFBXImporter.cpp(536): error C2039: '__this': is not a member of 'std::vector<BansheeEngine::TNamedAnimationCurve<BansheeEngine::Quaternion>,BansheeEngine::StdAlloc<T,BansheeEngine::GenAlloc>>'
1>          with
1>          [
1>              T=BansheeEngine::TNamedAnimationCurve<BansheeEngine::Quaternion>
1>          ]
1>  D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\vector(679): note: see declaration of 'std::vector<BansheeEngine::TNamedAnimationCurve<BansheeEngine::Quaternion>,BansheeEngine::StdAlloc<T,BansheeEngine::GenAlloc>>'
1>          with
1>          [
1>              T=BansheeEngine::TNamedAnimationCurve<BansheeEngine::Quaternion>
1>          ]
1>D:\BansheeEngine\Source\BansheeFBXImporter\Source\BsFBXImporter.cpp(539): error C2819: type 'BansheeEngine::TAnimationCurve<BansheeEngine::Quaternion>' does not have an overloaded member 'operator ->'
1>  D:\BansheeEngine\Source\BansheeCore\Include\BsAnimationClip.h(66): note: see declaration of 'BansheeEngine::TAnimationCurve<BansheeEngine::Quaternion>'
1>  D:\BansheeEngine\Source\BansheeFBXImporter\Source\BsFBXImporter.cpp(539): note: did you intend to use '.' instead?
1>D:\BansheeEngine\Source\BansheeFBXImporter\Source\BsFBXImporter.cpp(539): error C2232: '->BansheeEngine::TAnimationCurve<BansheeEngine::Quaternion>::makeAdditive': left operand has 'class' type, use '.'
1>D:\BansheeEngine\Source\BansheeFBXImporter\Source\BsFBXImporter.cpp(525): error C2440: 'initializing': cannot convert from 'BansheeEngine::TAnimationCurve<float>' to 'BansheeEngine::TAnimationCurve<BansheeEngine::Vector3> &'
1>  D:\BansheeEngine\Source\BansheeFBXImporter\Source\BsFBXImporter.cpp(546): note: see reference to function template instantiation 'auto BansheeEngine::FBXImporter::convertAnimations::<lambda_5746e8d4b9b9b75e1369ef5db81cb619>::operator ()<std::vector<BansheeEngine::TNamedAnimationCurve<float>,BansheeEngine::StdAlloc<T,BansheeEngine::GenAlloc>>,std::vector<BansheeEngine::TNamedAnimationCurve<float>,BansheeEngine::StdAlloc<T,BansheeEngine::GenAlloc>>>(std::vector<BansheeEngine::TNamedAnimationCurve<float>,BansheeEngine::StdAlloc<T,BansheeEngine::GenAlloc>> &,std::vector<BansheeEngine::TNamedAnimationCurve<float>,BansheeEngine::StdAlloc<T,BansheeEngine::GenAlloc>> &) const' being compiled
1>          with
1>          [
1>              T=BansheeEngine::TNamedAnimationCurve<float>
1>          ]
1>D:\BansheeEngine\Source\BansheeFBXImporter\Source\BsFBXImporter.cpp(536): error C2819: type 'std::vector<BansheeEngine::TNamedAnimationCurve<float>,BansheeEngine::StdAlloc<T,BansheeEngine::GenAlloc>>' does not have an overloaded member 'operator ->'
1>          with
1>          [
1>              T=BansheeEngine::TNamedAnimationCurve<float>
1>          ]
1>  D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\vector(679): note: see declaration of 'std::vector<BansheeEngine::TNamedAnimationCurve<float>,BansheeEngine::StdAlloc<T,BansheeEngine::GenAlloc>>'
1>          with
1>          [
1>              T=BansheeEngine::TNamedAnimationCurve<float>
1>          ]
1>  D:\BansheeEngine\Source\BansheeFBXImporter\Source\BsFBXImporter.cpp(536): note: did you intend to use '.' instead?
1>D:\BansheeEngine\Source\BansheeFBXImporter\Source\BsFBXImporter.cpp(536): error C2039: 'position': is not a member of 'std::vector<BansheeEngine::TNamedAnimationCurve<float>,BansheeEngine::StdAlloc<T,BansheeEngine::GenAlloc>>'
1>          with
2>d:\bansheeengine\source\bansheefmod\include\BsFMODAudio.h(7): fatal error C1083: Cannot open include file: 'fmod.hpp': No such file or directory
2>  BsFMODAudioListener.cpp
1>          [
1>              T=BansheeEngine::TNamedAnimationCurve<float>
1>          ]
1>  D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\vector(679): note: see declaration of 'std::vector<BansheeEngine::TNamedAnimationCurve<float>,BansheeEngine::StdAlloc<T,BansheeEngine::GenAlloc>>'
1>          with
1>          [
1>              T=BansheeEngine::TNamedAnimationCurve<float>
1>          ]
1>D:\BansheeEngine\Source\BansheeFBXImporter\Source\BsFBXImporter.cpp(536): error C2039: '__this': is not a member of 'std::vector<BansheeEngine::TNamedAnimationCurve<float>,BansheeEngine::StdAlloc<T,BansheeEngine::GenAlloc>>'
1>          with
1>          [
1>              T=BansheeEngine::TNamedAnimationCurve<float>
1>          ]
1>  D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\vector(679): note: see declaration of 'std::vector<BansheeEngine::TNamedAnimationCurve<float>,BansheeEngine::StdAlloc<T,BansheeEngine::GenAlloc>>'
1>          with
1>          [
1>              T=BansheeEngine::TNamedAnimationCurve<float>
1>          ]
1>D:\BansheeEngine\Source\BansheeFBXImporter\Source\BsFBXImporter.cpp(539): error C2819: type 'BansheeEngine::TAnimationCurve<float>' does not have an overloaded member 'operator ->'
1>  D:\BansheeEngine\Source\BansheeCore\Include\BsAnimationClip.h(88): note: see declaration of 'BansheeEngine::TAnimationCurve<float>'
1>  D:\BansheeEngine\Source\BansheeFBXImporter\Source\BsFBXImporter.cpp(539): note: did you intend to use '.' instead?
1>D:\BansheeEngine\Source\BansheeFBXImporter\Source\BsFBXImporter.cpp(539): error C2232: '->BansheeEngine::TAnimationCurve<float>::makeAdditive': left operand has 'class' type, use '.'
3>------ Build started: Project: BansheeEditorExec, Configuration: Debug Win32 ------
3>LINK : fatal error LNK1104: cannot open file 'D:\BansheeEngine\lib\x86\Debug\BansheeFBXImporter.lib'
2>D:\BansheeEngine\Source\BansheeFMOD\Include\BsFMODAudio.h(7): fatal error C1083: Cannot open include file: 'fmod.hpp': No such file or directory
2>  BsFMODAudioClip.cpp
2>D:\BansheeEngine\Source\BansheeFMOD\Include\BsFMODAudioClip.h(8): fatal error C1083: Cannot open include file: 'fmod.hpp': No such file or directory
2>  BsFMODAudio.cpp
2>D:\BansheeEngine\Source\BansheeFMOD\Include\BsFMODAudio.h(7): fatal error C1083: Cannot open include file: 'fmod.hpp': No such file or directory
2>  Generating Code...
4>------ Skipped Build: Project: ALL_BUILD, Configuration: Debug Win32 ------
4>Project not selected to build for this solution configuration 
========== Build: 0 succeeded, 3 failed, 21 up-to-date, 1 skipped ==========

The fmod is not installed because I chose to use OpenAudio, the other errors however I can't explain.

**Comment by MXSteel** [comment]
Might as well add - "Game" compiled and ran, but crashed with the following issue: 

**Warning** : 
Attempting to open a file that doesn't exist: GameSettings.asset
**Error**:
 Fatal error occurred and the program has to terminate!
Unhandled exception at 0x9178342. Access violation reading 0x0.

Stack trace:
BansheeEngine::FileDecoder::decode() - 0x9178342 File[bsfileserializer.cpp:82 (20)] Module[BansheeUtility.dll]
runApplication() - 0x3617043 File[main.cpp:55 (30)] Module[Game.exe]
WinMain() - 0x3619841 File[main.cpp:36 (0)] Module[Game.exe]
invoke_main() - 0x3666142 File[exe_common.inl:99 (0)] Module[Game.exe]
__scrt_common_main_seh() - 0x3665728 File[exe_common.inl:253 (5)] Module[Game.exe]
__scrt_common_main() - 0x3665373 File[exe_common.inl:296 (0)] Module[Game.exe]
WinMainCRTStartup() - 0x3666168 File[exe_winmain.cpp:17 (0)] Module[Game.exe]
0x1978872746 Module[kernel32.dll]
0x2001772402 Module[ntdll.dll]
0x2001772357 Module[ntdll.dll]

**Comment by BearishSun** [comment]
Are you at HEAD? Master branch is unstable and you might be on a commit that's broken.

"Game" project isn't meant to be compiled on its own, it's an executable used by the editor, which also outputs the files that it is missing. You should run either "BansheeEditorExec" or "ExampleProject".

**Comment by MXSteel** [comment]
I couldn't run ExampleProject due to the error in the OP.

I was indeed at HEAD. I'll commit to the latest "preview" and report if there are any issues.

**Comment by BearishSun** [comment]
HEAD of master should be fine as well. I'd ask you to double-check that you are on HEAD as the error messages you posted don't match up with my code on HEAD. 

I noticed you have your own fork: https://github.com/MXSteel/BansheeEngine, which is 13 commits behind.

**Comment by MXSteel** [comment]
http://i.imgur.com/hHm1sN2.mp4

This is a non-issue, I was indeed 13 commits behind.
