### ISSUE TITLE
Can't load bsfPhysX.dll

### ISSUE THREAD

**Issue by TumblerSGQ** [BearishSun/BansheeEngine#330]
![image](https://user-images.githubusercontent.com/12553991/66478633-667a5800-eacd-11e9-81eb-658627673d23.png)

**Comment by TumblerSGQ** [comment]
master branch

**Comment by ataulien** [comment]
Make sure to have the actual PhysX dll available. See https://github.com/GameFoundry/bsf/issues/366 for further information.

**Comment by BearishSun** [comment]
This is generally caused by CMake download failing during the initial setup. Or by attempting to compile the 32-bit version of Banshee (as we don't provide 32-bit version of dependencies).

**Comment by TumblerSGQ** [comment]
![image](https://user-images.githubusercontent.com/12553991/66535248-97996d80-eb4b-11e9-92b9-aa1cda5dde26.png)
 
The physX dll is there,  64bit.

**Comment by TumblerSGQ** [comment]
![image](https://user-images.githubusercontent.com/12553991/66536936-51470d00-eb51-11e9-9e0d-cebb35669d28.png)

![image](https://user-images.githubusercontent.com/12553991/66536900-32e11180-eb51-11e9-8120-368b35da6146.png)

**Comment by TumblerSGQ** [comment]
It's OK now. Thanks
