### ISSUE TITLE
Crash wehen execute a compute task

### ISSUE THREAD

**Issue by TumblerSGQ** [BearishSun/BansheeEngine#331]
![image](https://user-images.githubusercontent.com/12553991/66569271-c17b8000-eb9d-11e9-9c8f-579884024992.png)

GraphicCard: Intel HD630

**Comment by BearishSun** [comment]
Please post the crash log. There is not enough information in that screenshot for me to determine what would be the cause.

**Comment by TumblerSGQ** [comment]
It crashes in the Graphic Driver

**Comment by BearishSun** [comment]
Thanks. In that case I'll close this issue and we can track it in #324.
