### ISSUE TITLE
Need update on GUI: No response from GUI on current build.

### ISSUE THREAD

**Issue by christianclavet** [BearishSun/BansheeEngine#332]
Hi! 

Seem the GUI is not responding now with the current build (Window 10-Vulkan), made on october 13.

Seem related to the changes dones in the GUI of BSF, but the code need to be updated on the editor side to make it work again...

Until then, the editor seem broken.

To reproduce:
1- Create a new build of the editor (if possible using Vulkan)
2- Start the editor and create a new project.
3- Editor GUI is draw, but the project window does'nt close and the GUI is not updating. Doesnt seem to get events. I have to force close the application using the task manager on Windows.

**Comment by BearishSun** [comment]
Hey, thanks for the report. I didn't notice this locally but I didn't try a fresh build. I should have time to take a closer look near the end of the week.

**Comment by BearishSun** [comment]
This should be resolved on latest, the project window was failing to close properly - and since it was modal it was blocking interactions with everything else.

**Comment by christianclavet** [comment]
Thanks. Created a new build with the changes and now work correctly. I was finding it strange that the GUI was working at first (project selection) that would not work once you were in the editor.

So fix is confirmed
