### ISSUE TITLE
Crash when import picture and one warning repeatedly shows

### ISSUE THREAD

**Issue by zhagsenkk** [BearishSun/BansheeEngine#34]
Win10 64 
Warning	Unrealiable GPU timer query detected.
Warning	Unrealiable GPU timer query detected.
Warning	Unrealiable GPU timer query detected.
Error	Fatal error occurred and the program has to terminate!
InvalidParametersException - Texture width & height must be powers of 2.
in class std::vector,class BansheeEngine::StdAlloc,class BansheeEngine::GenAlloc> > __cdecl BansheeEngine::PixelUtil::genMipmaps(const class BansheeEngine::PixelData &,const struct BansheeEngine::MipMapGenOptions &) [..\..\Source\BansheeCore\Source\BsPixelUtil.cpp:1706]

Stack trace: 
BansheeEngine::PixelUtil::genMipmaps() - 0x140726530414347 File[bspixelutil.cpp:1706 (256)] Module[BansheeCore.dll]
BansheeEngine::FreeImgImporter::import() - 0x140726511214699 File[bsfreeimgimporter.cpp:164 (39)] Module[BansheeFreeImgImporter.dll]
BansheeEngine::SpecificImporter::importAll() - 0x140726531015539 File[bsspecificimporter.cpp:13 (0)] Module[BansheeCore.dll]
BansheeEngine::Importer::_importAllRaw() - 0x140726530557075 File[bsimporter.cpp:124 (54)] Module[BansheeCore.dll]
BansheeEngine::Importer::importAll() - 0x140726530554893 File[bsimporter.cpp:90 (0)] Module[BansheeCore.dll]
BansheeEngine::ProjectLibrary::reimportResourceInternal() - 0x140726658374516 File[bsprojectlibrary.cpp:432 (121)] Module[BansheeEditor.dll]
BansheeEngine::ProjectLibrary::addResourceInternal() - 0x140726658371678 File[bsprojectlibrary.cpp:280 (0)] Module[BansheeEditor.dll]
BansheeEngine::ProjectLibrary::checkForModifications() - 0x140726658369031 File[bsprojectlibrary.cpp:116 (0)] Module[BansheeEditor.dll]
BansheeEngine::ScriptProjectLibrary::internal_Refresh() - 0x140726528676920 File[bsscriptprojectlibrary.cpp:75 (0)] Module[SBansheeEditor.dll]
0x2409818247107
0x2409860472632
0x2409818457052
0x2409860809216
0x2409814856800
0x2409818146128
0x2409830839600
0x2409814884224
0x479960428784
0x479960428656
0x2409860809216
0x29126788
0x2409815100144

**Comment by BearishSun** [comment]
Hi thank you for reporting the issue. I have reproduced and fixed the issue on master under commit a8e30ad6f1268efa64b77bae55481fd7532bcca4.
