### ISSUE TITLE
InternalErrorException when launching pre-built binaries

### ISSUE THREAD

**Issue by ArchaicMage** [BearishSun/BansheeEngine#36]
Running BansheeEditorExec.exe from pre-built binaries results in _InternalErrorException_ when loading library `BansheeD3D11RenderAPI.dll`. I have included the compiled crash report. If I had to guess, the working directory and the relative dependencies path are not playing well together.

Recreation Steps
1. Extract pre-built binaries from Banshee_Win_x64_v0.3.0.zip.
2. Launch BansheeEditorExec.exe

[log.txt](https://github.com/BearishSun/BansheeEngine/files/381532/log.txt)

**Comment by BearishSun** [comment]
Hi, are you running on Windows 8 (not 8.1) or earlier? Also does your install path contain any non-standard characters?

**Comment by ArchaicMage** [comment]
I am running Windows 10 x64. My System and Local PATH variables are clean of any non-standard special characters.

**Comment by BearishSun** [comment]
What is most likely happening is that some .dll cannot be found. I cannot tell which on the basis of the log. If you wish to dig further, try downloading http://www.dependencywalker.com/ and then opening BansheeD3D11RenderAPI.dll, and see if any of the top-level dependencies cannot be found.

This is how it's supposed to look: https://postimg.org/image/squhkdo0n/

**Comment by ArchaicMage** [comment]
After running BansheeD3D11RenderAPI.dll through Dependency Walker there were a total of 379 missing dependencies. D3DCOMPILER_43.dll was the only top-level dependency I could see that was missing. 

It looks like DirectX Runtime June 2010 contains an optional feature that was missing from my machine. After downloading the Runtime [here](https://www.microsoft.com/en-us/download/confirmation.aspx?id=8109), extracting it to a local directory, and running the setup executable (I forget the filename) Banshee launches without any problems. 

Thank you for tuning me in to Dependency Walker!

**Comment by BearishSun** [comment]
Interesting, glad you got it sorted. We'll need to ship that .dll with later versions.
