### ISSUE TITLE
Tutorial for compiling

### ISSUE THREAD

**Issue by RealAquilus** [BearishSun/BansheeEngine#38]
Hi! I have Visual Studio 2013 Update 5 can i compile the source? And what i need for do that plus vs? (i already have cmake)﻿.
In case why don't make a tutorial for help noob like me to compile the engine? I want to learn with it :). It Seems amazing!

**Comment by BearishSun** [comment]
Hi, there is a tutorial over here: https://github.com/BearishSun/BansheeEngine/blob/master/Documentation/GitHub/compiling.md

Everything you need is listed on that page. You must use VS 2015 though.

**Comment by RealAquilus** [comment]
I have some problem with VS2015 can i compile an older version with VS2013? If not i will try redownloading VS2015 and hope this time works xD

**Comment by BearishSun** [comment]
v0.1 works with VS2013, but it is two years old, I do not suggest using it.

https://github.com/BearishSun/BansheeEngine/releases/tag/v0.1.0
