### ISSUE TITLE
Use TBB

### ISSUE THREAD

**Issue by sentik** [BearishSun/BansheeEngine#44]
Hello, why you do not want to use Intel TBB, as MemoryAllocator? I think it will give you many benefits as using the memory pool from the same package. Yet to my knowledge, have intel mkl to work with matrices and numbers ..

**Comment by BearishSun** [comment]
I'm not familiar with it, but this appears to be mostly useful for parallel algorithms working on shared data, which is not the case in Banshee, where threads are higher level and mostly operate independently. If you have a specific use case where it might be beneficial to Banshee let me know.

**Comment by sentik** [comment]
first came across an article in Google. 
https://www.threadingbuildingblocks.org/tutorial-intel-tbb-scalable-memory-allocator

Perhaps "2 lines of code" can help your project become even better.

all the best and good luck!

**Comment by BearishSun** [comment]
If I run into a situation where such allocator can be useful, I'll definitely consider it, thanks.
