### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by DmitryAvramenko** [BearishSun/BansheeEngine#45]
Hello! I see you have finished with the animations and sounds. Can you do a new build in stable branch? Something like v0.4.0 or beta release.
I wanna to try it.  
Thanks :)

**Comment by BearishSun** [comment]
Hey, you're right, but there's still a little bit work to do on the animations. I'll be releasing a new preview build binaries (v0.4) by the end of September (hopefully).

**Comment by fuzun** [comment]
@BearishSun Any thing to say about mobile platforms?

**Comment by BearishSun** [comment]
I don't have an exact timeline for mobile platforms. I'll probably start working on them sometime next year.

**Comment by virror** [comment]
Any progress regarding a website?
I think this is vital to start building a community and to get more ppl helping.
This should be one of the top priorities in my opinion.

**Comment by BearishSun** [comment]
Yes! Initial version of the site is almost ready and will go public at the same time 0.4 is released (by the end of September).

**Comment by virror** [comment]
Awesome : )

**Comment by BearishSun** [comment]
v0.4 has launched, you can get it from following the download link here on GitHub or on the site www.banshee3d.com.
