### ISSUE TITLE
Binaries release doesn't work.

### ISSUE THREAD

**Issue by RealAquilus** [BearishSun/BansheeEngine#47]
0.3 run perfectly on my Windows 7 system. 0.4 not. it shows "D3dcompiler_47.dll not found". But when i download it from this site "https://www.dll-files.com/d3dcompiler_47.dll.html" i get these problem :
with the 64bit version it shows "problem with api-ms-core-stencyh-l1-2.0.dll"
with the 32bit (10...) it simply won't start.
with the other two 32bit version it is uploaded for a moment in ram and after 1sec closed, without shows for any moment the editor.
My specs are:
i7 4790k
r9 270x Toxic
Maximus VII Ranger
16gb 1600mhz ddr3
windows 7 ultimate
i have all visual c++ redistributable.
directx 11 (checked with dxdiag)
what's the problem? I want to run the new version with skeletal animation!

**Comment by BearishSun** [comment]
Hi! Can you try downloading the DirectX SDK: https://www.microsoft.com/en-us/download/confirmation.aspx?id=8109 , and report if that fixes the problem? Thanks.

**Comment by RealAquilus** [comment]
Same problem, nothing change :( .

**Comment by BearishSun** [comment]
Try downloading DirectX SDK instead: https://www.microsoft.com/en-us/download/details.aspx?id=6812 .

If after download/install it still doesn't work, try looking in the install folder for the file and copying it next to the editor executable. This should almost certainly work.

**Comment by RealAquilus** [comment]
Again same error, in the DirectX SDk there are no D3dcompiler_47.dll :(

**Comment by BearishSun** [comment]
I uploaded my own file, along with another one that might be needed: http://bearishsun.thalassa.feralhosting.com/d3dcompiler.zip

See if using them does anything

**Comment by RealAquilus** [comment]
Yeahh!!! With your d3dcompiler_47.dll now works!! without adding the other dll too! Thanks!

**Comment by BearishSun** [comment]
Great, glad we got it stored, I'll include the file in future distributions.
