### ISSUE TITLE
Some includes are missing

### ISSUE THREAD

**Issue by FFalcon** [BearishSun/BansheeEngine#5]
In BansheeOISInput/Include/BsInputHandlerOIS.h the includes <OIS/OIS*.h> (Events,InputManager, etc) are missing or maybe I am not looking in the right places ?

**Comment by BearishSun** [comment]
You need to download the dependencies archive (linked at the front page in the readme) and extract them to the project folder. They contain all the third party includes and libraries.

In case you have done that then something else might have gone wrong, in which case make sure your compiler can find the dependencies. The ones you are looking for are in BansheeOISInput\Dependencies\Include\OIS.

**Comment by FFalcon** [comment]
Oh I guess I messed up the dependancies. Thanks a lot.
