### ISSUE TITLE
Dock Assertion

### ISSUE THREAD

**Issue by carlosmarti** [BearishSun/BansheeEngine#53]
Had some time today to break the editor some more. 
When you move the dock from it's default position and let go in between the viewport and one of the docks. It will move the dock in the same place as the library dock right on top of it. 

To Repeat Bug.
Drag and drop a dock in between the viewport and another dock. 
Try to click on the library dock that seems like it's fused with the dock moved.

Report of the banshee log.
![log](https://cloud.githubusercontent.com/assets/5507549/19415617/3c7790f2-932a-11e6-98d9-e68fcd3ad99c.PNG)

**Comment by BearishSun** [comment]
Fixed in d33c3fd4ecbe44a774b485d5a62d301d6a91eb94! Also fixed those parameter warnings - there was an issue in the shader and the dock overlay wasn't rendering because of them, it should now render properly.
