### ISSUE TITLE
Multi-Mesh FBX not working as intended 

### ISSUE THREAD

**Issue by dragonCASTjosh** [BearishSun/BansheeEngine#62]
FBX files with more than 1 mesh contained do not import correctly. View images for Example, I have also included a sample mesh that you should be able to use to demonstrate the issue. 

Images:
![blender](https://cloud.githubusercontent.com/assets/3044415/21103271/a21d1a9a-c079-11e6-8da1-9c503c5bcfbd.PNG)
![editor](https://cloud.githubusercontent.com/assets/3044415/21103270/a21be6b6-c079-11e6-90d1-a00c2edf7573.PNG)

Model:
https://drive.google.com/file/d/0B7EwsKWU8ATkMGpIRjdrMkp0NHM/view?usp=sharing

**Comment by BearishSun** [comment]
Hey, thanks for the report, I think I have a rough idea what's going on. Will hopefully be resolved by the end on the week when I'm done with current tasks.

**Comment by BearishSun** [comment]
Should be resolved with e3836cb1135d6bdc4b7a8b5543fa862e709ea9f4.

**Comment by dragonCASTjosh** [comment]
The fix you committed seems to have caused/revealed another issue. the best way I can describe it is by use of video. It seems to come into effect whenever there is more than 1 mesh in the viewport.

Video:
https://drive.google.com/file/d/0B7EwsKWU8ATkSVpkWDZlU09qeEk/view?usp=sharing

**Comment by BearishSun** [comment]
I can reproduce the issue, will let you know when its fixed.

**Comment by dragonCASTjosh** [comment]
Any closer to solving the issue?

**Comment by BearishSun** [comment]
Hey, I'm hoping to get around to it today or later this week.

**Comment by BearishSun** [comment]
The issue should be resolved with 3b15a8414093dbaca6bd2b8c241dfda690adfdd3

**Comment by dragonCASTjosh** [comment]
All seams to be solved from my latest testing. Thanks :)
