### ISSUE TITLE
unable to build in Windows

### ISSUE THREAD

**Issue by RallyTronics** [BearishSun/BansheeEngine#66]
When trying to build with VS2015 I get the following errors:
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2065	'BS_AUDIO_MODULE': undeclared identifier	Game	f:\bansheeengine\source\game\source\main.cpp	72	
Error	C2065	'BS_INPUT_MODULE': undeclared identifier	Game	f:\bansheeengine\source\game\source\main.cpp	74	
Error	C2065	'BS_PHYSICS_MODULE': undeclared identifier	Game	f:\bansheeengine\source\game\source\main.cpp	73	
Error	C2065	'BS_RENDERER_MODULE': undeclared identifier	Game	f:\bansheeengine\source\game\source\main.cpp	71	
Error	C2065	'BS_RENDER_API_MODULE': undeclared identifier	Game	f:\bansheeengine\source\game\source\main.cpp	70	
Error	LNK1120	1 unresolved externals	BansheeUtilityTest	F:\BansheeEngine\bin\x64\Debug\BansheeUtilityTest.exe	1	
Error	LNK2019	unresolved external symbol "public: __cdecl bs::FileSystemTestSuite::FileSystemTestSuite(void)" (??0FileSystemTestSuite@bs@@QEAA@XZ) referenced in function "public: __cdecl std::_Ref_count_obj_alloc<class bs::FileSystemTestSuite,class bs::StdAlloc<class bs::FileSystemTestSuite,class bs::GenAlloc> >::_Ref_count_obj_alloc<class bs::FileSystemTestSuite,class bs::StdAlloc<class bs::FileSystemTestSuite,class bs::GenAlloc> ><>(class bs::StdAlloc<class bs::FileSystemTestSuite,class bs::GenAlloc> const &)" (??$?0$$V@?$_Ref_count_obj_alloc@VFileSystemTestSuite@bs@@V?$StdAlloc@VFileSystemTestSuite@bs@@VGenAlloc@2@@2@@std@@QEAA@AEBV?$StdAlloc@VFileSystemTestSuite@bs@@VGenAlloc@2@@bs@@@Z)	BansheeUtilityTest	F:\BansheeEngine\Build\VS2015\BansheeUtility\BsUtilityTest.obj	1

**Comment by BearishSun** [comment]
Try compiling just BansheeEditorExec or one of the example executables, instead of the entire solution. The projects that are failing are non-critical and I'll get around to fixing them soon.

**Comment by RallyTronics** [comment]
Cool, thanks!

**Comment by BearishSun** [comment]
Resolved in 5496a2e79a4c7e6c5c7d345eb0ccc458cc06ab66
