### ISSUE TITLE
Incorrectly importing FBX

### ISSUE THREAD

**Issue by nem0** [BearishSun/BansheeEngine#67]
there are two issues
1. model is broken - see images
2. crash if I try to import animation

model: [default_pose_char+wep.zip](https://github.com/BearishSun/BansheeEngine/files/737444/default_pose_char.wep.zip)

Correct bind pose in open3mod:
![a](https://cloud.githubusercontent.com/assets/153526/22403477/9359cc00-e618-11e6-8b0f-306413dbc072.png)

imported model in BansheeEngine:
![b](https://cloud.githubusercontent.com/assets/153526/22403478/93749da0-e618-11e6-9960-c2e1e07ed1e3.png)

**Comment by BearishSun** [comment]
Hi, thanks for the report. The two issues you mentioned have been resolved on the internal build, the fix will be available with the next binary release.

I did find a new issue regarding skeleton generation when using your model. I'll report back when that is resolved.

**Comment by christianclavet** [comment]
I had that offset with a model, tried with another and the local rotation seem wrong, but position seem good.
![banshee](https://user-images.githubusercontent.com/13395943/28998641-6d0941dc-79fe-11e7-9ac6-8a0ef9d33c2f.JPG)

For that model it doesnt crash with the animation data, but got warnings and I had nothing in the animation clip. (Added the bone and animation components to the model)

**Comment by BearishSun** [comment]
If you send me the model that has the issue that would be greatly appreciated. You can use my email (on my GitHub profile) to send it privately, if that's possible. Thanks!

**Comment by christianclavet** [comment]
Sent you a mail.

**Comment by BearishSun** [comment]
I have resolved a bunch of FBX import problems with 36e1caf94b87b61145ef7a2bc991837616c961a4. All static meshes I've tested with now import properly, including all the meshes in this issue. I have yet to test animation, and will get around to it later on.

**Comment by BearishSun** [comment]
Many FBX animation issues have now been resolved as well. I'm closing this issue. There are still remaining issue regarding editor and the animation window. See #120.
