### ISSUE TITLE
Wrong CMake version in setup.bat

### ISSUE THREAD

**Issue by duncfro** [BearishSun/BansheeEngine#70]
I pulled (at  193af344096ed4f4e13dd3a161360457eba51b7a) and tried setup.bat, but I got a CMake version mismatch error:

![image](https://cloud.githubusercontent.com/assets/2336052/24990760/0a50f04a-1fcb-11e7-923b-fc6e9e57e086.png)

**Comment by BearishSun** [comment]
Thanks for reporting the issue. This is now resolved, ed415e9858c86ee3c515a9f0f417618ea4f7327d.
