### ISSUE TITLE
ObjectMoblity

### ISSUE THREAD

**Issue by TinTouneT** [BearishSun/BansheeEngine#75]
When trying to first compile, i have error The type or namespace ObjectMobility could not be found in some cs files. have i forgotten something ?

**Comment by BearishSun** [comment]
That enum is a part of an auto-generated file which is generated during script binding generation. Script bindings should be generated automatically during the build process as long as the GENERATE_SCRIPT_BINDINGS property is enabled in CMake (on by default or when running straight from setup.bat). Make sure that this is enabled and that generation isn't reporting any errors.

**Comment by TinTouneT** [comment]
Thx for your quick answer. The matter was i had written over an old cmake build whitch was not correctly build.
