### ISSUE TITLE
Access violation reading 0x0.

### ISSUE THREAD

**Issue by TinTouneT** [BearishSun/BansheeEngine#76]
I have built the entire solution, but when trying to execute i have an error. Crash reporting is : 
A fatal error occurred and the program has to terminate!
Unhandled exception at 0x140735859136751. Access violation reading 0x0.

Stack trace: 
Xsc::Expr::FindFirstOf() - 0x140735859136751 File[ast.cpp:89 (39)] Module[BansheeSL.dll]
Xsc::Expr::FindFirstOf() - 0x140735859137162 File[ast.cpp:125 (0)] Module[BansheeSL.dll]
Xsc::GLSLConverter::VisitReturnStmnt() - 0x140735859592088 File[glslconverter.cpp:449 (36)] Module[BansheeSL.dll]
Xsc::ReturnStmnt::Visit() - 0x140735858349061 File[ast.h:981 (69)] Module[BansheeSL.dll]
Xsc::Visitor::Visit() - 0x140735857664730 File[visitor.h:162 (0)] Module[BansheeSL.dll]
Xsc::Converter::VisitScopedStmntsFromHandler() - 0x140735859544458 File[converter.cpp:200 (20)] Module[BansheeSL.dll]
Xsc::Converter::VisitScopedStmnt() - 0x140735859541680 File[converter.cpp:124 (0)] Module[BansheeSL.dll]
Xsc::GLSLConverter::VisitIfStmnt() - 0x140735859591660 File[glslconverter.cpp:416 (0)] Module[BansheeSL.dll]
Xsc::IfStmnt::Visit() - 0x140735858348197 File[ast.h:946 (69)] Module[BansheeSL.dll]
Xsc::Visitor::Visit() - 0x140735857664730 File[visitor.h:162 (0)] Module[BansheeSL.dll]
Xsc::Converter::VisitScopedStmntsFromHandler() - 0x140735859544458 File[converter.cpp:200 (20)] Module[BansheeSL.dll]
Xsc::Converter::VisitScopedStmntList() - 0x140735859541819 File[converter.cpp:131 (0)] Module[BansheeSL.dll]
Xsc::GLSLConverter::VisitCodeBlock() - 0x140735859586653 File[glslconverter.cpp:137 (0)] Module[BansheeSL.dll]
Xsc::CodeBlock::Visit() - 0x140735858347426 File[ast.h:366 (66)] Module[BansheeSL.dll]
Xsc::Visitor::Visit >() - 0x140735857095083 File[visitor.h:161 (41)] Module[BansheeSL.dll]
Xsc::Visitor::VisitFunctionDecl() - 0x140735857083159 File[visitor.cpp:116 (0)] Module[BansheeSL.dll]
Xsc::GLSLConverter::ConvertFunctionDeclEntryPoint() - 0x140735859597935 File[glslconverter.cpp:778 (0)] Module[BansheeSL.dll]
Xsc::GLSLConverter::ConvertFunctionDecl() - 0x140735859597030 File[glslconverter.cpp:729 (0)] Module[BansheeSL.dll]
Xsc::GLSLConverter::VisitFunctionDecl() - 0x140735859588896 File[glslconverter.cpp:280 (0)] Module[BansheeSL.dll]
Xsc::FunctionDecl::Visit() - 0x140735858348098 File[ast.h:700 (66)] Module[BansheeSL.dll]
Xsc::Visitor::Visit() - 0x140735857664730 File[visitor.h:162 (0)] Module[BansheeSL.dll]
Xsc::Converter::VisitScopedStmntsFromHandler() - 0x140735859544458 File[converter.cpp:200 (20)] Module[BansheeSL.dll]
Xsc::Converter::VisitScopedStmntList() - 0x140735859541819 File[converter.cpp:131 (0)] Module[BansheeSL.dll]
Xsc::GLSLConverter::VisitProgram() - 0x140735859586521 File[glslconverter.cpp:128 (0)] Module[BansheeSL.dll]
Xsc::Program::Visit() - 0x140735858348866 File[ast.h:294 (66)] Module[BansheeSL.dll]
Xsc::Visitor::Visit() - 0x140735857664618 File[visitor.h:162 (0)] Module[BansheeSL.dll]
Xsc::GLSLConverter::ConvertASTPrimary() - 0x140735859585871 File[glslconverter.cpp:82 (0)] Module[BansheeSL.dll]
Xsc::Converter::ConvertAST() - 0x140735859539103 File[converter.cpp:26 (0)] Module[BansheeSL.dll]
Xsc::GLSLGenerator::GenerateCodePrimary() - 0x140735857537060 File[glslgenerator.cpp:85 (37)] Module[BansheeSL.dll]
Xsc::Generator::GenerateCode() - 0x140735857516702 File[generator.cpp:42 (34)] Module[BansheeSL.dll]
Xsc::CompileShaderPrimary() - 0x140735856570496 File[xsc.cpp:191 (58)] Module[BansheeSL.dll]
Xsc::CompileShader() - 0x140735856566120 File[xsc.cpp:245 (47)] Module[BansheeSL.dll]
bs::HLSLtoGLSL() - 0x140735856153781 File[bsslfxcompiler.cpp:261 (30)] Module[BansheeSL.dll]
::operator()() - 0x140735856140414 File[bsslfxcompiler.cpp:1629 (45)] Module[BansheeSL.dll]
bs::BSLFXCompiler::parseShader() - 0x140735856367521 File[bsslfxcompiler.cpp:1639 (0)] Module[BansheeSL.dll]
bs::BSLFXCompiler::compile() - 0x140735856318144 File[bsslfxcompiler.cpp:341 (33)] Module[BansheeSL.dll]
bs::SLImporter::import() - 0x140735855890342 File[bsslimporter.cpp:42 (74)] Module[BansheeSL.dll]
bs::Importer::import() - 0x140735938659204 File[bsimporter.cpp:81 (0)] Module[BansheeCore.dll]
::operator()() - 0x140735903725434 File[bsbuiltinresourceshelper.cpp:109 (0)] Module[BansheeEngine.dll]
bs::BuiltinResourcesHelper::importAssets() - 0x140735903798186 File[bsbuiltinresourceshelper.cpp:177 (87)] Module[BansheeEngine.dll]
bs::BuiltinResources::preprocess() - 0x140735903419785 File[bsbuiltinresources.cpp:416 (0)] Module[BansheeEngine.dll]
bs::BuiltinResources::BuiltinResources() - 0x140735902913633 File[bsbuiltinresources.cpp:255 (0)] Module[BansheeEngine.dll]
bs::bs_new() - 0x140735908976498 File[bsmemoryallocator.h:339 (52)] Module[BansheeEngine.dll]
bs::Module::startUp<>() - 0x140735908979455 File[bsmodule.h:71 (5)] Module[BansheeEngine.dll]
bs::Application::onStartUp() - 0x140735908992029 File[bsapplication.cpp:61 (0)] Module[BansheeEngine.dll]
bs::EditorApplication::onStartUp() - 0x140735974140919 File[bseditorapplication.cpp:85 (0)] Module[BansheeEditor.dll]
bs::Module::startUp() - 0x140735973779988 File[bsmodule.h:93 (0)] Module[BansheeEditor.dll]
bs::EditorApplication::startUp() - 0x140735974160227 File[bseditorapplication.cpp:153 (0)] Module[BansheeEditor.dll]
WinMain() - 0x140700116592454 File[bseditorexec.cpp:25 (0)] Module[BansheeEditorExec.exe]
invoke_main() - 0x140700116596045 File[exe_common.inl:99 (0)] Module[BansheeEditorExec.exe]
__scrt_common_main_seh() - 0x140700116595735 File[exe_common.inl:253 (5)] Module[BansheeEditorExec.exe]
__scrt_common_main() - 0x140700116595422 File[exe_common.inl:296 (0)] Module[BansheeEditorExec.exe]
WinMainCRTStartup() - 0x140700116596073 File[exe_winmain.cpp:17 (0)] Module[BansheeEditorExec.exe]
0x140736974521188 Module[KERNEL32.DLL]
0x140737012854993 Module[ntdll.dll]

**Comment by BearishSun** [comment]
My guess is that code for a third party library is out of date since that looks like an issue that was already fixed.

Try performing `git submodule update` which will retrieve the latest code for third party libraries. Then delete the `/Dependencies/Build/` folder which will force the dependencies to recompile. And re-run the build.

Let me know if that was the issue. I'll try to make this process automatic in the future.

**Comment by TinTouneT** [comment]
Yes that was the issue. Now i can compile and run. Thx.
