### ISSUE TITLE
Any reason why you chose Box2D for 2D physics? Have you considered Chipmunk?

### ISSUE THREAD

**Issue by Alan-FGR** [BearishSun/BansheeEngine#77]
Hello there. First of all I'd like to congrat on the awesome work being done here.

I just saw in the roadmap that you chose Box2D for the 2D physics, I guess that's because it's the most popular engine by far so you're just used to it, but have you considered Chipmunk?

In my opinion, Box2D doesn't really match the appeal of this engine because it feels old and it's missing some pretty important optimizations. Chipmunk has some quite neat and modern features and the spatial optimization (as long as you keep it reasonable) is in the worst case as fast as Box2D's, and in the best, when you fine-tune for your average objects, much faster (the engine could provide visual feedback for tweaking the settings). The important downside is the lack of speculative collision detection, but Box2D's is far from reliable and it's extremely slow anyway, which makes it pretty much unusable for a lot of use cases, to prevent tunneling on static or low velocity bodies, casting an approximate sweep shape between the physics world ticks is a much faster solution, and can be optimized to extremes, for example to a single raycast when preventing tunneling isn't that important.

Anyways, just a suggestion. Keep up the good work! :)

**Comment by BearishSun** [comment]
I wasn't aware of Chipmunk. The only reason I picked Box2D because it seemed to be fairly standard for 2D physics + I haven't done any research on the topic yet.

When the time comes I'll do some proper research and weight the cons/pros of each. Your argument certainly makes me lean in the favor of Chipmunk though. 

Thanks for bringing this to my attention!

**Comment by Alan-FGR** [comment]
You're welcome! 😄
Yeah, it's a fact that Box2D is what one would call the "industry standard", but it has it's disadvantages. I'm glad to know you're going to consider Chipmunk when the time comes! Keep up the amazing work! 👍😃
PS: I'm not closing this because I don't know if you want to keep track of it.
