### ISSUE TITLE
Error At Startup

### ISSUE THREAD

**Issue by mamarilmanson** [BearishSun/BansheeEngine#78]
I have this window... but sad thing is that I can't find the file it was referring to...

![capture](https://user-images.githubusercontent.com/3820189/26858058-d3d5f0ca-4b61-11e7-9358-c360fc8735b8.PNG)

**Comment by mamarilmanson** [comment]
![capture](https://user-images.githubusercontent.com/3820189/26858375-6bd8cb6c-4b63-11e7-9ef9-b88586bf8fa3.PNG)

And this is my system specs...

**Comment by mamarilmanson** [comment]
![capture](https://user-images.githubusercontent.com/3820189/26858735-a0899d9e-4b65-11e7-8f2a-61cc88bc473f.PNG)

Sorry... this is the correct error...

**Comment by BearishSun** [comment]
Hi, this issue is known and has been previously resolved, see #49. Binaries including the fix will be available with the next major release, but for now you can download this patched version:  http://bearishsun.thalassa.feralhosting.com/BansheeEditor_v0.4p1.zip

**Comment by mamarilmanson** [comment]
Tried it... it's working now...

I was thinking even before… what if there were incomplete major features to lure in bug fixers and turn them to contributors… just a thought... :)
