### ISSUE TITLE
Crash Report on add in scene GUI widget

### ISSUE THREAD

**Issue by fascwind** [BearishSun/BansheeEngine#79]
I've tried add GUI winget on scene
[CrashReports.zip](https://github.com/BearishSun/BansheeEngine/files/1067230/CrashReports.zip)

**Comment by BearishSun** [comment]
You are running the 0.4 pre-compiled binaries, or have you compiled the engine yourself from master? In the former case, the issue is known and has been resolved on master.

**Comment by fascwind** [comment]
thnx. i have 0.4. How i can update win banshee editor?

**Comment by BearishSun** [comment]
You would have to compile the most recent version from source code, as there are no new binary releases since 0.4. I suggest you wait until 1.0 stable is released if you need something that works out of the box.

**Comment by fascwind** [comment]
I've had some trouble on configure in cmake:

CMake Error at CMake/GenerateScriptBindings.cmake:86 (message):
  Failed to generate script bindings.
Call Stack (most recent call first):
  CMakeLists.txt:228 (include)


[CMakeOutput.log.txt](https://github.com/BearishSun/BansheeEngine/files/1068141/CMakeOutput.log.txt)

**Comment by fascwind** [comment]
i've got trouble on generate in cmake. 
![screenshot_1](https://user-images.githubusercontent.com/2401625/27036477-5d605b06-4f9e-11e7-98df-631a5a6baff1.png)

**Comment by BearishSun** [comment]
Do you have Visual Studio 2015 installed? It is required for the build to work.

In case you are using Visual Studio 2017, a workaround is required for now, see #72 .

**Comment by fascwind** [comment]
Thx. Found. Yes I use 2017. Now not found corecrt.


![screenshot_1](https://user-images.githubusercontent.com/2401625/27037880-c2730116-4fa2-11e7-9f1e-87cf93c89c08.png)

**Comment by fascwind** [comment]
Not that folder i added).

**Comment by fascwind** [comment]
Thnx!
