### ISSUE TITLE
Where are the assets?

### ISSUE THREAD

**Issue by amerkoleci** [BearishSun/BansheeEngine#8]
Hi, I downloaded the binary release package and saw there are diffent *.asset which are binary files, are there somewhere the source of these files, for example shader .bsl files?

**Comment by BearishSun** [comment]
Hi, yes. If you download the Banshee precompiled dependencies archive they
are in the Built/Data/Raw sub-folder. I should have made that clearer.
Dana 27. sij 2016. 08:28 osoba "Amer Koleci" <notifications@github.com>
napisala je:

**Comment by amerkoleci** [comment]
Nice thank you, would be nice to have some tutorial on how to create shaders/materials, what is RenderBeast? lightmapping tool?

**Comment by BearishSun** [comment]
I'll be adding a full tutorial on how to write shaders before 1.0 release. RenderBeast is the renderer that determines how are scene objects displayed on the screen. That is something that is still a work in progress though.
