### ISSUE TITLE
BansheeEditor has memory leak

### ISSUE THREAD

**Issue by fascwind** [BearishSun/BansheeEngine#80]
I'm add on scene camera and renderable
banshee corrupt ~40GB memory.
![default](https://user-images.githubusercontent.com/2401625/27032404-13001106-4f8e-11e7-9e81-238d87ea14c9.png)

**Comment by BearishSun** [comment]
Thanks for the report, I am aware of the camera-related memory leak/crash. I'll resolve the issue once I shift my focus back on editor development.

**Comment by fascwind** [comment]
How I can help?

**Comment by BearishSun** [comment]
I have enough information to track down the issue, but if you want to take a look around the source code yourself and debug the issue, feel free.

**Comment by christianclavet** [comment]
On 0.4, using only the edit camera, the memory use seem stable. (I did not used any other camera)

**Comment by BearishSun** [comment]
I'm going to close this as I believe all major leaks have been fixed with #87.
