### ISSUE TITLE
Website down - http://bearishsun.thalassa.feralhosting.com/BansheeDependencies_VS2015_Master.zip -

### ISSUE THREAD

**Issue by mediabuff** [BearishSun/BansheeEngine#83]

**Comment by BearishSun** [comment]
Hi, I'm aware of the issue and I'm trying to resolve it with my hosting service. For now you can use this link: https://www.dropbox.com/s/bmvqpimzeicb87i/BansheeDependencies_VS2015_Master.zip?dl=0

**Comment by BearishSun** [comment]
This should be resolved with 5be6731a0826fed498b1cea2f6dcffe13c48fc6f.  Please note that I have switched hosts, and the old links still do not work. If you pull latest the build system will use the new links. 

I have also updated the build process, which is reflected in the updated [Compiling guide](https://github.com/BearishSun/BansheeEngine/blob/master/Documentation/GitHub/compiling.md).

**Comment by E3141** [comment]
Download failed: URL

http://data.banshee3d.com/BansheeDependencies_VS2015_Master.zip

**Comment by BearishSun** [comment]
The download appears to proceed correctly on my end. Perhaps it was a temporary issue?

**Comment by E3141** [comment]
The download stops at 32%. It stopped at 34% a couple of days ago.

**Comment by E3141** [comment]
I will download once again via a different provider in a couple of hours

**Comment by E3141** [comment]
Sorry for it has taken me so long to write back. The download is successful. However via mobile network but worked. Sorry for disturbing. Thank you for your reply.
