### ISSUE TITLE
Little problem with camera.

### ISSUE THREAD

**Issue by MaxDeadOriginal** [BearishSun/BansheeEngine#86]
When the "near-plane" is changed to 0, the Banshee stops.

**Comment by BearishSun** [comment]
Thanks for the report. It should be a simple fix, I'll let you know when it's resolved.

**Comment by christianclavet** [comment]
This is not accepted anymore in the inspector and will give back the old value so it no longer crash.
But If, I use 0 in far plane, will got an error (no crash and can recuperate).
![image](https://user-images.githubusercontent.com/13395943/60034071-cd3b4900-9677-11e9-8728-c4443882dd76.png)
I think this issue can be closed.

**Comment by BearishSun** [comment]
Thanks for checking. I agree, closing.
