### ISSUE TITLE
Time to start a community

### ISSUE THREAD

**Issue by raizam** [BearishSun/BansheeEngine#9]
How about starting with a Forum and wiki?

**Comment by BearishSun** [comment]
A website with a forum and wiki is planned, as well as extensive documentation section. However implementing remaining engine features is currently taking up all my time. Regardless I'm hoping to get it up and running soon.

**Comment by raizam** [comment]
I haven't tried Banshee, just watched the youtube demo, and I'm quite impressed!

I see you are maintaining D3D and GL renderers, have you ever considered using BGFX? https://github.com/bkaradzic/bgfx

**Comment by BearishSun** [comment]
Thanks! That project looks interesting, however I prefer having a fully customized solution for Banshee.

**Comment by raizam** [comment]
This is the kind of choice that needs study and time, but please, give it some thought.
You won't have to maintain D3d, GL, and later on, vulkan, Metal... and fully focus on the engine.

**Comment by clix9** [comment]
> That project looks interesting, however I prefer having a fully customized solution for Banshee.

Hello, how likely will Banshee support OpenGL ES 2.0 in the future?

**Comment by BearishSun** [comment]
Hi, very likely. OpenGL ES and mobile ports are planned - I can't give you a timeframe for them yet though.

**Comment by t-boom** [comment]
Not to be pushy, but is there any chance you have a timeline for when a Linux port may be available? I'd love to try the engine out, but I don't have any Windows boxes around.

**Comment by BearishSun** [comment]
There is no clear timeline for it yet, but best case scenario it will be available by the end of 2016. However it is much more likely it will be available sometime in the first half of 2017.

**Comment by t-boom** [comment]
Alright, I'll keep watching. With any luck I'll have a Windows box before then, but who knows. Keep up the amazing work!
