### ISSUE TITLE
Can't rename items in the library windows.

### ISSUE THREAD

**Issue by christianclavet** [BearishSun/BansheeEngine#90]
I was not able to rename an item in the library window.
Pressing F2 work, but can't complete the edit if I press "ENTER". If I click outside it revert to the old name.

I can rename properly in the hierachy window. Tested with 0.4

**Comment by BearishSun** [comment]
I'm aware of the issue and it will be resolved before v1.0 BETA release. Work on the editor is currently on standby as I finish the core systems.

**Comment by christianclavet** [comment]
Update on this. The release I built this week (12/01/17), Using the F2 key, was able to rename. But using the menu didnt worked.
**Method 1.** Select the item, and press F2 to rename
_Result:_ Item is highlighted and we can edit it name. Pressing ENTER and the item is renamed.

**Method 2:** Select the item, and use right mouse button to select RENAME
_Result:_ Item is highlighted and we can edit it name. Impossible to get out of this state, and have to select another item (item get back it's original name). The ENTER key is not working using this method.

**Comment by christianclavet** [comment]
Hi,
Found out that we can simply rename items in the **hierarchy window** by doing 2 click over the name. But this behavior is absent from the items of the **ressources window**. If possible, it should have this too, as it would improve the GUI consistency.
