### ISSUE TITLE
Banshee 0.4: Crash when resizing window

### ISSUE THREAD

**Issue by christianclavet** [BearishSun/BansheeEngine#91]
I had a crash when I resized the editor window in Win10. 
This only happened one time, and is difficult to reproduce. It scale really well most of the time and my desktop is in 4K. Just to put a note that the application might crash when you rescale the editor window in rare occasion.

**Comment by BearishSun** [comment]
It happened once to me as well but I have been unable to reproduce since. I'll look into it.
