### ISSUE TITLE
Small bug in platformAlignedAlloc

### ISSUE THREAD

**Issue by ravarcade** [BearishSun/BansheeEngine#95]
It may return adress of memory outside allocated block.

Your code:

```
inline void* platformAlignedAlloc(size_t size, size_t alignment)
{
	void* data = ::malloc(size + (alignment - 1) + sizeof(void*));
	if (data == nullptr)
		return nullptr;

	UINT8* alignedData = ((UINT8*)data) + sizeof(void*);
	alignedData += alignment - ((uintptr_t)alignedData) & (alignment - 1);

	((void**)alignedData)[-1] = data;
	return alignedData;
}

```
Example: call platformAlignedAlloc(1, 16); // we want 1 byte, we are on 32 bit platform sizeof(void *)=4
Lets say malloc will return adress 0x100c,
So:
data = 0x100c
alignedData = data + sizeof(void *) = 0x1010
alignedData += 16 - (0x1010 & 0xf) 
So alignedData = 0x1020
It is data + 20 bytes
and we ask malloc for 20 bytes.
Returned adress point to first byte outside block.

Why it not crash app? Because os alredy align memory to 16 bytes or add few spare bytes outside request memory block.

**Comment by BearishSun** [comment]
Thanks for the report, should be resolved with 78b17cdd371dbd0ede3b67379eca9e172b1e5712.
