### ISSUE TITLE
A Linux port question

### ISSUE THREAD

**Issue by NathanWarden** [BearishSun/BansheeEngine#97]
Hi Marko, it's really exciting to see Linux support is being worked on for this engine. I have a quick question. Is this for a Linux Editor as well as builds, or is it only for builds?

Thanks and keep up the amazing work!

**Comment by BearishSun** [comment]
Complete Linux support, including the editor.

**Comment by NathanWarden** [comment]
Wow, that's really awesome! Okay, two followup questions:

1) Because it's LGPL3, this means if I modify the engine the I must release the source, I understand that half. If I make a game with a modified version of the engine, I must release the source, but do I have to release the script code (C#) for my game?
2) Is there a way to send monthly donations to you?

Thanks :)

**Comment by BearishSun** [comment]
You do not have to release the source code of your game. The licensing is primarily intended to ensure any changes to the engine remain open source.

There isn't currently a way to support the project via donations, but I plan on setting up a Patreon as the v1.0 release nears. Save your money until then :)

**Comment by NathanWarden** [comment]
Awesome, that's good news on both points. Thanks for the quick responses!

**Comment by qntf** [comment]
Hi @BearishSun,
Is the cross-platform editor/engine support part of the codebase right now? Or is it coming soon?
Great news to hear!

**Comment by BearishSun** [comment]
It is currently a work in progress and should be finished in the next few weeks.
